# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Bandeira Chinesa — Significado, História e Factos sobre a Bandeira Vermelha de Cinco Estrelas",
        "description": "A bandeira chinesa explicada: significado das cinco estrelas, história da bandeira vermelha de cinco estrelas, cores e proporções oficiais, etiqueta de hasteamento e ilustrações temáticas.",
    },
    "brand": "Bandeira Chinesa",
    "nav": {"meaning": "Significado", "history": "História", "data": "Dados Técnicos", "gallery": "Galeria", "etiquette": "Etiqueta"},
    "hero": {
        "flag_alt": "Bandeira da República Popular da China — a bandeira vermelha de cinco estrelas",
        "title": "A Bandeira Vermelha de Cinco Estrelas",
        "subtitle": "Bandeira nacional da República Popular da China",
        "meta": "Adotada em 27 de setembro de 1949 · Proporção 3:2 · Designer: Zeng Liansong",
    },
    "meaning": {
        "title": "Significado e Simbolismo",
        "intro": "Adotado em 1949, o design combina cor, geometria e história política num emblema instantaneamente reconhecível.",
        "cards": [
            {"title": "O Campo Vermelho", "text": "O vermelho representa a revolução e é também a cor tradicional da boa sorte e da celebração na cultura chinesa."},
            {"title": "A Estrela Grande", "text": "A grande estrela dourada representa a liderança do Partido Comunista da China."},
            {"title": "As Quatro Estrelas Pequenas", "text": "Representam a grande unidade do povo chinês sob essa liderança — tradicionalmente descritas como a classe operária, o campesinato, a pequena burguesia urbana e a burguesia nacional."},
            {"title": "Orientação das Estrelas", "text": "Cada estrela pequena tem uma ponta apontada precisamente para o centro da estrela grande, simbolizando a união reunida em torno de um centro comum."},
            {"title": "Amarelo Dourado", "text": "Escolhido para se destacar de forma brilhante sobre o campo vermelho, simbolizando a luz da revolução a iluminar o país."},
        ],
    },
    "history": {
        "title": "História e Origem",
        "items": [
            {"date": "1949", "text": "Em 27 de setembro de 1949, dias antes da fundação da República Popular da China, a Conferência Consultiva Política do Povo Chinês adotou formalmente a bandeira vermelha de cinco estrelas como bandeira nacional. Foi hasteada pela primeira vez sobre a Praça de Tiananmen em 1 de outubro de 1949, na cerimónia que proclamou a nova república."},
            {"date": "Design", "text": "O design vencedor foi da autoria de Zeng Liansong, um economista e artista amador de Zhejiang, submetido durante um concurso público nacional que reuniu quase 3000 propostas. O seu esboço original incluía um martelo e uma foice dentro da estrela grande; o comité de seleção removeu-os para manter o design simples e distinto dos emblemas de outros estados socialistas."},
            {"date": "2004", "text": "Normas técnicas formais sobre as proporções da bandeira, a geometria das estrelas e as cores foram codificadas em normas nacionais (GB 12982 para a construção, GB 15092 para a cor)."},
        ],
    },
    "data": {
        "title": "Dados Técnicos",
        "ratio": {"title": "Proporções", "text": "Relação entre comprimento e largura da bandeira."},
        "grid": {"title": "Grelha de Construção", "text": "Uma grelha de 30 × 20 unidades. Centro da estrela grande em (5,5), raio externo 3. Estrelas pequenas, raio externo 1, centradas em (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Cores",
            "red": "Vermelho — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Amarelo — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "A norma oficial define as cores através de amostras físicas de referência, não códigos digitais — os valores hexadecimais no ecrã são apenas aproximações.",
        },
        "orientation": {"title": "Regra de Orientação das Estrelas", "text": "Cada estrela pequena é rodada de modo que uma das suas pontas se alinhe exatamente com o centro da estrela grande."},
    },
    "gallery": {
        "title": "Galeria e Uso Quotidiano",
        "intro": "O motivo das cinco estrelas não é só para mastros — aqui é reinventado como objetos do quotidiano, animais populares e locais famosos, todos representados no vermelho e dourado da bandeira.",
        "groups": {"objects": "Objetos do Quotidiano", "animals": "Animais Populares na China", "landmarks": "Monumentos e o Mapa da China"},
        "disclaimer": "Representações ilustrativas criadas para este site — não são produtos oficiais ou licenciados, nem um mapa oficial.",
        "items": {
            "box": {"text": "Um Pacote nas Cores da Bandeira", "slug": "bandeira-chinesa-pacote"},
            "car": {"text": "Um Carro nas Cores da Bandeira", "slug": "bandeira-chinesa-carro"},
            "phone": {"text": "Um Smartphone nas Cores da Bandeira", "slug": "bandeira-chinesa-smartphone"},
            "chest": {"text": "Um Baú do Tesouro nas Cores da Bandeira", "slug": "bandeira-chinesa-bau-do-tesouro"},
            "teapot": {"text": "Um Bule nas Cores da Bandeira", "slug": "bandeira-chinesa-bule"},
            "teacup": {"text": "Uma Xícara de Chá nas Cores da Bandeira", "slug": "bandeira-chinesa-xicara-de-cha"},
            "umbrella": {"text": "Um Guarda-Chuva nas Cores da Bandeira", "slug": "bandeira-chinesa-guarda-chuva"},
            "fan": {"text": "Um Leque nas Cores da Bandeira", "slug": "bandeira-chinesa-leque"},
            "lantern": {"text": "Uma Lanterna nas Cores da Bandeira", "slug": "bandeira-chinesa-lanterna"},
            "bicycle": {"text": "Uma Bicicleta nas Cores da Bandeira", "slug": "bandeira-chinesa-bicicleta"},
            "backpack": {"text": "Uma Mochila nas Cores da Bandeira", "slug": "bandeira-chinesa-mochila"},
            "sneaker": {"text": "Um Tênis nas Cores da Bandeira", "slug": "bandeira-chinesa-tenis"},
            "bird": {"text": "Um Pássaro em Forma de Bandeira", "slug": "bandeira-chinesa-passaro"},
            "dragon": {"text": "Um Dragão em Forma de Bandeira", "slug": "bandeira-chinesa-dragao"},
            "dog": {"text": "Um Cão em Forma de Bandeira", "slug": "bandeira-chinesa-cao"},
            "snake": {"text": "Uma Cobra em Forma de Bandeira", "slug": "bandeira-chinesa-cobra"},
            "panda": {"text": "Um Panda em Forma de Bandeira", "slug": "bandeira-chinesa-panda"},
            "tiger": {"text": "Um Tigre em Forma de Bandeira", "slug": "bandeira-chinesa-tigre"},
            "rabbit": {"text": "Um Coelho em Forma de Bandeira", "slug": "bandeira-chinesa-coelho"},
            "ox": {"text": "Um Boi em Forma de Bandeira", "slug": "bandeira-chinesa-boi"},
            "horse": {"text": "Um Cavalo em Forma de Bandeira", "slug": "bandeira-chinesa-cavalo"},
            "monkey": {"text": "Um Macaco em Forma de Bandeira", "slug": "bandeira-chinesa-macaco"},
            "rooster": {"text": "Um Galo em Forma de Bandeira", "slug": "bandeira-chinesa-galo"},
            "koi": {"text": "Uma Carpa Koi em Forma de Bandeira", "slug": "bandeira-chinesa-carpa-koi"},
            "map": {"text": "O Contorno da China nas Cores da Bandeira", "slug": "bandeira-chinesa-contorno-da-china"},
            "greatwall": {"text": "A Grande Muralha nas Cores da Bandeira", "slug": "bandeira-chinesa-grande-muralha"},
            "forbiddencity": {"text": "A Cidade Proibida nas Cores da Bandeira", "slug": "bandeira-chinesa-cidade-proibida"},
            "templeofheaven": {"text": "O Templo do Céu nas Cores da Bandeira", "slug": "bandeira-chinesa-templo-do-ceu"},
            "terracotta": {"text": "Um Guerreiro de Terracota nas Cores da Bandeira", "slug": "bandeira-chinesa-guerreiro-de-terracota"},
            "pearltower": {"text": "A Torre da Pérola Oriental nas Cores da Bandeira", "slug": "bandeira-chinesa-torre-da-perola-oriental"},
            "potala": {"text": "O Palácio Potala nas Cores da Bandeira", "slug": "bandeira-chinesa-palacio-potala"},
            "guilin": {"text": "As Montanhas Cársicas de Guilin nas Cores da Bandeira", "slug": "bandeira-chinesa-montanhas-carsticas-de-guilin"},
            "pagoda": {"text": "O Pagode do Ganso Selvagem nas Cores da Bandeira", "slug": "bandeira-chinesa-pagode-do-ganso-selvagem"},
        },
    },
    "download": {
        "svg": "Transferir «{name}» em SVG",
        "png": "Transferir «{name}» em PNG",
    },
    "etiquette": {
        "title": "Hasteamento e Etiqueta",
        "text": "A bandeira é hasteada em feriados nacionais, especialmente no Dia Nacional (1 de outubro) e na Golden Week que se segue, bem como durante todo o ano em edifícios governamentais, escolas e postos fronteiriços. Nunca deve tocar o chão, ser hasteada ao contrário ou exibida danificada ou desbotada. Em dias de luto nacional, é hasteada a meia-haste.",
    },
    "footer": {
        "disclaimer": "Este é um site informativo independente e não oficial sobre a bandeira da República Popular da China. Não está afiliado, endossado ou operado em nome de qualquer governo.",
    },
}
