# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Bandera China — Significado, Historia y Datos de la Bandera Roja de Cinco Estrellas",
        "description": "La bandera china explicada: significado de las cinco estrellas, historia de la bandera roja de cinco estrellas, colores y proporciones oficiales, etiqueta de exhibición e ilustraciones temáticas.",
    },
    "brand": "Bandera China",
    "nav": {"meaning": "Significado", "history": "Historia", "data": "Datos Técnicos", "gallery": "Galería", "etiquette": "Etiqueta", "faq": "FAQ"},
    "hero": {
        "flag_alt": "Bandera de la República Popular China — la bandera roja de cinco estrellas",
        "title": "La Bandera Roja de Cinco Estrellas",
        "subtitle": "Bandera nacional de la República Popular China",
        "meta": "Adoptada el 27 de septiembre de 1949 · Proporción 3:2 · Diseñador: Zeng Liansong",
    },
    "meaning": {
        "title": "Significado y Simbolismo",
        "intro": "Adoptado en 1949, el diseño combina color, geometría e historia política en un emblema instantáneamente reconocible.",
        "cards": [
            {"title": "El Campo Rojo", "text": "El rojo representa la revolución y es también el color tradicional de la buena fortuna y la celebración en la cultura china."},
            {"title": "La Estrella Grande", "text": "La gran estrella dorada representa el liderazgo del Partido Comunista de China."},
            {"title": "Las Cuatro Estrellas Pequeñas", "text": "Representan la gran unidad del pueblo chino bajo ese liderazgo — descritas tradicionalmente como la clase obrera, el campesinado, la pequeña burguesía urbana y la burguesía nacional."},
            {"title": "Orientación de las Estrellas", "text": "Cada estrella pequeña tiene una punta dirigida precisamente hacia el centro de la estrella grande, simbolizando la unidad reunida en torno a un centro común."},
            {"title": "Amarillo Dorado", "text": "Elegido para resaltar brillantemente sobre el campo rojo, simbolizando la luz de la revolución iluminando el país."},
        ],
    },
    "history": {
        "title": "Historia y Origen",
        "items": [
            {"date": "1949", "text": "El 27 de septiembre de 1949, días antes de la fundación de la República Popular China, la Conferencia Consultiva Política del Pueblo Chino adoptó formalmente la bandera roja de cinco estrellas como bandera nacional. Se izó por primera vez sobre la plaza de Tian'anmen el 1 de octubre de 1949, en la ceremonia que proclamó la nueva república."},
            {"date": "Diseño", "text": "El diseño ganador fue obra de Zeng Liansong, un economista y artista aficionado de Zhejiang, presentado durante un concurso público a nivel nacional que reunió casi 3000 propuestas. Su boceto original incluía un martillo y una hoz dentro de la estrella grande; el comité de selección los eliminó para mantener el diseño simple y distinto de los emblemas de otros estados socialistas."},
            {"date": "2004", "text": "Las normas técnicas formales sobre las proporciones de la bandera, la geometría de las estrellas y los colores se codificaron en normas nacionales (GB 12982 para la construcción, GB 15092 para el color)."},
        ],
    },
    "data": {
        "title": "Datos Técnicos",
        "ratio": {"title": "Proporciones", "text": "Relación entre longitud y anchura de la bandera."},
        "grid": {"title": "Cuadrícula de Construcción", "text": "Una cuadrícula de 30 × 20 unidades. Centro de la estrella grande en (5,5), radio exterior 3. Estrellas pequeñas, radio exterior 1, centradas en (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Colores",
            "red": "Rojo — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Amarillo — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "El estándar oficial define los colores mediante muestras físicas de referencia, no códigos digitales — los valores hexadecimales en pantalla son solo aproximaciones.",
        },
        "orientation": {"title": "Regla de Orientación de las Estrellas", "text": "Cada estrella pequeña está girada de modo que una de sus puntas se alinea exactamente con el centro de la estrella grande."},
    },
    "gallery": {
        "title": "Galería y Uso Cotidiano",
        "intro": "El motivo de las cinco estrellas no es solo para los mástiles — aquí se reinventa como objetos cotidianos, animales populares y lugares famosos, todos representados en el rojo y dorado propios de la bandera.",
        "groups": {"objects": "Objetos Cotidianos", "animals": "Animales Populares en China", "landmarks": "Monumentos y el Mapa de China"},
        "disclaimer": "Representaciones ilustrativas creadas para este sitio — no son productos oficiales o con licencia, ni un mapa oficial.",
        "items": {
            "box": {"text": "Bandera China con Forma de Paquete", "slug": "bandera-china-paquete"},
            "car": {"text": "Bandera China con Forma de Coche", "slug": "bandera-china-coche"},
            "phone": {"text": "Bandera China con Forma de Smartphone", "slug": "bandera-china-smartphone"},
            "chest": {"text": "Bandera China con Forma de Cofre del Tesoro", "slug": "bandera-china-cofre-del-tesoro"},
            "teapot": {"text": "Bandera China con Forma de Tetera", "slug": "bandera-china-tetera"},
            "teacup": {"text": "Bandera China con Forma de Taza de Té", "slug": "bandera-china-taza-de-te"},
            "umbrella": {"text": "Bandera China con Forma de Paraguas", "slug": "bandera-china-paraguas"},
            "fan": {"text": "Bandera China con Forma de Abanico", "slug": "bandera-china-abanico"},
            "lantern": {"text": "Bandera China con Forma de Farolillo", "slug": "bandera-china-farolillo"},
            "bicycle": {"text": "Bandera China con Forma de Bicicleta", "slug": "bandera-china-bicicleta"},
            "backpack": {"text": "Bandera China con Forma de Mochila", "slug": "bandera-china-mochila"},
            "sneaker": {"text": "Bandera China con Forma de Zapatilla", "slug": "bandera-china-zapatilla"},
            "bird": {"text": "Bandera China con Forma de Pájaro", "slug": "bandera-china-pajaro"},
            "dragon": {"text": "Bandera China con Forma de Dragón", "slug": "bandera-china-dragon"},
            "dog": {"text": "Bandera China con Forma de Perro", "slug": "bandera-china-perro"},
            "snake": {"text": "Bandera China con Forma de Serpiente", "slug": "bandera-china-serpiente"},
            "panda": {"text": "Bandera China con Forma de Panda", "slug": "bandera-china-panda"},
            "tiger": {"text": "Bandera China con Forma de Tigre", "slug": "bandera-china-tigre"},
            "rabbit": {"text": "Bandera China con Forma de Conejo", "slug": "bandera-china-conejo"},
            "ox": {"text": "Bandera China con Forma de Buey", "slug": "bandera-china-buey"},
            "horse": {"text": "Bandera China con Forma de Caballo", "slug": "bandera-china-caballo"},
            "monkey": {"text": "Bandera China con Forma de Mono", "slug": "bandera-china-mono"},
            "rooster": {"text": "Bandera China con Forma de Gallo", "slug": "bandera-china-gallo"},
            "koi": {"text": "Bandera China con Forma de Carpa Koi", "slug": "bandera-china-carpa-koi"},
            "map": {"text": "Bandera China con Forma del Contorno de China", "slug": "bandera-china-contorno-de-china"},
            "greatwall": {"text": "Bandera China con Forma de la Gran Muralla", "slug": "bandera-china-gran-muralla"},
            "forbiddencity": {"text": "Bandera China con Forma de la Ciudad Prohibida", "slug": "bandera-china-ciudad-prohibida"},
            "templeofheaven": {"text": "Bandera China con Forma del Templo del Cielo", "slug": "bandera-china-templo-del-cielo"},
            "terracotta": {"text": "Bandera China con Forma de Guerrero de Terracota", "slug": "bandera-china-guerrero-de-terracota"},
            "pearltower": {"text": "Bandera China con Forma de la Torre de la Perla Oriental", "slug": "bandera-china-torre-de-la-perla-oriental"},
            "potala": {"text": "Bandera China con Forma del Palacio Potala", "slug": "bandera-china-palacio-potala"},
            "guilin": {"text": "Bandera China con Forma de las Montañas Kársticas de Guilin", "slug": "bandera-china-montanas-karsticas-de-guilin"},
            "pagoda": {"text": "Bandera China con Forma de la Pagoda del Ganso Salvaje", "slug": "bandera-china-pagoda-del-ganso-salvaje"},
        },
    },
    "download": {
        "svg": "Descargar «{name}» en SVG",
        "png": "Descargar «{name}» en PNG",
    },
    "faq": {
        "title": "Preguntas Frecuentes",
        "items": [
            {"q": "¿Qué significan las cinco estrellas de la bandera china?",
             "a": "La gran estrella dorada representa el liderazgo del Partido Comunista de China, y las cuatro estrellas menores la gran unidad del pueblo chino. Cada estrella pequeña tiene una punta dirigida exactamente hacia el centro de la estrella grande."},
            {"q": "¿Qué colores tiene la bandera china?",
             "a": "Rojo y amarillo dorado. El campo rojo corresponde al Pantone 186 C (aprox. #DE2910 en pantalla) y las estrellas al Pantone 012 C (aprox. #FFDE00). El rojo simboliza la revolución; el amarillo, la luz que ilumina el país."},
            {"q": "¿Cuándo se adoptó la bandera china?",
             "a": "El 27 de septiembre de 1949. Se izó por primera vez en la plaza de Tiananmén de Pekín el 1 de octubre de 1949, día de la proclamación de la República Popular China."},
            {"q": "¿Quién diseñó la bandera china?",
             "a": "Zeng Liansong, un economista y artista aficionado de la provincia de Zhejiang. Su diseño ganó un concurso nacional con casi 3000 propuestas."},
            {"q": "¿Cuál es la proporción de la bandera china?",
             "a": "3:2 — la bandera es una vez y media más larga que alta."},
            {"q": "¿Puedo descargar gratis las imágenes de la bandera de este sitio?",
             "a": "Sí. Cada ilustración de la galería puede descargarse gratuitamente como archivo vectorial SVG o como imagen PNG."},
        ],
    },
    "etiquette": {
        "title": "Exhibición y Etiqueta",
        "text": "La bandera se iza en los días festivos nacionales, especialmente el Día Nacional (1 de octubre) y la Semana Dorada que le sigue, así como durante todo el año en edificios gubernamentales, escuelas y cruces fronterizos. Nunca debe tocar el suelo, izarse al revés ni mostrarse dañada o descolorida. En los días de duelo nacional, se iza a media asta.",
    },
    "footer": {
        "disclaimer": "Este es un sitio web informativo independiente y no oficial sobre la bandera de la República Popular China. No está afiliado, respaldado ni operado en nombre de ningún gobierno.",
    },
}
