# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Kinas Flagga — Betydelse, Historia och Färger",
        "description": "Kinas flagga förklarad: de fem stjärnornas betydelse, historia, officiella färger och proportioner — plus 33 illustrationer att ladda ner gratis.",
    },
    "brand": "Kinas Flagga",
    "nav": {"meaning": "Betydelse", "history": "Historia", "data": "Teknisk Data", "gallery": "Galleri", "etiquette": "Etikett", "faq": "FAQ", "historic": "Historiska flaggor", "coloring": "Målarbild"},
    "hero": {
        "flag_alt": "Folkrepubliken Kinas flagga — den röda femstjärniga flaggan",
        "title": "Den Röda Femstjärniga Flaggan",
        "subtitle": "Folkrepubliken Kinas nationalflagga",
        "meta": "Antagen 27 september 1949 · Proportion 3:2 · Designer: Zeng Liansong",
    },
    "meaning": {
        "title": "Betydelse och Symbolik",
        "intro": "Designen, antagen 1949, förenar färg, geometri och politisk historia i ett omedelbart igenkännbart emblem.",
        "cards": [
            {"title": "Det Röda Fältet", "text": "Rött står för revolutionen och är också den traditionella färgen för lycka och firande i kinesisk kultur."},
            {"title": "Den Stora Stjärnan", "text": "Den stora gyllene stjärnan representerar Kinas kommunistiska partis ledarskap."},
            {"title": "De Fyra Små Stjärnorna", "text": "De representerar det kinesiska folkets stora enighet under detta ledarskap — traditionellt beskrivna som arbetarklassen, bönderna, den urbana småborgerskapen och den nationella bourgeoisin."},
            {"title": "Stjärnornas Riktning", "text": "Varje liten stjärna har en spets riktad exakt mot den stora stjärnans centrum, vilket symboliserar enighet samlad kring en gemensam medelpunkt."},
            {"title": "Guldgult", "text": "Valt för att lysa strålande mot det röda fältet, en symbol för revolutionens ljus som upplyser landet."},
        ],
    },
    "history": {
        "title": "Historia och Ursprung",
        "items": [
            {"date": "1949", "text": "Den 27 september 1949, några dagar före grundandet av Folkrepubliken Kina, antog Kinesiska folkets politiskt rådgivande konferens formellt den röda femstjärniga flaggan som nationalflagga. Den hissades för första gången över Himmelska fridens torg den 1 oktober 1949, vid ceremonin som proklamerade den nya republiken."},
            {"date": "Design", "text": "Den vinnande designen kom från Zeng Liansong, en ekonom och amatörkonstnär från Zhejiang, som lämnades in under en nationell allmän tävling som samlade nästan 3 000 bidrag. Hans ursprungliga skiss innehöll en hammare och skära inuti den stora stjärnan; urvalskommittén tog bort detta för att hålla designen enkel och skild från andra socialistiska staters emblem."},
            {"date": "2004", "text": "Formella tekniska standarder för flaggans proportioner, stjärngeometri och färger kodifierades i nationella standarder (GB 12982 för konstruktion, GB 15092 för färg)."},
        ],
    },
    "data": {
        "title": "Teknisk Data",
        "ratio": {"title": "Proportioner", "text": "Flaggans längd-till-bredd-förhållande."},
        "grid": {"title": "Konstruktionsraster", "text": "Ett rutnät på 30 × 20 enheter. Den stora stjärnans centrum vid (5,5), ytterradie 3. Små stjärnor, ytterradie 1, centrerade vid (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Färger",
            "red": "Rött — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Gult — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "Den officiella standarden definierar färger med hjälp av fysiska referensprover, inte digitala koder — hexvärden på skärmen är endast ungefärliga.",
        },
        "orientation": {"title": "Stjärnornas Riktningsregel", "text": "Varje liten stjärna är roterad så att en av dess spetsar exakt riktas mot den stora stjärnans centrum."},
    },
    "gallery": {
        "title": "Galleri och Vardagsbruk",
        "intro": "Femstjärnemotivet är inte bara till för flaggstänger — här återges det som vardagsföremål, populära djur och kända sevärdheter, alla i flaggans egna färger rött och guld.",
        "groups": {"objects": "Vardagsföremål", "animals": "Populära Djur i Kina", "landmarks": "Sevärdheter och Kinas Karta"},
        "disclaimer": "Illustrativa bilder skapade för denna sida — inga officiella eller licensierade produkter, och ingen officiell karta.",
        "license": "Bildlicens: Alla flaggillustrationer på den här sidan får laddas ner och användas gratis, även kommersiellt. Källhänvisning (en länk till china-flag.cn) uppskattas men krävs inte.",
        "items": {
            "box": {"text": "Kinesisk Flagga i Form av ett Paket", "slug": "kinesisk-flagga-paket"},
            "car": {"text": "Kinesisk Flagga i Form av en Bil", "slug": "kinesisk-flagga-bil"},
            "phone": {"text": "Kinesisk Flagga i Form av en Mobil", "slug": "kinesisk-flagga-mobil"},
            "chest": {"text": "Kinesisk Flagga i Form av en Skattkista", "slug": "kinesisk-flagga-skattkista"},
            "teapot": {"text": "Kinesisk Flagga i Form av en Tekanna", "slug": "kinesisk-flagga-tekanna"},
            "teacup": {"text": "Kinesisk Flagga i Form av en Tekopp", "slug": "kinesisk-flagga-tekopp"},
            "umbrella": {"text": "Kinesisk Flagga i Form av ett Paraply", "slug": "kinesisk-flagga-paraply"},
            "fan": {"text": "Kinesisk Flagga i Form av en Solfjäder", "slug": "kinesisk-flagga-solfjader"},
            "lantern": {"text": "Kinesisk Flagga i Form av en Lykta", "slug": "kinesisk-flagga-lykta"},
            "bicycle": {"text": "Kinesisk Flagga i Form av en Cykel", "slug": "kinesisk-flagga-cykel"},
            "backpack": {"text": "Kinesisk Flagga i Form av en Ryggsäck", "slug": "kinesisk-flagga-ryggsack"},
            "sneaker": {"text": "Kinesisk Flagga i Form av en Sneaker", "slug": "kinesisk-flagga-sneaker"},
            "bird": {"text": "Kinesisk Flagga i Form av en Fågel", "slug": "kinesisk-flagga-fagel"},
            "dragon": {"text": "Kinesisk Flagga i Form av en Drake", "slug": "kinesisk-flagga-drake"},
            "dog": {"text": "Kinesisk Flagga i Form av en Hund", "slug": "kinesisk-flagga-hund"},
            "snake": {"text": "Kinesisk Flagga i Form av en Orm", "slug": "kinesisk-flagga-orm"},
            "panda": {"text": "Kinesisk Flagga i Form av en Panda", "slug": "kinesisk-flagga-panda"},
            "tiger": {"text": "Kinesisk Flagga i Form av en Tiger", "slug": "kinesisk-flagga-tiger"},
            "rabbit": {"text": "Kinesisk Flagga i Form av en Kanin", "slug": "kinesisk-flagga-kanin"},
            "ox": {"text": "Kinesisk Flagga i Form av en Oxe", "slug": "kinesisk-flagga-oxe"},
            "horse": {"text": "Kinesisk Flagga i Form av en Häst", "slug": "kinesisk-flagga-hast"},
            "monkey": {"text": "Kinesisk Flagga i Form av en Apa", "slug": "kinesisk-flagga-apa"},
            "rooster": {"text": "Kinesisk Flagga i Form av en Tupp", "slug": "kinesisk-flagga-tupp"},
            "koi": {"text": "Kinesisk Flagga i Form av en Koikarp", "slug": "kinesisk-flagga-koikarp"},
            "map": {"text": "Kinesisk Flagga i Form av Kinas Konturer", "slug": "kinesisk-flagga-kinas-konturer"},
            "greatwall": {"text": "Kinesisk Flagga i Form av Kinesiska Muren", "slug": "kinesisk-flagga-kinesiska-muren"},
            "forbiddencity": {"text": "Kinesisk Flagga i Form av Förbjudna Staden", "slug": "kinesisk-flagga-forbjudna-staden"},
            "templeofheaven": {"text": "Kinesisk Flagga i Form av Himmelstemplet", "slug": "kinesisk-flagga-himmelstemplet"},
            "terracotta": {"text": "Kinesisk Flagga i Form av en Terrakottakrigare", "slug": "kinesisk-flagga-terrakottakrigare"},
            "pearltower": {"text": "Kinesisk Flagga i Form av Pearl Tower", "slug": "kinesisk-flagga-pearltower"},
            "potala": {"text": "Kinesisk Flagga i Form av Potalapalatset", "slug": "kinesisk-flagga-potalapalatset"},
            "guilin": {"text": "Kinesisk Flagga i Form av Guilins Karstberg", "slug": "kinesisk-flagga-guilins-karstberg"},
            "pagoda": {"text": "Kinesisk Flagga i Form av Vildgåspagoden", "slug": "kinesisk-flagga-vildgaspagoden"},
        },
    },
    "download": {
        "svg": "Ladda ner {name} som SVG",
        "png": "Ladda ner {name} som PNG",
    },
    "historical": {
        "title": "Kinas historiska flaggor",
        "intro": "Före den röda femstjärniga flaggan vajade helt andra fanor över Kina. Dessa stiliserade illustrationer visar de tre mest kända föregångarna.",
        "items": {
            "qing": {
                "name": "Qingdynastins drakflagga",
                "period": "1889–1912",
                "text": "Den sista kejsardynastin förde en guldgul flagga med en azurblå drake som jagar en röd pärla — gult var kejsarens färg.",
                "alt": "Qingdynastins drakflagga (1889–1912) — stiliserad illustration",
                "slug": "historisk-kinesisk-flagga-qing-drakflagga",
            },
            "fivecolor": {
                "name": "Femfärgsflaggan",
                "period": "1912–1928",
                "text": "Republiken Kinas första flagga: fem ränder för Kinas fem stora folk — han, manchuer, mongoler, hui och tibetaner.",
                "alt": "Republiken Kinas femfärgsflagga (1912–1928)",
                "slug": "historisk-kinesisk-flagga-femfargsflaggan",
            },
            "bluesky": {
                "name": "Blå himmel, vit sol, röd jord",
                "period": "1928–1949",
                "text": "Nationalflaggan under republikens era på fastlandet fram till 1949, med en vit sol med tolv strålar på ett blått fält i övre hörnet.",
                "alt": "Flagga från Republiken Kinas era (1928–1949) med blått hörnfält och vit sol",
                "slug": "historisk-kinesisk-flagga-bla-himmel-vit-sol",
            },
        },
    },
    "coloring": {
        "title": "Målarbild",
        "text": "En utskrivbar kontur av Kinas flagga att färglägga — perfekt för skolan eller en regnig eftermiddag. Tips: den stora stjärnan och de fyra små färgläggs guldgula på rött fält.",
        "caption": "Kinesisk flagga som målarbild",
        "alt": "Målarbild av Kinas flagga — utskrivbar kontur av den röda femstjärniga flaggan",
        "slug": "kinesisk-flagga-malarbild",
    },
    "emoji": {
        "title": "Kinas flagga som emoji",
        "text": "Kinas flagg-emoji 🇨🇳 består av de två regionala indikatorsymbolerna C (U+1F1E8) och N (U+1F1F3). Kopiera den här med ett klick.",
        "copy": "Kopiera emoji",
        "copied": "Kopierad!",
        "note": "På vissa Windows-system visas emojin som bokstäverna ”CN” — på mobiler och de flesta andra enheter visas flaggan.",
    },
    "consent": {
        "text": "Vi vill mäta hur den här webbplatsen används med Google Analytics. Statistikcookies sätts bara om du godkänner det.",
        "accept": "Godkänn",
        "decline": "Avböj",
        "settings": "Cookie-inställningar",
    },
    "faq": {
        "title": "Vanliga Frågor",
        "items": [
            {"q": "Vad betyder de fem stjärnorna på Kinas flagga?",
             "a": "Den stora gyllene stjärnan står för Kinas kommunistiska partis ledarskap, och de fyra mindre stjärnorna för det kinesiska folkets stora enighet. Varje liten stjärna har en spets riktad exakt mot den stora stjärnans centrum."},
            {"q": "Vilka färger har Kinas flagga?",
             "a": "Rött och guldgult. Det röda fältet motsvarar Pantone 186 C (ungefär #DE2910 på skärm) och stjärnorna Pantone 012 C (ungefär #FFDE00). Rött symboliserar revolutionen, gult ljuset som upplyser landet."},
            {"q": "När antogs Kinas flagga?",
             "a": "Den 27 september 1949. Den hissades för första gången på Himmelska fridens torg i Peking den 1 oktober 1949, dagen då Folkrepubliken Kina utropades."},
            {"q": "Vem formgav Kinas flagga?",
             "a": "Zeng Liansong, en ekonom och amatörkonstnär från provinsen Zhejiang. Hans förslag vann en nationell tävling med nästan 3 000 bidrag."},
            {"q": "Vilka proportioner har Kinas flagga?",
             "a": "3:2 — flaggan är en och en halv gång så lång som den är hög."},
            {"q": "Kan jag ladda ner flaggbilderna på den här sidan gratis?",
             "a": "Ja. Varje illustration i galleriet kan laddas ner gratis som SVG-vektorfil eller som PNG-bild."},
        ],
    },
    "etiquette": {
        "title": "Flaggning och Etikett",
        "text": "Flaggan hissas på nationella helgdagar, särskilt nationaldagen (1 oktober) och den efterföljande Gyllene veckan, samt året runt vid myndighetsbyggnader, skolor och gränsövergångar. Den får aldrig vidröra marken, hissas upp och ner eller visas skadad eller blekt. På nationella sorgedagar hissas den på halv stång.",
    },
    "footer": {
        "disclaimer": "Detta är en oberoende, inofficiell informationswebbplats om Folkrepubliken Kinas flagga. Den är inte kopplad till, godkänd av eller driven på uppdrag av någon regering.",
    },
}
