# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Chinesische Flagge — Bedeutung, Geschichte & Farben",
        "description": "Die chinesische Flagge erklärt: Bedeutung der fünf Sterne, Geschichte, offizielle Farben und Proportionen — plus 33 Grafiken als kostenloser Download.",
    },
    "brand": "China Flagge",
    "nav": {"meaning": "Bedeutung", "history": "Geschichte", "data": "Technische Daten", "gallery": "Galerie", "etiquette": "Etikette", "faq": "FAQ"},
    "hero": {
        "flag_alt": "Flagge der Volksrepublik China — die Fünf-Sterne-Rote Flagge",
        "title": "Die Fünf-Sterne-Rote Flagge",
        "subtitle": "Nationalflagge der Volksrepublik China",
        "meta": "Angenommen am 27. September 1949 · Seitenverhältnis 3:2 · Designer: Zeng Liansong",
    },
    "meaning": {
        "title": "Bedeutung & Symbolik",
        "intro": "Das 1949 verabschiedete Design vereint Farbe, Geometrie und politische Geschichte zu einem sofort wiedererkennbaren Emblem.",
        "cards": [
            {"title": "Das Rote Feld", "text": "Rot steht für die Revolution und ist zugleich die traditionelle Farbe für Glück und Freude in der chinesischen Kultur."},
            {"title": "Der Große Stern", "text": "Der große goldene Stern symbolisiert die Führung der Kommunistischen Partei Chinas."},
            {"title": "Die Vier Kleinen Sterne", "text": "Sie stehen für die große Einheit des chinesischen Volkes unter dieser Führung — traditionell beschrieben als Arbeiterklasse, Bauernschaft, städtisches Kleinbürgertum und nationale Bourgeoisie."},
            {"title": "Ausrichtung der Sterne", "text": "Jeder kleine Stern hat eine Spitze, die genau auf die Mitte des großen Sterns zeigt — Symbol für Einheit um einen gemeinsamen Mittelpunkt."},
            {"title": "Goldgelb", "text": "Gewählt, um sich strahlend vom roten Feld abzuheben, als Symbol für das Licht der Revolution, das das Land erhellt."},
        ],
    },
    "history": {
        "title": "Geschichte & Ursprung",
        "items": [
            {"date": "1949", "text": "Am 27. September 1949, wenige Tage vor der Gründung der Volksrepublik China, verabschiedete die Politische Konsultativkonferenz des chinesischen Volkes offiziell die Fünf-Sterne-Rote Flagge als Nationalflagge. Sie wurde am 1. Oktober 1949 bei der Zeremonie zur Ausrufung der neuen Republik erstmals über dem Tian'anmen-Platz gehisst."},
            {"date": "Design", "text": "Der siegreiche Entwurf stammt von Zeng Liansong, einem Ökonomen und Hobbykünstler aus Zhejiang, eingereicht bei einem landesweiten Wettbewerb mit fast 3.000 Einsendungen. Seine ursprüngliche Skizze enthielt Hammer und Sichel im großen Stern; das Auswahlkomitee entfernte dieses Detail, um das Design einfacher zu halten und es von den Emblemen anderer sozialistischer Staaten zu unterscheiden."},
            {"date": "2004", "text": "Formale technische Normen für Proportionen, Sterngeometrie und Farben der Flagge wurden in nationalen Standards festgeschrieben (GB 12982 für die Konstruktion, GB 15092 für die Farbe)."},
        ],
    },
    "data": {
        "title": "Technische Daten",
        "ratio": {"title": "Proportionen", "text": "Verhältnis von Länge zu Höhe der Flagge."},
        "grid": {"title": "Konstruktionsraster", "text": "Ein 30 × 20-Einheiten-Raster. Mittelpunkt des großen Sterns bei (5,5), Außenradius 3. Kleine Sterne mit Außenradius 1, Mittelpunkte bei (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Farben",
            "red": "Rot — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Gelb — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "Der offizielle Standard definiert Farben anhand physischer Referenzmuster, nicht digitaler Codes — Bildschirm-Hexwerte sind nur Annäherungen.",
        },
        "orientation": {"title": "Ausrichtungsregel der Sterne", "text": "Jeder kleine Stern ist so gedreht, dass eine seiner Spitzen exakt auf die Mitte des großen Sterns ausgerichtet ist."},
    },
    "gallery": {
        "title": "Galerie & Alltag",
        "intro": "Das Fünf-Sterne-Motiv ist nicht nur für den Fahnenmast gedacht — hier erscheint es neu interpretiert als Alltagsgegenstände, beliebte Tiere und berühmte Sehenswürdigkeiten, alle in den Farben Rot und Gold der Flagge.",
        "groups": {"objects": "Alltagsgegenstände", "animals": "In China beliebte Tiere", "landmarks": "Wahrzeichen & die Karte Chinas"},
        "disclaimer": "Illustrative Darstellungen für diese Website — keine offiziellen oder lizenzierten Produkte, und keine offizielle Karte.",
        "license": "Bildlizenz: Alle Flaggen-Illustrationen auf dieser Seite dürfen kostenlos heruntergeladen und verwendet werden, auch kommerziell. Eine Quellenangabe (Link auf china-flag.cn) ist willkommen, aber nicht erforderlich.",
        "items": {
            "box": {"text": "Chinesische Flagge als Paket", "slug": "chinesische-flagge-paket"},
            "car": {"text": "Chinesische Flagge als Auto", "slug": "chinesische-flagge-auto"},
            "phone": {"text": "Chinesische Flagge als Smartphone", "slug": "chinesische-flagge-smartphone"},
            "chest": {"text": "Chinesische Flagge als Schatzkiste", "slug": "chinesische-flagge-schatzkiste"},
            "teapot": {"text": "Chinesische Flagge als Teekanne", "slug": "chinesische-flagge-teekanne"},
            "teacup": {"text": "Chinesische Flagge als Teetasse", "slug": "chinesische-flagge-teetasse"},
            "umbrella": {"text": "Chinesische Flagge als Regenschirm", "slug": "chinesische-flagge-regenschirm"},
            "fan": {"text": "Chinesische Flagge als Faltfächer", "slug": "chinesische-flagge-faltfaecher"},
            "lantern": {"text": "Chinesische Flagge als Laterne", "slug": "chinesische-flagge-laterne"},
            "bicycle": {"text": "Chinesische Flagge als Fahrrad", "slug": "chinesische-flagge-fahrrad"},
            "backpack": {"text": "Chinesische Flagge als Rucksack", "slug": "chinesische-flagge-rucksack"},
            "sneaker": {"text": "Chinesische Flagge als Sneaker", "slug": "chinesische-flagge-sneaker"},
            "bird": {"text": "Chinesische Flagge als Vogel", "slug": "chinesische-flagge-vogel"},
            "dragon": {"text": "Chinesische Flagge als Drache", "slug": "chinesische-flagge-drache"},
            "dog": {"text": "Chinesische Flagge als Hund", "slug": "chinesische-flagge-hund"},
            "snake": {"text": "Chinesische Flagge als Schlange", "slug": "chinesische-flagge-schlange"},
            "panda": {"text": "Chinesische Flagge als Panda", "slug": "chinesische-flagge-panda"},
            "tiger": {"text": "Chinesische Flagge als Tiger", "slug": "chinesische-flagge-tiger"},
            "rabbit": {"text": "Chinesische Flagge als Hase", "slug": "chinesische-flagge-hase"},
            "ox": {"text": "Chinesische Flagge als Rind", "slug": "chinesische-flagge-rind"},
            "horse": {"text": "Chinesische Flagge als Pferd", "slug": "chinesische-flagge-pferd"},
            "monkey": {"text": "Chinesische Flagge als Affe", "slug": "chinesische-flagge-affe"},
            "rooster": {"text": "Chinesische Flagge als Hahn", "slug": "chinesische-flagge-hahn"},
            "koi": {"text": "Chinesische Flagge als Koi-Karpfen", "slug": "chinesische-flagge-koi-karpfen"},
            "map": {"text": "Chinesische Flagge als Umriss Chinas", "slug": "chinesische-flagge-china-umriss"},
            "greatwall": {"text": "Chinesische Flagge als Große Mauer", "slug": "chinesische-flagge-grosse-mauer"},
            "forbiddencity": {"text": "Chinesische Flagge als Verbotene Stadt", "slug": "chinesische-flagge-verbotene-stadt"},
            "templeofheaven": {"text": "Chinesische Flagge als Himmelstempel", "slug": "chinesische-flagge-himmelstempel"},
            "terracotta": {"text": "Chinesische Flagge als Terrakotta-Krieger", "slug": "chinesische-flagge-terrakotta-krieger"},
            "pearltower": {"text": "Chinesische Flagge als Oriental Pearl Tower", "slug": "chinesische-flagge-perlturm"},
            "potala": {"text": "Chinesische Flagge als Potala-Palast", "slug": "chinesische-flagge-potala-palast"},
            "guilin": {"text": "Chinesische Flagge als Guilin-Karstberge", "slug": "chinesische-flagge-guilin-karstberge"},
            "pagoda": {"text": "Chinesische Flagge als Große Wildganspagode", "slug": "chinesische-flagge-wildganspagode"},
        },
    },
    "download": {
        "svg": "„{name}“ als SVG herunterladen",
        "png": "„{name}“ als PNG herunterladen",
    },
    "consent": {
        "text": "Wir möchten mit Google Analytics messen, wie diese Seite genutzt wird. Statistik-Cookies werden nur gesetzt, wenn du zustimmst.",
        "accept": "Akzeptieren",
        "decline": "Ablehnen",
        "settings": "Cookie-Einstellungen",
    },
    "faq": {
        "title": "Häufige Fragen",
        "items": [
            {"q": "Was bedeuten die fünf Sterne auf der chinesischen Flagge?",
             "a": "Der große goldene Stern steht für die Führung der Kommunistischen Partei Chinas, die vier kleineren Sterne für die große Einheit des chinesischen Volkes. Jeder kleine Stern zeigt mit einer Spitze genau auf die Mitte des großen Sterns."},
            {"q": "Welche Farben hat die chinesische Flagge?",
             "a": "Rot und Goldgelb. Das rote Feld entspricht Pantone 186 C (am Bildschirm etwa #DE2910), die Sterne Pantone 012 C (etwa #FFDE00). Rot symbolisiert die Revolution, Gelb das Licht, das das Land erhellt."},
            {"q": "Wann wurde die chinesische Flagge eingeführt?",
             "a": "Am 27. September 1949. Erstmals gehisst wurde sie am 1. Oktober 1949 auf dem Tian'anmen-Platz in Peking, dem Tag der Ausrufung der Volksrepublik China."},
            {"q": "Wer hat die chinesische Flagge entworfen?",
             "a": "Zeng Liansong, ein Ökonom und Hobbykünstler aus der Provinz Zhejiang. Sein Entwurf setzte sich in einem landesweiten Wettbewerb mit fast 3.000 Einsendungen durch."},
            {"q": "Welches Seitenverhältnis hat die chinesische Flagge?",
             "a": "3:2 — die Flagge ist anderthalbmal so lang wie hoch."},
            {"q": "Kann ich die Flaggen-Grafiken dieser Seite kostenlos herunterladen?",
             "a": "Ja. Jede Illustration in der Galerie kann kostenlos als SVG-Vektordatei oder als PNG-Bild heruntergeladen werden."},
        ],
    },
    "etiquette": {
        "title": "Beflaggung & Etikette",
        "text": "Die Flagge wird an nationalen Feiertagen gehisst, insbesondere am Nationalfeiertag (1. Oktober) und in der anschließenden Goldenen Woche, sowie ganzjährig an Regierungsgebäuden, Schulen und Grenzübergängen. Sie darf niemals den Boden berühren, verkehrt herum gehisst oder in beschädigtem oder verblasstem Zustand gezeigt werden. An nationalen Trauertagen wird sie auf halbmast gesetzt.",
    },
    "footer": {
        "disclaimer": "Dies ist eine unabhängige, inoffizielle Informationswebsite über die Flagge der Volksrepublik China. Sie steht in keiner Verbindung zu einer Regierung und wird von keiner Regierung unterstützt oder betrieben.",
    },
}
