# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Tutar China — Ma'ana, Tarihi da Launuka",
        "description": "Bayani kan tutar China: ma'anar taurari biyar, tarihi, launuka da gwargwado na hukuma — tare da zane-zane 33 don saukewa kyauta.",
    },
    "brand": "Tutar China",
    "nav": {"meaning": "Ma'ana", "history": "Tarihi", "data": "Bayanan Fasaha", "gallery": "Hotuna", "etiquette": "Ladabi", "faq": "Tambayoyi", "historic": "Tutocin Tarihi", "coloring": "Zanen Launi"},
    "hero": {
        "flag_alt": "Tutar Jamhuriyar Jama'ar China — Jar Tuta mai Taurari Biyar",
        "title": "Jar Tuta mai Taurari Biyar",
        "subtitle": "Tutar ƙasa ta Jamhuriyar Jama'ar China",
        "meta": "An amince da ita a 27 ga Satumba 1949 · Gwargwado 3:2 · Mai zane: Zeng Liansong",
    },
    "meaning": {
        "title": "Ma'ana da Alamomi",
        "intro": "Wannan zane da aka amince da shi a 1949 ya haɗa launi, lissafi da tarihin siyasa cikin alama guda da ake ganewa nan take.",
        "cards": [
            {"title": "Jar Fage", "text": "Ja tana wakiltar juyin juya hali, kuma ita ce launin gargajiya na sa'a da biki a al'adun kasar Sin."},
            {"title": "Babban Tauraro", "text": "Babban tauraron zinariya yana wakiltar jagorancin Jam'iyyar Kwaminis ta China."},
            {"title": "Ƙananan Taurari Huɗu", "text": "Suna wakiltar babbar haɗin kan jama'ar China a ƙarƙashin wannan jagoranci — bisa fassarar gargajiya: ma'aikata, manoma, 'yan kasuwa ƙanana na birni da masu jari na ƙasa."},
            {"title": "Fuskantar Taurari", "text": "Kowane ƙaramin tauraro yana da tsini ɗaya da ke nuni kai tsaye zuwa tsakiyar babban tauraro — alamar haɗin kai da ke kewaye da cibiya guda."},
            {"title": "Rawaya ta Zinariya", "text": "An zaɓe ta don ta yi haske a kan jar fage — alamar hasken juyin juya hali da ke haskaka ƙasa."},
        ],
    },
    "history": {
        "title": "Tarihi da Asali",
        "items": [
            {"date": "1949", "text": "A ranar 27 ga Satumba 1949, kwanaki kaɗan kafin kafuwar Jamhuriyar Jama'ar China, Taron Shawara na Siyasa na Jama'ar China ya amince da Jar Tuta mai Taurari Biyar a matsayin tutar ƙasa a hukumance. An fara ɗaga ta a dandalin Tiananmen a ranar 1 ga Oktoba 1949, a bikin shelanta sabuwar jamhuriya."},
            {"date": "Zane", "text": "Zanen da ya yi nasara na Zeng Liansong ne, masanin tattalin arziki kuma mai zane-zane daga Zhejiang, wanda aka gabatar a gasar ƙasa da ta samu kusan ayyuka 3,000. Zanensa na farko yana da guduma da lauje a cikin babban tauraro; kwamitin zaɓe ya cire su domin zanen ya kasance mai sauƙi kuma ya bambanta da alamomin sauran ƙasashen gurguzu."},
            {"date": "2004", "text": "An rubuta ƙa'idojin fasaha na hukuma game da gwargwadon tuta, lissafin taurari da launuka a cikin ƙa'idojin ƙasa (GB 12982 don gini, GB 15092 don launi)."},
        ],
    },
    "data": {
        "title": "Bayanan Fasaha",
        "ratio": {"title": "Gwargwado", "text": "Gwargwadon tsawon tuta zuwa faɗinta."},
        "grid": {"title": "Grid na Gini", "text": "Grid mai raka'a 30 × 20. Tsakiyar babban tauraro yana (5,5), radius na waje 3. Ƙananan taurari suna da radius na waje 1; tsakiyoyinsu suna (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Launuka",
            "red": "Ja — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Rawaya — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "Ƙa'idar hukuma tana bayyana launuka da samfuran zahiri ba lambobin dijital ba — ƙimar hex a allo ƙiyasi ne kawai.",
        },
        "orientation": {"title": "Ƙa'idar Fuskantar Taurari", "text": "An juya kowane ƙaramin tauraro yadda ɗaya daga cikin tsininsa zai yi daidai da tsakiyar babban tauraro."},
    },
    "gallery": {
        "title": "Hotuna da Amfani na Yau da Kullum",
        "intro": "Alamar taurari biyar ba don sandunan tuta kaɗai ba ce — a nan an sake fasalta ta zuwa kayan yau da kullum, dabbobin da ake so da wurare shahararru, duk cikin ja da zinariya na tutar kanta.",
        "groups": {"objects": "Kayan Yau da Kullum", "animals": "Dabbobin da Suka Shahara a China", "landmarks": "Wurare Shahararru da Taswirar China"},
        "disclaimer": "Zane-zane ne na misali da aka yi wa wannan shafi — ba kayayyakin hukuma ko masu lasisi ba ne, kuma ba taswirar hukuma ba ce.",
        "license": "Lasisin hotuna: Duk zane-zanen tuta a wannan shafi ana iya saukewa da amfani da su kyauta, har da amfanin kasuwanci. Ambaton tushe (hanyar haɗi zuwa china-flag.cn) abin farin ciki ne amma ba dole ba ne.",
        "items": {
            "box": {"text": "Tutar China mai Siffar Fakiti", "slug": "tutar-china-fakiti"},
            "car": {"text": "Tutar China mai Siffar Mota", "slug": "tutar-china-mota"},
            "phone": {"text": "Tutar China mai Siffar Wayar Salula", "slug": "tutar-china-waya"},
            "chest": {"text": "Tutar China mai Siffar Akwatin Dukiya", "slug": "tutar-china-akwatin-dukiya"},
            "teapot": {"text": "Tutar China mai Siffar Bukin Shayi", "slug": "tutar-china-bukin-shayi"},
            "teacup": {"text": "Tutar China mai Siffar Kofin Shayi", "slug": "tutar-china-kofin-shayi"},
            "umbrella": {"text": "Tutar China mai Siffar Laima", "slug": "tutar-china-laima"},
            "fan": {"text": "Tutar China mai Siffar Fanka ta Hannu", "slug": "tutar-china-fanka"},
            "lantern": {"text": "Tutar China mai Siffar Fitila", "slug": "tutar-china-fitila"},
            "bicycle": {"text": "Tutar China mai Siffar Keke", "slug": "tutar-china-keke"},
            "backpack": {"text": "Tutar China mai Siffar Jakar Baya", "slug": "tutar-china-jakar-baya"},
            "sneaker": {"text": "Tutar China mai Siffar Takalmin Wasanni", "slug": "tutar-china-takalmi"},
            "bird": {"text": "Tutar China mai Siffar Tsuntsu", "slug": "tutar-china-tsuntsu"},
            "dragon": {"text": "Tutar China mai Siffar Dodon Wuta", "slug": "tutar-china-dodon-wuta"},
            "dog": {"text": "Tutar China mai Siffar Kare", "slug": "tutar-china-kare"},
            "snake": {"text": "Tutar China mai Siffar Maciji", "slug": "tutar-china-maciji"},
            "panda": {"text": "Tutar China mai Siffar Panda", "slug": "tutar-china-panda"},
            "tiger": {"text": "Tutar China mai Siffar Damisa", "slug": "tutar-china-damisa"},
            "rabbit": {"text": "Tutar China mai Siffar Zomo", "slug": "tutar-china-zomo"},
            "ox": {"text": "Tutar China mai Siffar Sa", "slug": "tutar-china-sa"},
            "horse": {"text": "Tutar China mai Siffar Doki", "slug": "tutar-china-doki"},
            "monkey": {"text": "Tutar China mai Siffar Biri", "slug": "tutar-china-biri"},
            "rooster": {"text": "Tutar China mai Siffar Zakara", "slug": "tutar-china-zakara"},
            "koi": {"text": "Tutar China mai Siffar Kifin Koi", "slug": "tutar-china-kifin-koi"},
            "map": {"text": "Tutar China mai Siffar Taswirar China", "slug": "tutar-china-taswira"},
            "greatwall": {"text": "Tutar China mai Siffar Babbar Ganuwar China", "slug": "tutar-china-babbar-ganuwa"},
            "forbiddencity": {"text": "Tutar China mai Siffar Haramtaccen Birni", "slug": "tutar-china-haramtaccen-birni"},
            "templeofheaven": {"text": "Tutar China mai Siffar Haikalin Sama", "slug": "tutar-china-haikalin-sama"},
            "terracotta": {"text": "Tutar China mai Siffar Sojan Yumbu", "slug": "tutar-china-sojan-yumbu"},
            "pearltower": {"text": "Tutar China mai Siffar Hasumiyar Lu'ulu'u", "slug": "tutar-china-hasumiyar-lulu"},
            "potala": {"text": "Tutar China mai Siffar Fadar Potala", "slug": "tutar-china-fadar-potala"},
            "guilin": {"text": "Tutar China mai Siffar Duwatsun Guilin", "slug": "tutar-china-duwatsun-guilin"},
            "pagoda": {"text": "Tutar China mai Siffar Pagoda ta Agwagwar Daji", "slug": "tutar-china-pagoda"},
        },
    },
    "download": {
        "svg": "Sauke {name} a matsayin SVG",
        "png": "Sauke {name} a matsayin PNG",
    },
    "historical": {
        "title": "Tutocin Tarihi na China",
        "intro": "Kafin Jar Tuta mai Taurari Biyar, tutoci mabambanta ne suka kaɗa a China. Waɗannan zane-zane na salo suna nuna fitattun tutoci uku na baya.",
        "items": {
            "qing": {
                "name": "Tutar Dodon Wuta ta Qing",
                "period": "1889–1912",
                "text": "Daular sarauta ta ƙarshe ta yi amfani da tuta mai launin rawaya ta zinariya, da dodon wuta shuɗi na bin lu'ulu'u ja — rawaya ita ce launin sarki.",
                "alt": "Tutar dodon wuta ta daular Qing (1889–1912) — zanen salo",
                "slug": "tutar-tarihi-china-dodon-qing",
            },
            "fivecolor": {
                "name": "Tuta mai Launuka Biyar",
                "period": "1912–1928",
                "text": "Tutar farko ta Jamhuriyar China: ratsi biyar don manyan al'ummomi biyar na China — Han, Manchu, Mongoliya, Hui da Tibet.",
                "alt": "Tuta mai launuka biyar ta Jamhuriyar China (1912–1928)",
                "slug": "tutar-tarihi-china-launuka-biyar",
            },
            "bluesky": {
                "name": "Sararin Sama Shuɗi, Rana Fara, Ƙasa Ja",
                "period": "1928–1949",
                "text": "Tutar ƙasa ta zamanin jamhuriya a babban yankin har zuwa 1949, mai farin rana da haskoki goma sha biyu a kusurwar shuɗi.",
                "alt": "Tutar zamanin Jamhuriyar China (1928–1949) mai kusurwar shuɗi da farin rana",
                "slug": "tutar-tarihi-china-sararin-sama-shudi",
            },
        },
    },
    "coloring": {
        "title": "Zanen Launi",
        "text": "Zayyanar tutar China da za a iya bugawa don shafa launi — ya dace da makaranta ko yammacin ruwan sama. Shawara: a shafa wa babban tauraro da ƙananan taurari huɗu launin rawaya ta zinariya a kan jar fage.",
        "caption": "Tutar China don Shafa Launi",
        "alt": "Zanen launi na tutar China — zayyanar Jar Tuta mai Taurari Biyar da za a iya bugawa",
        "slug": "tutar-china-zanen-launi",
    },
    "emoji": {
        "title": "Emoji na Tutar China",
        "text": "Emoji na tutar China 🇨🇳 ya ƙunshi alamomin nuni na yanki guda biyu: C (U+1F1E8) da N (U+1F1F3). Kwafa shi a nan da danna sau ɗaya.",
        "copy": "Kwafi emoji",
        "copied": "An kwafa!",
        "note": "A wasu na'urorin Windows emoji yana bayyana a matsayin haruffan “CN” — a wayoyi da yawancin sauran na'urori tutar ce ke bayyana.",
    },
    "consent": {
        "text": "Muna son auna amfani da wannan shafi ta Google Analytics. Ana saka kukis na ƙididdiga ne kawai idan ka amince.",
        "accept": "Amince",
        "decline": "Ƙi",
        "settings": "Saitunan kuki",
    },
    "faq": {
        "title": "Tambayoyin da Ake Yawan Yi",
        "items": [
            {"q": "Menene ma'anar taurari biyar a tutar China?",
             "a": "Babban tauraron zinariya yana wakiltar jagorancin Jam'iyyar Kwaminis ta China, ƙananan taurari huɗu kuma babbar haɗin kan jama'ar China. Kowane ƙaramin tauraro yana da tsini ɗaya da ke nuni kai tsaye zuwa tsakiyar babban tauraro."},
            {"q": "Waɗanne launuka ne tutar China take da su?",
             "a": "Ja da rawaya ta zinariya. Jar fage tana daidai da Pantone 186 C (kimanin #DE2910 a allo), taurari kuma Pantone 012 C (kimanin #FFDE00). Ja tana wakiltar juyin juya hali, rawaya kuma hasken da ke haskaka ƙasa."},
            {"q": "Yaushe aka amince da tutar China?",
             "a": "A ranar 27 ga Satumba 1949. An fara ɗaga ta a dandalin Tiananmen na Beijing a ranar 1 ga Oktoba 1949 — ranar da aka shelanta Jamhuriyar Jama'ar China."},
            {"q": "Wa ya zana tutar China?",
             "a": "Zeng Liansong, masanin tattalin arziki kuma mai zane-zane daga lardin Zhejiang. Zanensa ya yi nasara a gasar ƙasa da ta samu kusan ayyuka 3,000."},
            {"q": "Menene gwargwadon tutar China?",
             "a": "3:2 — tsawon tutar ya ninka tsayinta sau ɗaya da rabi."},
            {"q": "Zan iya sauke hotunan tuta a wannan shafi kyauta?",
             "a": "Eh. Kowane zane a cikin hotunan ana iya saukewa kyauta a matsayin fayil ɗin vector na SVG ko hoton PNG."},
        ],
    },
    "etiquette": {
        "title": "Ɗaga Tuta da Ladabi",
        "text": "Ana ɗaga tutar a ranakun hutu na ƙasa, musamman Ranar Ƙasa (1 ga Oktoba) da Makon Zinariya da ke biye, sannan a duk shekara a gine-ginen gwamnati, makarantu da mashigar kan iyaka. Kada tutar ta taɓa ƙasa, kada a ɗaga ta a juye, kuma kada a nuna ta cikin yagaggu ko koɗaɗɗen yanayi. A ranakun makoki na ƙasa ana ɗaga ta rabin sanda.",
    },
    "footer": {
        "disclaimer": "Wannan shafi ne mai zaman kansa, ba na hukuma ba, mai bayani kan tutar Jamhuriyar Jama'ar China. Ba shi da alaƙa da wata gwamnati, ba wata gwamnati ce ta amince da shi ba, kuma ba a gudanar da shi a madadin wata gwamnati.",
    },
}
