# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Bandiera Cinese — Significato, Storia e Curiosità sulla Bandiera Rossa a Cinque Stelle",
        "description": "La bandiera cinese spiegata: significato delle cinque stelle, storia della bandiera rossa a cinque stelle, colori e proporzioni ufficiali, galateo di esposizione e illustrazioni a tema.",
    },
    "brand": "Bandiera Cinese",
    "nav": {"meaning": "Significato", "history": "Storia", "data": "Dati Tecnici", "gallery": "Galleria", "etiquette": "Galateo"},
    "hero": {
        "flag_alt": "Bandiera della Repubblica Popolare Cinese — la bandiera rossa a cinque stelle",
        "title": "La Bandiera Rossa a Cinque Stelle",
        "subtitle": "Bandiera nazionale della Repubblica Popolare Cinese",
        "meta": "Adottata il 27 settembre 1949 · Proporzioni 3:2 · Designer: Zeng Liansong",
    },
    "meaning": {
        "title": "Significato e Simbolismo",
        "intro": "Adottato nel 1949, il design unisce colore, geometria e storia politica in un emblema immediatamente riconoscibile.",
        "cards": [
            {"title": "Il Campo Rosso", "text": "Il rosso rappresenta la rivoluzione ed è anche il colore tradizionale della buona fortuna e della festa nella cultura cinese."},
            {"title": "La Stella Grande", "text": "La grande stella dorata rappresenta la guida del Partito Comunista Cinese."},
            {"title": "Le Quattro Stelle Piccole", "text": "Rappresentano la grande unità del popolo cinese sotto quella guida — tradizionalmente descritte come la classe operaia, i contadini, la piccola borghesia urbana e la borghesia nazionale."},
            {"title": "Orientamento delle Stelle", "text": "Ogni stella piccola ha una punta rivolta precisamente verso il centro della stella grande, simboleggiando l'unità raccolta attorno a un centro comune."},
            {"title": "Giallo Dorato", "text": "Scelto per risaltare brillantemente sul campo rosso, simboleggiando la luce della rivoluzione che illumina il paese."},
        ],
    },
    "history": {
        "title": "Storia e Origine",
        "items": [
            {"date": "1949", "text": "Il 27 settembre 1949, pochi giorni prima della fondazione della Repubblica Popolare Cinese, la Conferenza Consultiva Politica del Popolo Cinese adottò formalmente la bandiera rossa a cinque stelle come bandiera nazionale. Fu issata per la prima volta su piazza Tienanmen il 1° ottobre 1949, durante la cerimonia che proclamava la nuova repubblica."},
            {"date": "Design", "text": "Il design vincitore fu opera di Zeng Liansong, un economista e artista dilettante dello Zhejiang, presentato durante un concorso pubblico nazionale che raccolse quasi 3.000 proposte. Il suo schizzo originale includeva falce e martello all'interno della stella grande; il comitato di selezione li rimosse per mantenere il design semplice e distinto dagli emblemi di altri stati socialisti."},
            {"date": "2004", "text": "Norme tecniche formali sulle proporzioni della bandiera, la geometria delle stelle e i colori furono codificate in standard nazionali (GB 12982 per la costruzione, GB 15092 per il colore)."},
        ],
    },
    "data": {
        "title": "Dati Tecnici",
        "ratio": {"title": "Proporzioni", "text": "Rapporto tra lunghezza e altezza della bandiera."},
        "grid": {"title": "Griglia di Costruzione", "text": "Una griglia di 30 × 20 unità. Centro della stella grande in (5,5), raggio esterno 3. Stelle piccole, raggio esterno 1, centrate in (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Colori",
            "red": "Rosso — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Giallo — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "Lo standard ufficiale definisce i colori tramite campioni fisici di riferimento, non codici digitali — i valori esadecimali a schermo sono solo approssimazioni.",
        },
        "orientation": {"title": "Regola di Orientamento delle Stelle", "text": "Ogni stella piccola è ruotata in modo che una delle sue punte si allinei esattamente con il centro della stella grande."},
    },
    "gallery": {
        "title": "Galleria e Uso Quotidiano",
        "intro": "Il motivo delle cinque stelle non è solo per i pennoni — qui viene reinterpretato come oggetti quotidiani, animali amati e luoghi famosi, tutti resi nel rosso e oro propri della bandiera.",
        "groups": {"objects": "Oggetti Quotidiani", "animals": "Animali Popolari in Cina", "landmarks": "Monumenti e la Mappa della Cina"},
        "disclaimer": "Rappresentazioni illustrative create per questo sito — non sono prodotti ufficiali o su licenza, né una mappa ufficiale.",
        "items": {
            "box": {"text": "Un Pacco nei Colori della Bandiera", "slug": "bandiera-cinese-pacco"},
            "car": {"text": "Un'Auto nei Colori della Bandiera", "slug": "bandiera-cinese-auto"},
            "phone": {"text": "Uno Smartphone nei Colori della Bandiera", "slug": "bandiera-cinese-smartphone"},
            "chest": {"text": "Un Forziere nei Colori della Bandiera", "slug": "bandiera-cinese-forziere"},
            "teapot": {"text": "Una Teiera nei Colori della Bandiera", "slug": "bandiera-cinese-teiera"},
            "teacup": {"text": "Una Tazza da Tè nei Colori della Bandiera", "slug": "bandiera-cinese-tazza-da-te"},
            "umbrella": {"text": "Un Ombrello nei Colori della Bandiera", "slug": "bandiera-cinese-ombrello"},
            "fan": {"text": "Un Ventaglio nei Colori della Bandiera", "slug": "bandiera-cinese-ventaglio"},
            "lantern": {"text": "Una Lanterna nei Colori della Bandiera", "slug": "bandiera-cinese-lanterna"},
            "bicycle": {"text": "Una Bicicletta nei Colori della Bandiera", "slug": "bandiera-cinese-bicicletta"},
            "backpack": {"text": "Uno Zaino nei Colori della Bandiera", "slug": "bandiera-cinese-zaino"},
            "sneaker": {"text": "Una Sneaker nei Colori della Bandiera", "slug": "bandiera-cinese-sneaker"},
            "bird": {"text": "Un Uccello a Forma di Bandiera", "slug": "bandiera-cinese-uccello"},
            "dragon": {"text": "Un Drago a Forma di Bandiera", "slug": "bandiera-cinese-drago"},
            "dog": {"text": "Un Cane a Forma di Bandiera", "slug": "bandiera-cinese-cane"},
            "snake": {"text": "Un Serpente a Forma di Bandiera", "slug": "bandiera-cinese-serpente"},
            "panda": {"text": "Un Panda a Forma di Bandiera", "slug": "bandiera-cinese-panda"},
            "tiger": {"text": "Una Tigre a Forma di Bandiera", "slug": "bandiera-cinese-tigre"},
            "rabbit": {"text": "Un Coniglio a Forma di Bandiera", "slug": "bandiera-cinese-coniglio"},
            "ox": {"text": "Un Bue a Forma di Bandiera", "slug": "bandiera-cinese-bue"},
            "horse": {"text": "Un Cavallo a Forma di Bandiera", "slug": "bandiera-cinese-cavallo"},
            "monkey": {"text": "Una Scimmia a Forma di Bandiera", "slug": "bandiera-cinese-scimmia"},
            "rooster": {"text": "Un Gallo a Forma di Bandiera", "slug": "bandiera-cinese-gallo"},
            "koi": {"text": "Una Carpa Koi a Forma di Bandiera", "slug": "bandiera-cinese-carpa-koi"},
            "map": {"text": "Il Contorno della Cina nei Colori della Bandiera", "slug": "bandiera-cinese-contorno-della-cina"},
            "greatwall": {"text": "La Grande Muraglia nei Colori della Bandiera", "slug": "bandiera-cinese-grande-muraglia"},
            "forbiddencity": {"text": "La Città Proibita nei Colori della Bandiera", "slug": "bandiera-cinese-citta-proibita"},
            "templeofheaven": {"text": "Il Tempio del Cielo nei Colori della Bandiera", "slug": "bandiera-cinese-tempio-del-cielo"},
            "terracotta": {"text": "Un Guerriero di Terracotta nei Colori della Bandiera", "slug": "bandiera-cinese-guerriero-di-terracotta"},
            "pearltower": {"text": "La Torre della Perla Orientale nei Colori della Bandiera", "slug": "bandiera-cinese-torre-della-perla-orientale"},
            "potala": {"text": "Il Palazzo del Potala nei Colori della Bandiera", "slug": "bandiera-cinese-palazzo-del-potala"},
            "guilin": {"text": "Le Montagne Carsiche di Guilin nei Colori della Bandiera", "slug": "bandiera-cinese-montagne-carsiche-di-guilin"},
            "pagoda": {"text": "La Pagoda dell'Oca Selvatica nei Colori della Bandiera", "slug": "bandiera-cinese-pagoda-dell-oca-selvatica"},
        },
    },
    "download": {
        "svg": "Scarica «{name}» in SVG",
        "png": "Scarica «{name}» in PNG",
    },
    "etiquette": {
        "title": "Esposizione e Galateo",
        "text": "La bandiera viene issata nelle festività nazionali, in particolare la Festa Nazionale (1° ottobre) e la successiva Golden Week, oltre che tutto l'anno su edifici governativi, scuole e valichi di frontiera. Non deve mai toccare il suolo, essere issata capovolta o mostrata danneggiata o sbiadita. Nei giorni di lutto nazionale viene esposta a mezz'asta.",
    },
    "footer": {
        "disclaimer": "Questo è un sito web informativo indipendente e non ufficiale sulla bandiera della Repubblica Popolare Cinese. Non è affiliato, sostenuto o gestito per conto di alcun governo.",
    },
}
