# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Bandeira Chinesa — Significado, História e Cores",
        "description": "A bandeira chinesa explicada: significado das cinco estrelas, história, cores e proporções oficiais, e 33 ilustrações para descarregar grátis.",
    },
    "brand": "Bandeira Chinesa",
    "nav": {"meaning": "Significado", "history": "História", "data": "Dados Técnicos", "gallery": "Galeria", "etiquette": "Etiqueta", "faq": "FAQ"},
    "hero": {
        "flag_alt": "Bandeira da República Popular da China — a bandeira vermelha de cinco estrelas",
        "title": "A Bandeira Vermelha de Cinco Estrelas",
        "subtitle": "Bandeira nacional da República Popular da China",
        "meta": "Adotada em 27 de setembro de 1949 · Proporção 3:2 · Designer: Zeng Liansong",
    },
    "meaning": {
        "title": "Significado e Simbolismo",
        "intro": "Adotado em 1949, o design combina cor, geometria e história política num emblema instantaneamente reconhecível.",
        "cards": [
            {"title": "O Campo Vermelho", "text": "O vermelho representa a revolução e é também a cor tradicional da boa sorte e da celebração na cultura chinesa."},
            {"title": "A Estrela Grande", "text": "A grande estrela dourada representa a liderança do Partido Comunista da China."},
            {"title": "As Quatro Estrelas Pequenas", "text": "Representam a grande unidade do povo chinês sob essa liderança — tradicionalmente descritas como a classe operária, o campesinato, a pequena burguesia urbana e a burguesia nacional."},
            {"title": "Orientação das Estrelas", "text": "Cada estrela pequena tem uma ponta apontada precisamente para o centro da estrela grande, simbolizando a união reunida em torno de um centro comum."},
            {"title": "Amarelo Dourado", "text": "Escolhido para se destacar de forma brilhante sobre o campo vermelho, simbolizando a luz da revolução a iluminar o país."},
        ],
    },
    "history": {
        "title": "História e Origem",
        "items": [
            {"date": "1949", "text": "Em 27 de setembro de 1949, dias antes da fundação da República Popular da China, a Conferência Consultiva Política do Povo Chinês adotou formalmente a bandeira vermelha de cinco estrelas como bandeira nacional. Foi hasteada pela primeira vez sobre a Praça de Tiananmen em 1 de outubro de 1949, na cerimónia que proclamou a nova república."},
            {"date": "Design", "text": "O design vencedor foi da autoria de Zeng Liansong, um economista e artista amador de Zhejiang, submetido durante um concurso público nacional que reuniu quase 3000 propostas. O seu esboço original incluía um martelo e uma foice dentro da estrela grande; o comité de seleção removeu-os para manter o design simples e distinto dos emblemas de outros estados socialistas."},
            {"date": "2004", "text": "Normas técnicas formais sobre as proporções da bandeira, a geometria das estrelas e as cores foram codificadas em normas nacionais (GB 12982 para a construção, GB 15092 para a cor)."},
        ],
    },
    "data": {
        "title": "Dados Técnicos",
        "ratio": {"title": "Proporções", "text": "Relação entre comprimento e largura da bandeira."},
        "grid": {"title": "Grelha de Construção", "text": "Uma grelha de 30 × 20 unidades. Centro da estrela grande em (5,5), raio externo 3. Estrelas pequenas, raio externo 1, centradas em (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Cores",
            "red": "Vermelho — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Amarelo — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "A norma oficial define as cores através de amostras físicas de referência, não códigos digitais — os valores hexadecimais no ecrã são apenas aproximações.",
        },
        "orientation": {"title": "Regra de Orientação das Estrelas", "text": "Cada estrela pequena é rodada de modo que uma das suas pontas se alinhe exatamente com o centro da estrela grande."},
    },
    "gallery": {
        "title": "Galeria e Uso Quotidiano",
        "intro": "O motivo das cinco estrelas não é só para mastros — aqui é reinventado como objetos do quotidiano, animais populares e locais famosos, todos representados no vermelho e dourado da bandeira.",
        "groups": {"objects": "Objetos do Quotidiano", "animals": "Animais Populares na China", "landmarks": "Monumentos e o Mapa da China"},
        "disclaimer": "Representações ilustrativas criadas para este site — não são produtos oficiais ou licenciados, nem um mapa oficial.",
        "license": "Licença das imagens: todas as ilustrações de bandeiras desta página podem ser descarregadas e utilizadas gratuitamente, inclusive para fins comerciais. A atribuição (um link para china-flag.cn) é apreciada, mas não obrigatória.",
        "items": {
            "box": {"text": "Bandeira Chinesa em Forma de Pacote", "slug": "bandeira-chinesa-pacote"},
            "car": {"text": "Bandeira Chinesa em Forma de Carro", "slug": "bandeira-chinesa-carro"},
            "phone": {"text": "Bandeira Chinesa em Forma de Smartphone", "slug": "bandeira-chinesa-smartphone"},
            "chest": {"text": "Bandeira Chinesa em Forma de Baú do Tesouro", "slug": "bandeira-chinesa-bau-do-tesouro"},
            "teapot": {"text": "Bandeira Chinesa em Forma de Bule", "slug": "bandeira-chinesa-bule"},
            "teacup": {"text": "Bandeira Chinesa em Forma de Xícara de Chá", "slug": "bandeira-chinesa-xicara-de-cha"},
            "umbrella": {"text": "Bandeira Chinesa em Forma de Guarda-Chuva", "slug": "bandeira-chinesa-guarda-chuva"},
            "fan": {"text": "Bandeira Chinesa em Forma de Leque", "slug": "bandeira-chinesa-leque"},
            "lantern": {"text": "Bandeira Chinesa em Forma de Lanterna", "slug": "bandeira-chinesa-lanterna"},
            "bicycle": {"text": "Bandeira Chinesa em Forma de Bicicleta", "slug": "bandeira-chinesa-bicicleta"},
            "backpack": {"text": "Bandeira Chinesa em Forma de Mochila", "slug": "bandeira-chinesa-mochila"},
            "sneaker": {"text": "Bandeira Chinesa em Forma de Tênis", "slug": "bandeira-chinesa-tenis"},
            "bird": {"text": "Bandeira Chinesa em Forma de Pássaro", "slug": "bandeira-chinesa-passaro"},
            "dragon": {"text": "Bandeira Chinesa em Forma de Dragão", "slug": "bandeira-chinesa-dragao"},
            "dog": {"text": "Bandeira Chinesa em Forma de Cão", "slug": "bandeira-chinesa-cao"},
            "snake": {"text": "Bandeira Chinesa em Forma de Cobra", "slug": "bandeira-chinesa-cobra"},
            "panda": {"text": "Bandeira Chinesa em Forma de Panda", "slug": "bandeira-chinesa-panda"},
            "tiger": {"text": "Bandeira Chinesa em Forma de Tigre", "slug": "bandeira-chinesa-tigre"},
            "rabbit": {"text": "Bandeira Chinesa em Forma de Coelho", "slug": "bandeira-chinesa-coelho"},
            "ox": {"text": "Bandeira Chinesa em Forma de Boi", "slug": "bandeira-chinesa-boi"},
            "horse": {"text": "Bandeira Chinesa em Forma de Cavalo", "slug": "bandeira-chinesa-cavalo"},
            "monkey": {"text": "Bandeira Chinesa em Forma de Macaco", "slug": "bandeira-chinesa-macaco"},
            "rooster": {"text": "Bandeira Chinesa em Forma de Galo", "slug": "bandeira-chinesa-galo"},
            "koi": {"text": "Bandeira Chinesa em Forma de Carpa Koi", "slug": "bandeira-chinesa-carpa-koi"},
            "map": {"text": "Bandeira Chinesa em Forma do Contorno da China", "slug": "bandeira-chinesa-contorno-da-china"},
            "greatwall": {"text": "Bandeira Chinesa em Forma da Grande Muralha", "slug": "bandeira-chinesa-grande-muralha"},
            "forbiddencity": {"text": "Bandeira Chinesa em Forma da Cidade Proibida", "slug": "bandeira-chinesa-cidade-proibida"},
            "templeofheaven": {"text": "Bandeira Chinesa em Forma do Templo do Céu", "slug": "bandeira-chinesa-templo-do-ceu"},
            "terracotta": {"text": "Bandeira Chinesa em Forma de Guerreiro de Terracota", "slug": "bandeira-chinesa-guerreiro-de-terracota"},
            "pearltower": {"text": "Bandeira Chinesa em Forma da Torre da Pérola Oriental", "slug": "bandeira-chinesa-torre-da-perola-oriental"},
            "potala": {"text": "Bandeira Chinesa em Forma do Palácio Potala", "slug": "bandeira-chinesa-palacio-potala"},
            "guilin": {"text": "Bandeira Chinesa em Forma das Montanhas Cársicas de Guilin", "slug": "bandeira-chinesa-montanhas-carsticas-de-guilin"},
            "pagoda": {"text": "Bandeira Chinesa em Forma do Pagode do Ganso Selvagem", "slug": "bandeira-chinesa-pagode-do-ganso-selvagem"},
        },
    },
    "download": {
        "svg": "Transferir «{name}» em SVG",
        "png": "Transferir «{name}» em PNG",
    },
    "consent": {
        "text": "Gostaríamos de medir a utilização deste site com o Google Analytics. Os cookies estatísticos só são definidos com o seu consentimento.",
        "accept": "Aceitar",
        "decline": "Recusar",
        "settings": "Definições de cookies",
    },
    "faq": {
        "title": "Perguntas Frequentes",
        "items": [
            {"q": "O que significam as cinco estrelas da bandeira chinesa?",
             "a": "A grande estrela dourada representa a liderança do Partido Comunista da China, e as quatro estrelas menores a grande unidade do povo chinês. Cada estrela pequena tem uma ponta apontada exatamente para o centro da estrela grande."},
            {"q": "Quais são as cores da bandeira chinesa?",
             "a": "Vermelho e amarelo dourado. O campo vermelho corresponde ao Pantone 186 C (aprox. #DE2910 no ecrã) e as estrelas ao Pantone 012 C (aprox. #FFDE00). O vermelho simboliza a revolução; o amarelo, a luz que ilumina o país."},
            {"q": "Quando foi adotada a bandeira chinesa?",
             "a": "Em 27 de setembro de 1949. Foi hasteada pela primeira vez na Praça de Tiananmen, em Pequim, em 1 de outubro de 1949, dia da proclamação da República Popular da China."},
            {"q": "Quem desenhou a bandeira chinesa?",
             "a": "Zeng Liansong, economista e artista amador da província de Zhejiang. O seu projeto venceu um concurso nacional com quase 3000 propostas."},
            {"q": "Qual é a proporção da bandeira chinesa?",
             "a": "3:2 — a bandeira é uma vez e meia mais comprida do que alta."},
            {"q": "Posso descarregar gratuitamente as imagens da bandeira deste site?",
             "a": "Sim. Cada ilustração da galeria pode ser descarregada gratuitamente como ficheiro vetorial SVG ou como imagem PNG."},
        ],
    },
    "etiquette": {
        "title": "Hasteamento e Etiqueta",
        "text": "A bandeira é hasteada em feriados nacionais, especialmente no Dia Nacional (1 de outubro) e na Golden Week que se segue, bem como durante todo o ano em edifícios governamentais, escolas e postos fronteiriços. Nunca deve tocar o chão, ser hasteada ao contrário ou exibida danificada ou desbotada. Em dias de luto nacional, é hasteada a meia-haste.",
    },
    "footer": {
        "disclaimer": "Este é um site informativo independente e não oficial sobre a bandeira da República Popular da China. Não está afiliado, endossado ou operado em nome de qualquer governo.",
    },
}
