# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Chinesische Flagge — Bedeutung, Geschichte & Fakten zur Fünf-Sterne-Flagge",
        "description": "Die chinesische Flagge erklärt: Bedeutung der fünf Sterne, Geschichte der Fünf-Sterne-Roten Flagge, offizielle Farben & Proportionen, Beflaggungsregeln und thematische Illustrationen.",
    },
    "brand": "China Flagge",
    "nav": {"meaning": "Bedeutung", "history": "Geschichte", "data": "Technische Daten", "gallery": "Galerie", "etiquette": "Etikette"},
    "hero": {
        "flag_alt": "Flagge der Volksrepublik China — die Fünf-Sterne-Rote Flagge",
        "title": "Die Fünf-Sterne-Rote Flagge",
        "subtitle": "Nationalflagge der Volksrepublik China",
        "meta": "Angenommen am 27. September 1949 · Seitenverhältnis 3:2 · Designer: Zeng Liansong",
    },
    "meaning": {
        "title": "Bedeutung & Symbolik",
        "intro": "Das 1949 verabschiedete Design vereint Farbe, Geometrie und politische Geschichte zu einem sofort wiedererkennbaren Emblem.",
        "cards": [
            {"title": "Das Rote Feld", "text": "Rot steht für die Revolution und ist zugleich die traditionelle Farbe für Glück und Freude in der chinesischen Kultur."},
            {"title": "Der Große Stern", "text": "Der große goldene Stern symbolisiert die Führung der Kommunistischen Partei Chinas."},
            {"title": "Die Vier Kleinen Sterne", "text": "Sie stehen für die große Einheit des chinesischen Volkes unter dieser Führung — traditionell beschrieben als Arbeiterklasse, Bauernschaft, städtisches Kleinbürgertum und nationale Bourgeoisie."},
            {"title": "Ausrichtung der Sterne", "text": "Jeder kleine Stern hat eine Spitze, die genau auf die Mitte des großen Sterns zeigt — Symbol für Einheit um einen gemeinsamen Mittelpunkt."},
            {"title": "Goldgelb", "text": "Gewählt, um sich strahlend vom roten Feld abzuheben, als Symbol für das Licht der Revolution, das das Land erhellt."},
        ],
    },
    "history": {
        "title": "Geschichte & Ursprung",
        "items": [
            {"date": "1949", "text": "Am 27. September 1949, wenige Tage vor der Gründung der Volksrepublik China, verabschiedete die Politische Konsultativkonferenz des chinesischen Volkes offiziell die Fünf-Sterne-Rote Flagge als Nationalflagge. Sie wurde am 1. Oktober 1949 bei der Zeremonie zur Ausrufung der neuen Republik erstmals über dem Tian'anmen-Platz gehisst."},
            {"date": "Design", "text": "Der siegreiche Entwurf stammt von Zeng Liansong, einem Ökonomen und Hobbykünstler aus Zhejiang, eingereicht bei einem landesweiten Wettbewerb mit fast 3.000 Einsendungen. Seine ursprüngliche Skizze enthielt Hammer und Sichel im großen Stern; das Auswahlkomitee entfernte dieses Detail, um das Design einfacher zu halten und es von den Emblemen anderer sozialistischer Staaten zu unterscheiden."},
            {"date": "2004", "text": "Formale technische Normen für Proportionen, Sterngeometrie und Farben der Flagge wurden in nationalen Standards festgeschrieben (GB 12982 für die Konstruktion, GB 15092 für die Farbe)."},
        ],
    },
    "data": {
        "title": "Technische Daten",
        "ratio": {"title": "Proportionen", "text": "Verhältnis von Länge zu Höhe der Flagge."},
        "grid": {"title": "Konstruktionsraster", "text": "Ein 30 × 20-Einheiten-Raster. Mittelpunkt des großen Sterns bei (5,5), Außenradius 3. Kleine Sterne mit Außenradius 1, Mittelpunkte bei (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Farben",
            "red": "Rot — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Gelb — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "Der offizielle Standard definiert Farben anhand physischer Referenzmuster, nicht digitaler Codes — Bildschirm-Hexwerte sind nur Annäherungen.",
        },
        "orientation": {"title": "Ausrichtungsregel der Sterne", "text": "Jeder kleine Stern ist so gedreht, dass eine seiner Spitzen exakt auf die Mitte des großen Sterns ausgerichtet ist."},
    },
    "gallery": {
        "title": "Galerie & Alltag",
        "intro": "Das Fünf-Sterne-Motiv ist nicht nur für den Fahnenmast gedacht — hier erscheint es neu interpretiert als Alltagsgegenstände, beliebte Tiere und berühmte Sehenswürdigkeiten, alle in den Farben Rot und Gold der Flagge.",
        "groups": {"objects": "Alltagsgegenstände", "animals": "In China beliebte Tiere", "landmarks": "Wahrzeichen & die Karte Chinas"},
        "disclaimer": "Illustrative Darstellungen für diese Website — keine offiziellen oder lizenzierten Produkte, und keine offizielle Karte.",
        "items": {
            "box": {"text": "Ein Paket in Flaggenfarben", "slug": "chinesische-flagge-paket"},
            "car": {"text": "Ein Auto in Flaggenfarben", "slug": "chinesische-flagge-auto"},
            "phone": {"text": "Ein Smartphone in Flaggenfarben", "slug": "chinesische-flagge-smartphone"},
            "chest": {"text": "Eine Schatzkiste in Flaggenfarben", "slug": "chinesische-flagge-schatzkiste"},
            "teapot": {"text": "Eine Teekanne in Flaggenfarben", "slug": "chinesische-flagge-teekanne"},
            "teacup": {"text": "Eine Teetasse in Flaggenfarben", "slug": "chinesische-flagge-teetasse"},
            "umbrella": {"text": "Ein Regenschirm in Flaggenfarben", "slug": "chinesische-flagge-regenschirm"},
            "fan": {"text": "Ein Faltfächer in Flaggenfarben", "slug": "chinesische-flagge-faltfaecher"},
            "lantern": {"text": "Eine Laterne in Flaggenfarben", "slug": "chinesische-flagge-laterne"},
            "bicycle": {"text": "Ein Fahrrad in Flaggenfarben", "slug": "chinesische-flagge-fahrrad"},
            "backpack": {"text": "Ein Rucksack in Flaggenfarben", "slug": "chinesische-flagge-rucksack"},
            "sneaker": {"text": "Ein Sneaker in Flaggenfarben", "slug": "chinesische-flagge-sneaker"},
            "bird": {"text": "Ein Vogel in Flaggenform", "slug": "chinesische-flagge-vogel"},
            "dragon": {"text": "Ein Drache in Flaggenform", "slug": "chinesische-flagge-drache"},
            "dog": {"text": "Ein Hund in Flaggenform", "slug": "chinesische-flagge-hund"},
            "snake": {"text": "Eine Schlange in Flaggenform", "slug": "chinesische-flagge-schlange"},
            "panda": {"text": "Ein Panda in Flaggenform", "slug": "chinesische-flagge-panda"},
            "tiger": {"text": "Ein Tiger in Flaggenform", "slug": "chinesische-flagge-tiger"},
            "rabbit": {"text": "Ein Hase in Flaggenform", "slug": "chinesische-flagge-hase"},
            "ox": {"text": "Ein Rind in Flaggenform", "slug": "chinesische-flagge-rind"},
            "horse": {"text": "Ein Pferd in Flaggenform", "slug": "chinesische-flagge-pferd"},
            "monkey": {"text": "Ein Affe in Flaggenform", "slug": "chinesische-flagge-affe"},
            "rooster": {"text": "Ein Hahn in Flaggenform", "slug": "chinesische-flagge-hahn"},
            "koi": {"text": "Ein Koi-Karpfen in Flaggenform", "slug": "chinesische-flagge-koi-karpfen"},
            "map": {"text": "Der Umriss Chinas in Flaggenfarben", "slug": "chinesische-flagge-china-umriss"},
            "greatwall": {"text": "Die Große Mauer in Flaggenfarben", "slug": "chinesische-flagge-grosse-mauer"},
            "forbiddencity": {"text": "Die Verbotene Stadt in Flaggenfarben", "slug": "chinesische-flagge-verbotene-stadt"},
            "templeofheaven": {"text": "Der Himmelstempel in Flaggenfarben", "slug": "chinesische-flagge-himmelstempel"},
            "terracotta": {"text": "Ein Terrakotta-Krieger in Flaggenfarben", "slug": "chinesische-flagge-terrakotta-krieger"},
            "pearltower": {"text": "Der Oriental Pearl Tower in Flaggenfarben", "slug": "chinesische-flagge-perlturm"},
            "potala": {"text": "Der Potala-Palast in Flaggenfarben", "slug": "chinesische-flagge-potala-palast"},
            "guilin": {"text": "Die Karstberge von Guilin in Flaggenfarben", "slug": "chinesische-flagge-guilin-karstberge"},
            "pagoda": {"text": "Die Große Wildganspagode in Flaggenfarben", "slug": "chinesische-flagge-wildganspagode"},
        },
    },
    "download": {
        "svg": "„{name}“ als SVG herunterladen",
        "png": "„{name}“ als PNG herunterladen",
    },
    "etiquette": {
        "title": "Beflaggung & Etikette",
        "text": "Die Flagge wird an nationalen Feiertagen gehisst, insbesondere am Nationalfeiertag (1. Oktober) und in der anschließenden Goldenen Woche, sowie ganzjährig an Regierungsgebäuden, Schulen und Grenzübergängen. Sie darf niemals den Boden berühren, verkehrt herum gehisst oder in beschädigtem oder verblasstem Zustand gezeigt werden. An nationalen Trauertagen wird sie auf halbmast gesetzt.",
    },
    "footer": {
        "disclaimer": "Dies ist eine unabhängige, inoffizielle Informationswebsite über die Flagge der Volksrepublik China. Sie steht in keiner Verbindung zu einer Regierung und wird von keiner Regierung unterstützt oder betrieben.",
    },
}
