# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Bandiera Cinese — Significato, Storia e Colori",
        "description": "La bandiera cinese spiegata: significato delle cinque stelle, storia, colori e proporzioni ufficiali, più 33 illustrazioni da scaricare gratis.",
    },
    "brand": "Bandiera Cinese",
    "nav": {"meaning": "Significato", "history": "Storia", "data": "Dati Tecnici", "gallery": "Galleria", "etiquette": "Galateo", "faq": "FAQ", "historic": "Bandiere storiche", "coloring": "Da colorare"},
    "hero": {
        "flag_alt": "Bandiera della Repubblica Popolare Cinese — la bandiera rossa a cinque stelle",
        "title": "La Bandiera Rossa a Cinque Stelle",
        "subtitle": "Bandiera nazionale della Repubblica Popolare Cinese",
        "meta": "Adottata il 27 settembre 1949 · Proporzioni 3:2 · Designer: Zeng Liansong",
    },
    "meaning": {
        "title": "Significato e Simbolismo",
        "intro": "Adottato nel 1949, il design unisce colore, geometria e storia politica in un emblema immediatamente riconoscibile.",
        "cards": [
            {"title": "Il Campo Rosso", "text": "Il rosso rappresenta la rivoluzione ed è anche il colore tradizionale della buona fortuna e della festa nella cultura cinese."},
            {"title": "La Stella Grande", "text": "La grande stella dorata rappresenta la guida del Partito Comunista Cinese."},
            {"title": "Le Quattro Stelle Piccole", "text": "Rappresentano la grande unità del popolo cinese sotto quella guida — tradizionalmente descritte come la classe operaia, i contadini, la piccola borghesia urbana e la borghesia nazionale."},
            {"title": "Orientamento delle Stelle", "text": "Ogni stella piccola ha una punta rivolta precisamente verso il centro della stella grande, simboleggiando l'unità raccolta attorno a un centro comune."},
            {"title": "Giallo Dorato", "text": "Scelto per risaltare brillantemente sul campo rosso, simboleggiando la luce della rivoluzione che illumina il paese."},
        ],
    },
    "history": {
        "title": "Storia e Origine",
        "items": [
            {"date": "1949", "text": "Il 27 settembre 1949, pochi giorni prima della fondazione della Repubblica Popolare Cinese, la Conferenza Consultiva Politica del Popolo Cinese adottò formalmente la bandiera rossa a cinque stelle come bandiera nazionale. Fu issata per la prima volta su piazza Tienanmen il 1° ottobre 1949, durante la cerimonia che proclamava la nuova repubblica."},
            {"date": "Design", "text": "Il design vincitore fu opera di Zeng Liansong, un economista e artista dilettante dello Zhejiang, presentato durante un concorso pubblico nazionale che raccolse quasi 3.000 proposte. Il suo schizzo originale includeva falce e martello all'interno della stella grande; il comitato di selezione li rimosse per mantenere il design semplice e distinto dagli emblemi di altri stati socialisti."},
            {"date": "2004", "text": "Norme tecniche formali sulle proporzioni della bandiera, la geometria delle stelle e i colori furono codificate in standard nazionali (GB 12982 per la costruzione, GB 15092 per il colore)."},
        ],
    },
    "data": {
        "title": "Dati Tecnici",
        "ratio": {"title": "Proporzioni", "text": "Rapporto tra lunghezza e altezza della bandiera."},
        "grid": {"title": "Griglia di Costruzione", "text": "Una griglia di 30 × 20 unità. Centro della stella grande in (5,5), raggio esterno 3. Stelle piccole, raggio esterno 1, centrate in (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Colori",
            "red": "Rosso — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Giallo — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "Lo standard ufficiale definisce i colori tramite campioni fisici di riferimento, non codici digitali — i valori esadecimali a schermo sono solo approssimazioni.",
        },
        "orientation": {"title": "Regola di Orientamento delle Stelle", "text": "Ogni stella piccola è ruotata in modo che una delle sue punte si allinei esattamente con il centro della stella grande."},
    },
    "gallery": {
        "title": "Galleria e Uso Quotidiano",
        "intro": "Il motivo delle cinque stelle non è solo per i pennoni — qui viene reinterpretato come oggetti quotidiani, animali amati e luoghi famosi, tutti resi nel rosso e oro propri della bandiera.",
        "groups": {"objects": "Oggetti Quotidiani", "animals": "Animali Popolari in Cina", "landmarks": "Monumenti e la Mappa della Cina"},
        "disclaimer": "Rappresentazioni illustrative create per questo sito — non sono prodotti ufficiali o su licenza, né una mappa ufficiale.",
        "license": "Licenza delle immagini: tutte le illustrazioni di bandiere di questa pagina possono essere scaricate e utilizzate gratuitamente, anche per scopi commerciali. L'attribuzione (un link a china-flag.cn) è gradita ma non obbligatoria.",
        "items": {
            "box": {"text": "Bandiera Cinese a Forma di Pacco", "slug": "bandiera-cinese-pacco"},
            "car": {"text": "Bandiera Cinese a Forma di Auto", "slug": "bandiera-cinese-auto"},
            "phone": {"text": "Bandiera Cinese a Forma di Smartphone", "slug": "bandiera-cinese-smartphone"},
            "chest": {"text": "Bandiera Cinese a Forma di Forziere", "slug": "bandiera-cinese-forziere"},
            "teapot": {"text": "Bandiera Cinese a Forma di Teiera", "slug": "bandiera-cinese-teiera"},
            "teacup": {"text": "Bandiera Cinese a Forma di Tazza da Tè", "slug": "bandiera-cinese-tazza-da-te"},
            "umbrella": {"text": "Bandiera Cinese a Forma di Ombrello", "slug": "bandiera-cinese-ombrello"},
            "fan": {"text": "Bandiera Cinese a Forma di Ventaglio", "slug": "bandiera-cinese-ventaglio"},
            "lantern": {"text": "Bandiera Cinese a Forma di Lanterna", "slug": "bandiera-cinese-lanterna"},
            "bicycle": {"text": "Bandiera Cinese a Forma di Bicicletta", "slug": "bandiera-cinese-bicicletta"},
            "backpack": {"text": "Bandiera Cinese a Forma di Zaino", "slug": "bandiera-cinese-zaino"},
            "sneaker": {"text": "Bandiera Cinese a Forma di Sneaker", "slug": "bandiera-cinese-sneaker"},
            "bird": {"text": "Bandiera Cinese a Forma di Uccello", "slug": "bandiera-cinese-uccello"},
            "dragon": {"text": "Bandiera Cinese a Forma di Drago", "slug": "bandiera-cinese-drago"},
            "dog": {"text": "Bandiera Cinese a Forma di Cane", "slug": "bandiera-cinese-cane"},
            "snake": {"text": "Bandiera Cinese a Forma di Serpente", "slug": "bandiera-cinese-serpente"},
            "panda": {"text": "Bandiera Cinese a Forma di Panda", "slug": "bandiera-cinese-panda"},
            "tiger": {"text": "Bandiera Cinese a Forma di Tigre", "slug": "bandiera-cinese-tigre"},
            "rabbit": {"text": "Bandiera Cinese a Forma di Coniglio", "slug": "bandiera-cinese-coniglio"},
            "ox": {"text": "Bandiera Cinese a Forma di Bue", "slug": "bandiera-cinese-bue"},
            "horse": {"text": "Bandiera Cinese a Forma di Cavallo", "slug": "bandiera-cinese-cavallo"},
            "monkey": {"text": "Bandiera Cinese a Forma di Scimmia", "slug": "bandiera-cinese-scimmia"},
            "rooster": {"text": "Bandiera Cinese a Forma di Gallo", "slug": "bandiera-cinese-gallo"},
            "koi": {"text": "Bandiera Cinese a Forma di Carpa Koi", "slug": "bandiera-cinese-carpa-koi"},
            "map": {"text": "Bandiera Cinese a Forma del Contorno della Cina", "slug": "bandiera-cinese-contorno-della-cina"},
            "greatwall": {"text": "Bandiera Cinese a Forma della Grande Muraglia", "slug": "bandiera-cinese-grande-muraglia"},
            "forbiddencity": {"text": "Bandiera Cinese a Forma della Città Proibita", "slug": "bandiera-cinese-citta-proibita"},
            "templeofheaven": {"text": "Bandiera Cinese a Forma del Tempio del Cielo", "slug": "bandiera-cinese-tempio-del-cielo"},
            "terracotta": {"text": "Bandiera Cinese a Forma di Guerriero di Terracotta", "slug": "bandiera-cinese-guerriero-di-terracotta"},
            "pearltower": {"text": "Bandiera Cinese a Forma della Torre della Perla Orientale", "slug": "bandiera-cinese-torre-della-perla-orientale"},
            "potala": {"text": "Bandiera Cinese a Forma del Palazzo del Potala", "slug": "bandiera-cinese-palazzo-del-potala"},
            "guilin": {"text": "Bandiera Cinese a Forma delle Montagne Carsiche di Guilin", "slug": "bandiera-cinese-montagne-carsiche-di-guilin"},
            "pagoda": {"text": "Bandiera Cinese a Forma della Pagoda dell'Oca Selvatica", "slug": "bandiera-cinese-pagoda-dell-oca-selvatica"},
        },
    },
    "download": {
        "svg": "Scarica «{name}» in SVG",
        "png": "Scarica «{name}» in PNG",
    },
    "historical": {
        "title": "Bandiere storiche della Cina",
        "intro": "Prima della bandiera rossa a cinque stelle, la Cina issava vessilli molto diversi. Queste illustrazioni stilizzate mostrano i tre predecessori più noti.",
        "items": {
            "qing": {
                "name": "Bandiera del drago Qing",
                "period": "1889–1912",
                "text": "L'ultima dinastia imperiale usava una bandiera giallo oro con un drago azzurro che insegue una perla rossa — il giallo era il colore dell'imperatore.",
                "alt": "Bandiera del drago della dinastia Qing (1889–1912) — illustrazione stilizzata",
                "slug": "bandiera-storica-cina-drago-qing",
            },
            "fivecolor": {
                "name": "Bandiera a cinque colori",
                "period": "1912–1928",
                "text": "La prima bandiera della Repubblica di Cina: cinque strisce per i cinque grandi popoli della Cina — Han, Manciù, Mongoli, Hui e Tibetani.",
                "alt": "Bandiera a cinque colori della Repubblica di Cina (1912–1928)",
                "slug": "bandiera-storica-cina-cinque-colori",
            },
            "bluesky": {
                "name": "Cielo blu, sole bianco, terra rossa",
                "period": "1928–1949",
                "text": "La bandiera nazionale dell'era repubblicana sul continente fino al 1949, con un sole bianco a dodici raggi su un cantone blu.",
                "alt": "Bandiera dell'era della Repubblica di Cina (1928–1949) con cantone blu e sole bianco",
                "slug": "bandiera-storica-cina-cielo-blu-sole-bianco",
            },
        },
    },
    "coloring": {
        "title": "Pagina da colorare",
        "text": "Un contorno stampabile della bandiera cinese da colorare — ideale per la scuola o un pomeriggio di pioggia. Suggerimento: la stella grande e le quattro piccole si colorano di giallo oro su campo rosso.",
        "caption": "Bandiera cinese da colorare",
        "alt": "Pagina da colorare della bandiera cinese — contorno stampabile della bandiera rossa a cinque stelle",
        "slug": "bandiera-cinese-da-colorare",
    },
    "emoji": {
        "title": "Emoji della bandiera cinese",
        "text": "L'emoji della bandiera cinese 🇨🇳 è composta dai due simboli indicatori regionali C (U+1F1E8) e N (U+1F1F3). Copiala qui con un clic.",
        "copy": "Copia emoji",
        "copied": "Copiato!",
        "note": "Su alcuni sistemi Windows l'emoji viene mostrata come le lettere «CN» — su telefoni e sulla maggior parte degli altri dispositivi appare la bandiera.",
    },
    "consent": {
        "text": "Vorremmo misurare l'utilizzo di questo sito con Google Analytics. I cookie statistici vengono impostati solo con il tuo consenso.",
        "accept": "Accetta",
        "decline": "Rifiuta",
        "settings": "Impostazioni cookie",
    },
    "faq": {
        "title": "Domande Frequenti",
        "items": [
            {"q": "Cosa significano le cinque stelle della bandiera cinese?",
             "a": "La grande stella dorata rappresenta la guida del Partito Comunista Cinese, le quattro stelle più piccole la grande unità del popolo cinese. Ogni stella piccola ha una punta rivolta esattamente verso il centro della stella grande."},
            {"q": "Quali colori ha la bandiera cinese?",
             "a": "Rosso e giallo dorato. Il campo rosso corrisponde al Pantone 186 C (circa #DE2910 a schermo), le stelle al Pantone 012 C (circa #FFDE00). Il rosso simboleggia la rivoluzione, il giallo la luce che illumina il paese."},
            {"q": "Quando è stata adottata la bandiera cinese?",
             "a": "Il 27 settembre 1949. Fu issata per la prima volta su piazza Tienanmen a Pechino il 1° ottobre 1949, giorno della proclamazione della Repubblica Popolare Cinese."},
            {"q": "Chi ha disegnato la bandiera cinese?",
             "a": "Zeng Liansong, economista e artista dilettante della provincia dello Zhejiang. Il suo progetto vinse un concorso nazionale con quasi 3.000 proposte."},
            {"q": "Qual è il rapporto di proporzioni della bandiera cinese?",
             "a": "3:2 — la bandiera è una volta e mezza più lunga che alta."},
            {"q": "Posso scaricare gratuitamente le immagini della bandiera da questo sito?",
             "a": "Sì. Ogni illustrazione della galleria può essere scaricata gratuitamente come file vettoriale SVG o come immagine PNG."},
        ],
    },
    "etiquette": {
        "title": "Esposizione e Galateo",
        "text": "La bandiera viene issata nelle festività nazionali, in particolare la Festa Nazionale (1° ottobre) e la successiva Golden Week, oltre che tutto l'anno su edifici governativi, scuole e valichi di frontiera. Non deve mai toccare il suolo, essere issata capovolta o mostrata danneggiata o sbiadita. Nei giorni di lutto nazionale viene esposta a mezz'asta.",
    },
    "footer": {
        "disclaimer": "Questo è un sito web informativo indipendente e non ufficiale sulla bandiera della Repubblica Popolare Cinese. Non è affiliato, sostenuto o gestito per conto di alcun governo.",
    },
}
