# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Bendera ya China — Maana, Historia na Rangi",
        "description": "Bendera ya China imefafanuliwa: maana ya nyota tano, historia, rangi na uwiano rasmi — pamoja na michoro 33 ya kupakua bure.",
    },
    "brand": "Bendera ya China",
    "nav": {"meaning": "Maana", "history": "Historia", "data": "Taarifa za Kiufundi", "gallery": "Matunzio", "etiquette": "Adabu", "faq": "Maswali", "historic": "Bendera za Kihistoria", "coloring": "Picha ya Kupaka Rangi"},
    "hero": {
        "flag_alt": "Bendera ya Jamhuri ya Watu wa China — Bendera Nyekundu ya Nyota Tano",
        "title": "Bendera Nyekundu ya Nyota Tano",
        "subtitle": "Bendera ya taifa ya Jamhuri ya Watu wa China",
        "meta": "Ilipitishwa 27 Septemba 1949 · Uwiano 3:2 · Mbunifu: Zeng Liansong",
    },
    "meaning": {
        "title": "Maana na Ishara",
        "intro": "Muundo huu uliopitishwa mwaka 1949 unaunganisha rangi, jiometri na historia ya kisiasa kuwa nembo inayotambulika mara moja.",
        "cards": [
            {"title": "Uwanda Mwekundu", "text": "Rangi nyekundu inawakilisha mapinduzi, na pia ni rangi ya jadi ya bahati njema na sherehe katika utamaduni wa Kichina."},
            {"title": "Nyota Kubwa", "text": "Nyota kubwa ya dhahabu inawakilisha uongozi wa Chama cha Kikomunisti cha China."},
            {"title": "Nyota Nne Ndogo", "text": "Zinawakilisha umoja mkuu wa watu wa China chini ya uongozi huo — kwa maelezo ya jadi: tabaka la wafanyakazi, wakulima, wafanyabiashara wadogo wa mijini na mabepari wa kitaifa."},
            {"title": "Mwelekeo wa Nyota", "text": "Kila nyota ndogo ina ncha moja inayoelekea moja kwa moja katikati ya nyota kubwa — ishara ya umoja unaokusanyika kuzunguka kitovu kimoja."},
            {"title": "Njano ya Dhahabu", "text": "Ilichaguliwa ili ing'ae kwenye uwanda mwekundu — ishara ya mwanga wa mapinduzi unaoangaza nchi."},
        ],
    },
    "history": {
        "title": "Historia na Chimbuko",
        "items": [
            {"date": "1949", "text": "Tarehe 27 Septemba 1949, siku chache kabla ya kuanzishwa kwa Jamhuri ya Watu wa China, Mkutano wa Kisiasa wa Ushauri wa Watu wa China ulipitisha rasmi Bendera Nyekundu ya Nyota Tano kuwa bendera ya taifa. Ilipandishwa kwa mara ya kwanza kwenye Uwanja wa Tiananmen tarehe 1 Oktoba 1949, katika sherehe ya kutangazwa kwa jamhuri mpya."},
            {"date": "Muundo", "text": "Muundo ulioshinda ulitoka kwa Zeng Liansong, mwanauchumi na msanii wa kujifunza kutoka Zhejiang, uliowasilishwa katika shindano la kitaifa lililopokea kazi karibu 3,000. Mchoro wake wa awali ulikuwa na nyundo na mundu ndani ya nyota kubwa; kamati ya uteuzi iliviondoa ili muundo ubaki rahisi na utofautiane na nembo za nchi nyingine za kisoshalisti."},
            {"date": "2004", "text": "Viwango rasmi vya kiufundi vya uwiano wa bendera, jiometri ya nyota na rangi viliwekwa katika viwango vya kitaifa (GB 12982 kwa uundaji, GB 15092 kwa rangi)."},
        ],
    },
    "data": {
        "title": "Taarifa za Kiufundi",
        "ratio": {"title": "Uwiano", "text": "Uwiano wa urefu kwa upana wa bendera."},
        "grid": {"title": "Gridi ya Uundaji", "text": "Gridi ya vipimo 30 × 20. Kitovu cha nyota kubwa kiko (5,5), nusukipenyo ya nje 3. Nyota ndogo zina nusukipenyo ya nje 1; vitovu vyake ni (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Rangi",
            "red": "Nyekundu — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Njano — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "Kiwango rasmi kinafafanua rangi kwa sampuli halisi, si kwa misimbo ya kidijitali — thamani za hex kwenye skrini ni makadirio tu.",
        },
        "orientation": {"title": "Kanuni ya Mwelekeo wa Nyota", "text": "Kila nyota ndogo imezungushwa ili ncha yake moja ilingane sawasawa na kitovu cha nyota kubwa."},
    },
    "gallery": {
        "title": "Matunzio na Matumizi ya Kila Siku",
        "intro": "Mchoro wa nyota tano si wa milingoti ya bendera pekee — hapa umebuniwa upya kuwa vitu vya kila siku, wanyama wapendwao na maeneo maarufu, vyote kwa rangi nyekundu na dhahabu za bendera yenyewe.",
        "groups": {"objects": "Vitu vya Kila Siku", "animals": "Wanyama Maarufu nchini China", "landmarks": "Maeneo Maarufu na Ramani ya China"},
        "disclaimer": "Michoro ya mfano iliyotengenezwa kwa ajili ya tovuti hii — si bidhaa rasmi au zenye leseni, wala si ramani rasmi.",
        "license": "Leseni ya picha: Michoro yote ya bendera kwenye ukurasa huu inaweza kupakuliwa na kutumiwa bure, ikiwa ni pamoja na matumizi ya kibiashara. Kutaja chanzo (kiungo cha china-flag.cn) kunakaribishwa lakini si lazima.",
        "items": {
            "box": {"text": "Bendera ya China yenye Umbo la Kifurushi", "slug": "bendera-ya-china-kifurushi"},
            "car": {"text": "Bendera ya China yenye Umbo la Gari", "slug": "bendera-ya-china-gari"},
            "phone": {"text": "Bendera ya China yenye Umbo la Simu", "slug": "bendera-ya-china-simu"},
            "chest": {"text": "Bendera ya China yenye Umbo la Sanduku la Hazina", "slug": "bendera-ya-china-sanduku-la-hazina"},
            "teapot": {"text": "Bendera ya China yenye Umbo la Birika la Chai", "slug": "bendera-ya-china-birika"},
            "teacup": {"text": "Bendera ya China yenye Umbo la Kikombe cha Chai", "slug": "bendera-ya-china-kikombe"},
            "umbrella": {"text": "Bendera ya China yenye Umbo la Mwavuli", "slug": "bendera-ya-china-mwavuli"},
            "fan": {"text": "Bendera ya China yenye Umbo la Kipepeo cha Mkono", "slug": "bendera-ya-china-kipepeo"},
            "lantern": {"text": "Bendera ya China yenye Umbo la Taa", "slug": "bendera-ya-china-taa"},
            "bicycle": {"text": "Bendera ya China yenye Umbo la Baiskeli", "slug": "bendera-ya-china-baiskeli"},
            "backpack": {"text": "Bendera ya China yenye Umbo la Shanta", "slug": "bendera-ya-china-shanta"},
            "sneaker": {"text": "Bendera ya China yenye Umbo la Kiatu cha Michezo", "slug": "bendera-ya-china-kiatu"},
            "bird": {"text": "Bendera ya China yenye Umbo la Ndege", "slug": "bendera-ya-china-ndege"},
            "dragon": {"text": "Bendera ya China yenye Umbo la Joka", "slug": "bendera-ya-china-joka"},
            "dog": {"text": "Bendera ya China yenye Umbo la Mbwa", "slug": "bendera-ya-china-mbwa"},
            "snake": {"text": "Bendera ya China yenye Umbo la Nyoka", "slug": "bendera-ya-china-nyoka"},
            "panda": {"text": "Bendera ya China yenye Umbo la Panda", "slug": "bendera-ya-china-panda"},
            "tiger": {"text": "Bendera ya China yenye Umbo la Chui-Milia", "slug": "bendera-ya-china-chui"},
            "rabbit": {"text": "Bendera ya China yenye Umbo la Sungura", "slug": "bendera-ya-china-sungura"},
            "ox": {"text": "Bendera ya China yenye Umbo la Fahali", "slug": "bendera-ya-china-fahali"},
            "horse": {"text": "Bendera ya China yenye Umbo la Farasi", "slug": "bendera-ya-china-farasi"},
            "monkey": {"text": "Bendera ya China yenye Umbo la Tumbili", "slug": "bendera-ya-china-tumbili"},
            "rooster": {"text": "Bendera ya China yenye Umbo la Jogoo", "slug": "bendera-ya-china-jogoo"},
            "koi": {"text": "Bendera ya China yenye Umbo la Samaki wa Koi", "slug": "bendera-ya-china-samaki-koi"},
            "map": {"text": "Bendera ya China yenye Umbo la Ramani ya China", "slug": "bendera-ya-china-ramani"},
            "greatwall": {"text": "Bendera ya China yenye Umbo la Ukuta Mkuu", "slug": "bendera-ya-china-ukuta-mkuu"},
            "forbiddencity": {"text": "Bendera ya China yenye Umbo la Mji Uliokatazwa", "slug": "bendera-ya-china-mji-uliokatazwa"},
            "templeofheaven": {"text": "Bendera ya China yenye Umbo la Hekalu la Mbingu", "slug": "bendera-ya-china-hekalu-la-mbingu"},
            "terracotta": {"text": "Bendera ya China yenye Umbo la Askari wa Udongo", "slug": "bendera-ya-china-askari-wa-udongo"},
            "pearltower": {"text": "Bendera ya China yenye Umbo la Mnara wa Lulu", "slug": "bendera-ya-china-mnara-wa-lulu"},
            "potala": {"text": "Bendera ya China yenye Umbo la Kasri la Potala", "slug": "bendera-ya-china-kasri-la-potala"},
            "guilin": {"text": "Bendera ya China yenye Umbo la Milima ya Guilin", "slug": "bendera-ya-china-milima-ya-guilin"},
            "pagoda": {"text": "Bendera ya China yenye Umbo la Pagoda ya Bata-Mzinga Pori", "slug": "bendera-ya-china-pagoda"},
        },
    },
    "download": {
        "svg": "Pakua {name} kama SVG",
        "png": "Pakua {name} kama PNG",
    },
    "historical": {
        "title": "Bendera za Kihistoria za China",
        "intro": "Kabla ya Bendera Nyekundu ya Nyota Tano, bendera tofauti kabisa zilipepea juu ya China. Michoro hii ya kimtindo inaonyesha bendera tatu za awali maarufu zaidi.",
        "items": {
            "qing": {
                "name": "Bendera ya Joka ya Qing",
                "period": "1889–1912",
                "text": "Nasaba ya mwisho ya kifalme ilitumia bendera ya njano ya dhahabu yenye joka la bluu likifukuzia lulu nyekundu — njano ilikuwa rangi ya mfalme.",
                "alt": "Bendera ya joka ya nasaba ya Qing (1889–1912) — mchoro wa kimtindo",
                "slug": "bendera-ya-kihistoria-china-joka-la-qing",
            },
            "fivecolor": {
                "name": "Bendera ya Rangi Tano",
                "period": "1912–1928",
                "text": "Bendera ya kwanza ya Jamhuri ya China: mistari mitano kwa ajili ya mataifa makuu matano ya China — Wahan, Wamanchu, Wamongolia, Wahui na Watibeti.",
                "alt": "Bendera ya rangi tano ya Jamhuri ya China (1912–1928)",
                "slug": "bendera-ya-kihistoria-china-rangi-tano",
            },
            "bluesky": {
                "name": "Anga Bluu, Jua Jeupe, Ardhi Nyekundu",
                "period": "1928–1949",
                "text": "Bendera ya taifa ya enzi ya jamhuri barani hadi 1949, ikiwa na jua jeupe la miale kumi na miwili kwenye kona ya bluu.",
                "alt": "Bendera ya enzi ya Jamhuri ya China (1928–1949) yenye kona ya bluu na jua jeupe",
                "slug": "bendera-ya-kihistoria-china-anga-bluu-jua-jeupe",
            },
        },
    },
    "coloring": {
        "title": "Picha ya Kupaka Rangi",
        "text": "Muhtasari wa bendera ya China unaoweza kuchapishwa kwa ajili ya kupaka rangi — mzuri kwa shule au alasiri ya mvua. Dokezo: nyota kubwa na nyota nne ndogo hupakwa njano ya dhahabu kwenye uwanda mwekundu.",
        "caption": "Bendera ya China ya Kupaka Rangi",
        "alt": "Picha ya kupaka rangi ya bendera ya China — muhtasari unaochapishwa wa Bendera Nyekundu ya Nyota Tano",
        "slug": "bendera-ya-china-picha-ya-kupaka-rangi",
    },
    "emoji": {
        "title": "Emoji ya Bendera ya China",
        "text": "Emoji ya bendera ya China 🇨🇳 imeundwa na alama mbili za kiashiria cha eneo: C (U+1F1E8) na N (U+1F1F3). Inakili hapa kwa kubofya mara moja.",
        "copy": "Nakili emoji",
        "copied": "Imenakiliwa!",
        "note": "Katika baadhi ya mifumo ya Windows, emoji huonekana kama herufi “CN” — kwenye simu na vifaa vingine vingi bendera huonekana.",
    },
    "consent": {
        "text": "Tungependa kupima matumizi ya tovuti hii kwa Google Analytics. Vidakuzi vya takwimu huwekwa tu ukikubali.",
        "accept": "Kubali",
        "decline": "Kataa",
        "settings": "Mipangilio ya vidakuzi",
    },
    "faq": {
        "title": "Maswali Yanayoulizwa Mara kwa Mara",
        "items": [
            {"q": "Nyota tano kwenye bendera ya China zina maana gani?",
             "a": "Nyota kubwa ya dhahabu inawakilisha uongozi wa Chama cha Kikomunisti cha China, na nyota nne ndogo zinawakilisha umoja mkuu wa watu wa China. Kila nyota ndogo ina ncha moja inayoelekea moja kwa moja katikati ya nyota kubwa."},
            {"q": "Bendera ya China ina rangi zipi?",
             "a": "Nyekundu na njano ya dhahabu. Uwanda mwekundu unalingana na Pantone 186 C (takriban #DE2910 kwenye skrini), nyota ni Pantone 012 C (takriban #FFDE00). Nyekundu inawakilisha mapinduzi, njano mwanga unaoangaza nchi."},
            {"q": "Bendera ya China ilipitishwa lini?",
             "a": "Tarehe 27 Septemba 1949. Ilipandishwa kwa mara ya kwanza kwenye Uwanja wa Tiananmen mjini Beijing tarehe 1 Oktoba 1949 — siku ya kutangazwa kwa Jamhuri ya Watu wa China."},
            {"q": "Nani alibuni bendera ya China?",
             "a": "Zeng Liansong, mwanauchumi na msanii wa kujifunza kutoka mkoa wa Zhejiang. Muundo wake ulishinda shindano la kitaifa lililopokea kazi karibu 3,000."},
            {"q": "Uwiano wa bendera ya China ni upi?",
             "a": "3:2 — urefu wa bendera ni mara moja na nusu ya kimo chake."},
            {"q": "Naweza kupakua picha za bendera kwenye tovuti hii bure?",
             "a": "Ndiyo. Kila mchoro kwenye matunzio unaweza kupakuliwa bure kama faili ya vekta ya SVG au picha ya PNG."},
        ],
    },
    "etiquette": {
        "title": "Upandishaji na Adabu",
        "text": "Bendera hupandishwa siku za sikukuu za kitaifa, hasa Siku ya Taifa (1 Oktoba) na Wiki ya Dhahabu inayofuata, na pia mwaka mzima kwenye majengo ya serikali, shule na vituo vya mipakani. Haipaswi kamwe kugusa ardhi, kupandishwa kichwa chini, au kuonyeshwa ikiwa imechanika au imefifia. Siku za maombolezo ya kitaifa hupandishwa nusu mlingoti.",
    },
    "footer": {
        "disclaimer": "Hii ni tovuti huru na isiyo rasmi ya taarifa kuhusu bendera ya Jamhuri ya Watu wa China. Haihusiani na serikali yoyote, haijaidhinishwa wala kuendeshwa kwa niaba ya serikali yoyote.",
    },
}
