# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Chinese Vlag — Betekenis, Geschiedenis en Feiten over de Rode Vijfsterrenvlag",
        "description": "De Chinese vlag uitgelegd: betekenis van de vijf sterren, geschiedenis van de rode vijfsterrenvlag, officiële kleuren en verhoudingen, vlagetiquette en vlagthema-illustraties.",
    },
    "brand": "Chinese Vlag",
    "nav": {"meaning": "Betekenis", "history": "Geschiedenis", "data": "Technische Gegevens", "gallery": "Galerij", "etiquette": "Etiquette"},
    "hero": {
        "flag_alt": "Vlag van de Volksrepubliek China — de rode vijfsterrenvlag",
        "title": "De Rode Vijfsterrenvlag",
        "subtitle": "Nationale vlag van de Volksrepubliek China",
        "meta": "Aangenomen op 27 september 1949 · Verhouding 3:2 · Ontwerper: Zeng Liansong",
    },
    "meaning": {
        "title": "Betekenis en Symboliek",
        "intro": "Het in 1949 aangenomen ontwerp combineert kleur, geometrie en politieke geschiedenis tot een direct herkenbaar embleem.",
        "cards": [
            {"title": "Het Rode Veld", "text": "Rood staat voor de revolutie en is ook de traditionele kleur van geluk en feestvreugde in de Chinese cultuur."},
            {"title": "De Grote Ster", "text": "De grote gouden ster vertegenwoordigt de leiding van de Communistische Partij van China."},
            {"title": "De Vier Kleine Sterren", "text": "Ze staan voor de grote eenheid van het Chinese volk onder die leiding — traditioneel omschreven als de arbeidersklasse, de boerenstand, de stedelijke kleinburgerij en de nationale bourgeoisie."},
            {"title": "Oriëntatie van de Sterren", "text": "Elke kleine ster heeft één punt die precies naar het middelpunt van de grote ster wijst, als symbool van eenheid rond een gemeenschappelijk middelpunt."},
            {"title": "Goudgeel", "text": "Gekozen om schitterend af te steken tegen het rode veld, als symbool van het licht van de revolutie dat het land verlicht."},
        ],
    },
    "history": {
        "title": "Geschiedenis en Oorsprong",
        "items": [
            {"date": "1949", "text": "Op 27 september 1949, enkele dagen voor de oprichting van de Volksrepubliek China, nam de Chinese Volkspolitieke Consultatieve Conferentie de rode vijfsterrenvlag officieel aan als nationale vlag. Ze werd voor het eerst gehesen boven het Tiananmenplein op 1 oktober 1949, tijdens de plechtigheid waarbij de nieuwe republiek werd uitgeroepen."},
            {"date": "Ontwerp", "text": "Het winnende ontwerp kwam van Zeng Liansong, een econoom en amateurkunstenaar uit Zhejiang, ingediend tijdens een landelijke openbare wedstrijd met bijna 3.000 inzendingen. Zijn oorspronkelijke schets bevatte een hamer en sikkel binnen de grote ster; het selectiecomité verwijderde dit om het ontwerp eenvoudig te houden en te onderscheiden van de emblemen van andere socialistische staten."},
            {"date": "2004", "text": "Formele technische normen voor de verhoudingen, stergeometrie en kleuren van de vlag werden vastgelegd in nationale standaarden (GB 12982 voor de constructie, GB 15092 voor de kleur)."},
        ],
    },
    "data": {
        "title": "Technische Gegevens",
        "ratio": {"title": "Verhoudingen", "text": "Verhouding tussen lengte en breedte van de vlag."},
        "grid": {"title": "Constructieraster", "text": "Een raster van 30 × 20 eenheden. Middelpunt van de grote ster op (5,5), buitenstraal 3. Kleine sterren, buitenstraal 1, met middelpunten op (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Kleuren",
            "red": "Rood — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Geel — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "De officiële norm definieert kleuren aan de hand van fysieke referentiestalen, niet digitale codes — hexwaarden op het scherm zijn slechts benaderingen.",
        },
        "orientation": {"title": "Oriëntatieregel van de Sterren", "text": "Elke kleine ster is zo gedraaid dat één van de punten precies uitlijnt met het middelpunt van de grote ster."},
    },
    "gallery": {
        "title": "Galerij en Dagelijks Gebruik",
        "intro": "Het vijfsterrenmotief is niet alleen voor vlaggenmasten — hier wordt het opnieuw vormgegeven als alledaagse voorwerpen, geliefde dieren en beroemde bezienswaardigheden, allemaal in het rood en goud van de vlag zelf.",
        "groups": {"objects": "Alledaagse Voorwerpen", "animals": "Populaire Dieren in China", "landmarks": "Bezienswaardigheden & de Kaart van China"},
        "disclaimer": "Illustratieve weergaven gemaakt voor deze site — geen officiële of gelicentieerde producten, en geen officiële kaart.",
        "items": {
            "box": {"text": "Een Pakket in Vlagkleuren", "slug": "chinese-vlag-pakket"},
            "car": {"text": "Een Auto in Vlagkleuren", "slug": "chinese-vlag-auto"},
            "phone": {"text": "Een Smartphone in Vlagkleuren", "slug": "chinese-vlag-smartphone"},
            "chest": {"text": "Een Schatkist in Vlagkleuren", "slug": "chinese-vlag-schatkist"},
            "teapot": {"text": "Een Theepot in Vlagkleuren", "slug": "chinese-vlag-theepot"},
            "teacup": {"text": "Een Theekopje in Vlagkleuren", "slug": "chinese-vlag-theekopje"},
            "umbrella": {"text": "Een Paraplu in Vlagkleuren", "slug": "chinese-vlag-paraplu"},
            "fan": {"text": "Een Waaier in Vlagkleuren", "slug": "chinese-vlag-waaier"},
            "lantern": {"text": "Een Lantaarn in Vlagkleuren", "slug": "chinese-vlag-lantaarn"},
            "bicycle": {"text": "Een Fiets in Vlagkleuren", "slug": "chinese-vlag-fiets"},
            "backpack": {"text": "Een Rugzak in Vlagkleuren", "slug": "chinese-vlag-rugzak"},
            "sneaker": {"text": "Een Sneaker in Vlagkleuren", "slug": "chinese-vlag-sneaker"},
            "bird": {"text": "Een Vogel in Vlagvorm", "slug": "chinese-vlag-vogel"},
            "dragon": {"text": "Een Draak in Vlagvorm", "slug": "chinese-vlag-draak"},
            "dog": {"text": "Een Hond in Vlagvorm", "slug": "chinese-vlag-hond"},
            "snake": {"text": "Een Slang in Vlagvorm", "slug": "chinese-vlag-slang"},
            "panda": {"text": "Een Panda in Vlagvorm", "slug": "chinese-vlag-panda"},
            "tiger": {"text": "Een Tijger in Vlagvorm", "slug": "chinese-vlag-tijger"},
            "rabbit": {"text": "Een Konijn in Vlagvorm", "slug": "chinese-vlag-konijn"},
            "ox": {"text": "Een Os in Vlagvorm", "slug": "chinese-vlag-os"},
            "horse": {"text": "Een Paard in Vlagvorm", "slug": "chinese-vlag-paard"},
            "monkey": {"text": "Een Aap in Vlagvorm", "slug": "chinese-vlag-aap"},
            "rooster": {"text": "Een Haan in Vlagvorm", "slug": "chinese-vlag-haan"},
            "koi": {"text": "Een Koikarper in Vlagvorm", "slug": "chinese-vlag-koikarper"},
            "map": {"text": "De Omtrek van China in Vlagkleuren", "slug": "chinese-vlag-omtrek-van-china"},
            "greatwall": {"text": "De Chinese Muur in Vlagkleuren", "slug": "chinese-vlag-chinese-muur"},
            "forbiddencity": {"text": "De Verboden Stad in Vlagkleuren", "slug": "chinese-vlag-verboden-stad"},
            "templeofheaven": {"text": "De Hemeltempel in Vlagkleuren", "slug": "chinese-vlag-hemeltempel"},
            "terracotta": {"text": "Een Terracotta Krijger in Vlagkleuren", "slug": "chinese-vlag-terracotta-krijger"},
            "pearltower": {"text": "De Oriental Pearl Tower in Vlagkleuren", "slug": "chinese-vlag-oriental-pearl-tower"},
            "potala": {"text": "Het Potala-paleis in Vlagkleuren", "slug": "chinese-vlag-potala-paleis"},
            "guilin": {"text": "De Karstbergen van Guilin in Vlagkleuren", "slug": "chinese-vlag-guilin-karstbergen"},
            "pagoda": {"text": "De Wilde Ganzenpagode in Vlagkleuren", "slug": "chinese-vlag-wilde-ganzenpagode"},
        },
    },
    "etiquette": {
        "title": "Vlaggen en Etiquette",
        "text": "De vlag wordt gehesen op nationale feestdagen, met name op de Nationale Feestdag (1 oktober) en de daaropvolgende Gouden Week, en het hele jaar door bij overheidsgebouwen, scholen en grensovergangen. Ze mag nooit de grond raken, ondersteboven worden gehesen of in beschadigde of verbleekte staat worden getoond. Op nationale rouwdagen wordt ze halfstok gehesen.",
    },
    "footer": {
        "disclaimer": "Dit is een onafhankelijke, niet-officiële informatieve website over de vlag van de Volksrepubliek China. Ze is niet verbonden met, goedgekeurd door of geëxploiteerd namens enige overheid.",
    },
}
