# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Quốc kỳ Trung Quốc — Ý nghĩa, Lịch sử và Màu sắc",
        "description": "Quốc kỳ Trung Quốc: ý nghĩa năm ngôi sao, lịch sử, màu sắc và tỷ lệ chính thức — cùng 33 hình minh họa tải về miễn phí.",
    },
    "brand": "Quốc kỳ Trung Quốc",
    "nav": {"meaning": "Ý nghĩa", "history": "Lịch sử", "data": "Thông số kỹ thuật", "gallery": "Thư viện ảnh", "etiquette": "Nghi thức", "faq": "Hỏi đáp", "historic": "Quốc kỳ lịch sử", "coloring": "Tranh tô màu"},
    "hero": {
        "flag_alt": "Quốc kỳ nước Cộng hòa Nhân dân Trung Hoa — Cờ đỏ năm sao",
        "title": "Cờ đỏ năm sao",
        "subtitle": "Quốc kỳ nước Cộng hòa Nhân dân Trung Hoa",
        "meta": "Được thông qua ngày 27 tháng 9 năm 1949 · Tỷ lệ 3:2 · Người thiết kế: Tăng Liên Tùng",
    },
    "meaning": {
        "title": "Ý nghĩa và Biểu tượng",
        "intro": "Được thông qua năm 1949, thiết kế này kết hợp màu sắc, hình học và lịch sử chính trị thành một biểu tượng dễ nhận biết ngay lập tức.",
        "cards": [
            {"title": "Nền đỏ", "text": "Màu đỏ tượng trưng cho cách mạng, đồng thời là màu truyền thống của may mắn và lễ hội trong văn hóa Trung Hoa."},
            {"title": "Ngôi sao lớn", "text": "Ngôi sao vàng lớn tượng trưng cho sự lãnh đạo của Đảng Cộng sản Trung Quốc."},
            {"title": "Bốn ngôi sao nhỏ", "text": "Tượng trưng cho khối đại đoàn kết của nhân dân Trung Quốc dưới sự lãnh đạo đó — theo cách hiểu truyền thống là giai cấp công nhân, nông dân, tiểu tư sản thành thị và tư sản dân tộc."},
            {"title": "Hướng của các ngôi sao", "text": "Mỗi ngôi sao nhỏ có một đỉnh hướng thẳng vào tâm ngôi sao lớn, tượng trưng cho sự đoàn kết quanh một trung tâm chung."},
            {"title": "Màu vàng kim", "text": "Được chọn để nổi bật rực rỡ trên nền đỏ, tượng trưng cho ánh sáng cách mạng soi rọi đất nước."},
        ],
    },
    "history": {
        "title": "Lịch sử và Nguồn gốc",
        "items": [
            {"date": "1949", "text": "Ngày 27 tháng 9 năm 1949, ít ngày trước khi nước Cộng hòa Nhân dân Trung Hoa thành lập, Hội nghị Hiệp thương Chính trị Nhân dân Trung Quốc chính thức thông qua Cờ đỏ năm sao làm quốc kỳ. Lá cờ được kéo lên lần đầu tại Quảng trường Thiên An Môn ngày 1 tháng 10 năm 1949, trong lễ tuyên bố thành lập nước cộng hòa mới."},
            {"date": "Thiết kế", "text": "Mẫu thiết kế thắng cuộc thuộc về Tăng Liên Tùng, một nhà kinh tế và họa sĩ nghiệp dư quê Chiết Giang, gửi dự thi trong cuộc thi toàn quốc thu hút gần 3.000 tác phẩm. Bản phác thảo ban đầu có búa liềm trong ngôi sao lớn; ban tuyển chọn đã bỏ chi tiết này để thiết kế đơn giản hơn và khác biệt với quốc huy các nước xã hội chủ nghĩa khác."},
            {"date": "2004", "text": "Các tiêu chuẩn kỹ thuật chính thức về tỷ lệ, hình học ngôi sao và màu sắc của quốc kỳ được quy định trong tiêu chuẩn quốc gia (GB 12982 về cách dựng, GB 15092 về màu sắc)."},
        ],
    },
    "data": {
        "title": "Thông số kỹ thuật",
        "ratio": {"title": "Tỷ lệ", "text": "Tỷ lệ giữa chiều dài và chiều rộng của lá cờ."},
        "grid": {"title": "Lưới dựng hình", "text": "Lưới 30 × 20 đơn vị. Tâm ngôi sao lớn tại (5,5), bán kính ngoài 3. Các ngôi sao nhỏ bán kính ngoài 1, tâm tại (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Màu sắc",
            "red": "Đỏ — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Vàng — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "Tiêu chuẩn chính thức xác định màu bằng mẫu vật lý chứ không phải mã số — giá trị hex trên màn hình chỉ là gần đúng.",
        },
        "orientation": {"title": "Quy tắc hướng sao", "text": "Mỗi ngôi sao nhỏ được xoay sao cho một đỉnh của nó thẳng hàng chính xác với tâm ngôi sao lớn."},
    },
    "gallery": {
        "title": "Thư viện ảnh và Ứng dụng đời thường",
        "intro": "Họa tiết năm sao không chỉ dành cho cột cờ — tại đây nó được tái hiện thành đồ vật hằng ngày, những con vật được yêu thích và các danh thắng nổi tiếng, tất cả trong sắc đỏ và vàng của lá cờ.",
        "groups": {"objects": "Đồ vật hằng ngày", "animals": "Động vật được yêu thích ở Trung Quốc", "landmarks": "Danh thắng và bản đồ Trung Quốc"},
        "disclaimer": "Hình minh họa được tạo riêng cho trang này — không phải sản phẩm chính thức hay được cấp phép, cũng không phải bản đồ chính thức.",
        "license": "Giấy phép hình ảnh: Mọi hình minh họa quốc kỳ trên trang này đều có thể tải về và sử dụng miễn phí, kể cả cho mục đích thương mại. Ghi nguồn (liên kết tới china-flag.cn) được hoan nghênh nhưng không bắt buộc.",
        "items": {
            "box": {"text": "Quốc kỳ Trung Quốc hình bưu kiện", "slug": "quoc-ky-trung-quoc-buu-kien"},
            "car": {"text": "Quốc kỳ Trung Quốc hình ô tô", "slug": "quoc-ky-trung-quoc-o-to"},
            "phone": {"text": "Quốc kỳ Trung Quốc hình điện thoại", "slug": "quoc-ky-trung-quoc-dien-thoai"},
            "chest": {"text": "Quốc kỳ Trung Quốc hình rương kho báu", "slug": "quoc-ky-trung-quoc-ruong-kho-bau"},
            "teapot": {"text": "Quốc kỳ Trung Quốc hình ấm trà", "slug": "quoc-ky-trung-quoc-am-tra"},
            "teacup": {"text": "Quốc kỳ Trung Quốc hình chén trà", "slug": "quoc-ky-trung-quoc-chen-tra"},
            "umbrella": {"text": "Quốc kỳ Trung Quốc hình chiếc ô", "slug": "quoc-ky-trung-quoc-chiec-o"},
            "fan": {"text": "Quốc kỳ Trung Quốc hình quạt xếp", "slug": "quoc-ky-trung-quoc-quat-xep"},
            "lantern": {"text": "Quốc kỳ Trung Quốc hình đèn lồng", "slug": "quoc-ky-trung-quoc-den-long"},
            "bicycle": {"text": "Quốc kỳ Trung Quốc hình xe đạp", "slug": "quoc-ky-trung-quoc-xe-dap"},
            "backpack": {"text": "Quốc kỳ Trung Quốc hình ba lô", "slug": "quoc-ky-trung-quoc-ba-lo"},
            "sneaker": {"text": "Quốc kỳ Trung Quốc hình giày thể thao", "slug": "quoc-ky-trung-quoc-giay-the-thao"},
            "bird": {"text": "Quốc kỳ Trung Quốc hình chú chim", "slug": "quoc-ky-trung-quoc-chu-chim"},
            "dragon": {"text": "Quốc kỳ Trung Quốc hình con rồng", "slug": "quoc-ky-trung-quoc-con-rong"},
            "dog": {"text": "Quốc kỳ Trung Quốc hình chú chó", "slug": "quoc-ky-trung-quoc-chu-cho"},
            "snake": {"text": "Quốc kỳ Trung Quốc hình con rắn", "slug": "quoc-ky-trung-quoc-con-ran"},
            "panda": {"text": "Quốc kỳ Trung Quốc hình gấu trúc", "slug": "quoc-ky-trung-quoc-gau-truc"},
            "tiger": {"text": "Quốc kỳ Trung Quốc hình con hổ", "slug": "quoc-ky-trung-quoc-con-ho"},
            "rabbit": {"text": "Quốc kỳ Trung Quốc hình con thỏ", "slug": "quoc-ky-trung-quoc-con-tho"},
            "ox": {"text": "Quốc kỳ Trung Quốc hình con trâu", "slug": "quoc-ky-trung-quoc-con-trau"},
            "horse": {"text": "Quốc kỳ Trung Quốc hình con ngựa", "slug": "quoc-ky-trung-quoc-con-ngua"},
            "monkey": {"text": "Quốc kỳ Trung Quốc hình con khỉ", "slug": "quoc-ky-trung-quoc-con-khi"},
            "rooster": {"text": "Quốc kỳ Trung Quốc hình con gà trống", "slug": "quoc-ky-trung-quoc-ga-trong"},
            "koi": {"text": "Quốc kỳ Trung Quốc hình cá koi", "slug": "quoc-ky-trung-quoc-ca-koi"},
            "map": {"text": "Quốc kỳ Trung Quốc hình bản đồ Trung Quốc", "slug": "quoc-ky-trung-quoc-ban-do"},
            "greatwall": {"text": "Quốc kỳ Trung Quốc hình Vạn Lý Trường Thành", "slug": "quoc-ky-trung-quoc-van-ly-truong-thanh"},
            "forbiddencity": {"text": "Quốc kỳ Trung Quốc hình Tử Cấm Thành", "slug": "quoc-ky-trung-quoc-tu-cam-thanh"},
            "templeofheaven": {"text": "Quốc kỳ Trung Quốc hình Thiên Đàn", "slug": "quoc-ky-trung-quoc-thien-dan"},
            "terracotta": {"text": "Quốc kỳ Trung Quốc hình chiến binh đất nung", "slug": "quoc-ky-trung-quoc-chien-binh-dat-nung"},
            "pearltower": {"text": "Quốc kỳ Trung Quốc hình tháp Minh Châu Phương Đông", "slug": "quoc-ky-trung-quoc-thap-minh-chau"},
            "potala": {"text": "Quốc kỳ Trung Quốc hình cung điện Potala", "slug": "quoc-ky-trung-quoc-cung-potala"},
            "guilin": {"text": "Quốc kỳ Trung Quốc hình núi đá vôi Quế Lâm", "slug": "quoc-ky-trung-quoc-nui-que-lam"},
            "pagoda": {"text": "Quốc kỳ Trung Quốc hình Đại Nhạn Tháp", "slug": "quoc-ky-trung-quoc-dai-nhan-thap"},
        },
    },
    "download": {
        "svg": "Tải {name} dạng SVG",
        "png": "Tải {name} dạng PNG",
    },
    "historical": {
        "title": "Các quốc kỳ lịch sử của Trung Quốc",
        "intro": "Trước Cờ đỏ năm sao, Trung Quốc từng treo những lá cờ rất khác. Các hình minh họa cách điệu này giới thiệu ba lá cờ tiền nhiệm nổi tiếng nhất.",
        "items": {
            "qing": {
                "name": "Cờ rồng nhà Thanh",
                "period": "1889–1912",
                "text": "Triều đại phong kiến cuối cùng dùng lá cờ vàng kim với con rồng xanh đuổi theo viên ngọc đỏ — màu vàng là màu của hoàng đế.",
                "alt": "Cờ rồng của nhà Thanh (1889–1912) — hình minh họa cách điệu",
                "slug": "quoc-ky-lich-su-trung-quoc-co-rong-nha-thanh",
            },
            "fivecolor": {
                "name": "Cờ ngũ sắc",
                "period": "1912–1928",
                "text": "Lá quốc kỳ đầu tiên của Trung Hoa Dân Quốc: năm dải màu tượng trưng cho năm dân tộc lớn của Trung Quốc — Hán, Mãn, Mông, Hồi và Tạng.",
                "alt": "Cờ ngũ sắc của Trung Hoa Dân Quốc (1912–1928)",
                "slug": "quoc-ky-lich-su-trung-quoc-co-ngu-sac",
            },
            "bluesky": {
                "name": "Thanh thiên bạch nhật mãn địa hồng",
                "period": "1928–1949",
                "text": "Quốc kỳ thời kỳ Dân Quốc trên đại lục đến năm 1949, với mặt trời trắng mười hai tia trên góc cờ màu xanh.",
                "alt": "Quốc kỳ thời Trung Hoa Dân Quốc (1928–1949) với góc xanh và mặt trời trắng",
                "slug": "quoc-ky-lich-su-trung-quoc-thanh-thien-bach-nhat",
            },
        },
    },
    "coloring": {
        "title": "Tranh tô màu",
        "text": "Đường nét quốc kỳ Trung Quốc có thể in ra để tô màu — lý tưởng cho trường học hoặc một buổi chiều mưa. Gợi ý: ngôi sao lớn và bốn ngôi sao nhỏ tô màu vàng kim trên nền đỏ.",
        "caption": "Quốc kỳ Trung Quốc — tranh tô màu",
        "alt": "Tranh tô màu quốc kỳ Trung Quốc — đường nét Cờ đỏ năm sao để in",
        "slug": "quoc-ky-trung-quoc-tranh-to-mau",
    },
    "emoji": {
        "title": "Emoji quốc kỳ Trung Quốc",
        "text": "Emoji quốc kỳ Trung Quốc 🇨🇳 gồm hai ký hiệu chỉ báo khu vực C (U+1F1E8) và N (U+1F1F3). Sao chép tại đây chỉ với một cú nhấp.",
        "copy": "Sao chép emoji",
        "copied": "Đã sao chép!",
        "note": "Trên một số hệ thống Windows, emoji hiển thị thành hai chữ cái “CN” — trên điện thoại và hầu hết thiết bị khác, lá cờ sẽ hiện ra.",
    },
    "consent": {
        "text": "Chúng tôi muốn đo lường việc sử dụng trang này bằng Google Analytics. Cookie thống kê chỉ được đặt khi bạn đồng ý.",
        "accept": "Đồng ý",
        "decline": "Từ chối",
        "settings": "Cài đặt cookie",
    },
    "faq": {
        "title": "Câu hỏi thường gặp",
        "items": [
            {"q": "Năm ngôi sao trên quốc kỳ Trung Quốc có ý nghĩa gì?",
             "a": "Ngôi sao vàng lớn tượng trưng cho sự lãnh đạo của Đảng Cộng sản Trung Quốc, bốn ngôi sao nhỏ tượng trưng cho khối đại đoàn kết của nhân dân Trung Quốc. Mỗi ngôi sao nhỏ có một đỉnh hướng thẳng vào tâm ngôi sao lớn."},
            {"q": "Quốc kỳ Trung Quốc có những màu nào?",
             "a": "Đỏ và vàng kim. Nền đỏ tương ứng Pantone 186 C (trên màn hình khoảng #DE2910), các ngôi sao là Pantone 012 C (khoảng #FFDE00). Màu đỏ tượng trưng cho cách mạng, màu vàng là ánh sáng soi rọi đất nước."},
            {"q": "Quốc kỳ Trung Quốc được thông qua khi nào?",
             "a": "Ngày 27 tháng 9 năm 1949. Lá cờ được kéo lên lần đầu tại Quảng trường Thiên An Môn, Bắc Kinh, ngày 1 tháng 10 năm 1949 — ngày tuyên bố thành lập nước Cộng hòa Nhân dân Trung Hoa."},
            {"q": "Ai là người thiết kế quốc kỳ Trung Quốc?",
             "a": "Tăng Liên Tùng, một nhà kinh tế và họa sĩ nghiệp dư quê Chiết Giang. Mẫu thiết kế của ông thắng cuộc thi toàn quốc với gần 3.000 tác phẩm dự thi."},
            {"q": "Tỷ lệ của quốc kỳ Trung Quốc là bao nhiêu?",
             "a": "3:2 — chiều dài lá cờ bằng một rưỡi chiều cao."},
            {"q": "Tôi có thể tải miễn phí hình quốc kỳ trên trang này không?",
             "a": "Có. Mọi hình minh họa trong thư viện đều có thể tải miễn phí dưới dạng tệp vector SVG hoặc ảnh PNG."},
        ],
    },
    "etiquette": {
        "title": "Treo cờ và Nghi thức",
        "text": "Quốc kỳ được treo vào các ngày lễ quốc gia, đặc biệt là Quốc khánh (1 tháng 10) và Tuần lễ Vàng sau đó, đồng thời quanh năm tại các cơ quan nhà nước, trường học và cửa khẩu. Cờ không được chạm đất, không được treo ngược, không được dùng khi đã rách hoặc phai màu. Vào ngày quốc tang, cờ được treo rủ.",
    },
    "footer": {
        "disclaimer": "Đây là trang thông tin độc lập, không chính thức về quốc kỳ nước Cộng hòa Nhân dân Trung Hoa. Trang không liên kết với, không được bảo trợ hay vận hành thay mặt bất kỳ chính phủ nào.",
    },
}
