# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Chinese Vlag — Betekenis, Geschiedenis en Feiten over de Rode Vijfsterrenvlag",
        "description": "De Chinese vlag uitgelegd: betekenis van de vijf sterren, geschiedenis van de rode vijfsterrenvlag, officiële kleuren en verhoudingen, vlagetiquette en vlagthema-illustraties.",
    },
    "brand": "Chinese Vlag",
    "nav": {"meaning": "Betekenis", "history": "Geschiedenis", "data": "Technische Gegevens", "gallery": "Galerij", "etiquette": "Etiquette"},
    "hero": {
        "flag_alt": "Vlag van de Volksrepubliek China — de rode vijfsterrenvlag",
        "title": "De Rode Vijfsterrenvlag",
        "subtitle": "Nationale vlag van de Volksrepubliek China",
        "meta": "Aangenomen op 27 september 1949 · Verhouding 3:2 · Ontwerper: Zeng Liansong",
    },
    "meaning": {
        "title": "Betekenis en Symboliek",
        "intro": "Het in 1949 aangenomen ontwerp combineert kleur, geometrie en politieke geschiedenis tot een direct herkenbaar embleem.",
        "cards": [
            {"title": "Het Rode Veld", "text": "Rood staat voor de revolutie en is ook de traditionele kleur van geluk en feestvreugde in de Chinese cultuur."},
            {"title": "De Grote Ster", "text": "De grote gouden ster vertegenwoordigt de leiding van de Communistische Partij van China."},
            {"title": "De Vier Kleine Sterren", "text": "Ze staan voor de grote eenheid van het Chinese volk onder die leiding — traditioneel omschreven als de arbeidersklasse, de boerenstand, de stedelijke kleinburgerij en de nationale bourgeoisie."},
            {"title": "Oriëntatie van de Sterren", "text": "Elke kleine ster heeft één punt die precies naar het middelpunt van de grote ster wijst, als symbool van eenheid rond een gemeenschappelijk middelpunt."},
            {"title": "Goudgeel", "text": "Gekozen om schitterend af te steken tegen het rode veld, als symbool van het licht van de revolutie dat het land verlicht."},
        ],
    },
    "history": {
        "title": "Geschiedenis en Oorsprong",
        "items": [
            {"date": "1949", "text": "Op 27 september 1949, enkele dagen voor de oprichting van de Volksrepubliek China, nam de Chinese Volkspolitieke Consultatieve Conferentie de rode vijfsterrenvlag officieel aan als nationale vlag. Ze werd voor het eerst gehesen boven het Tiananmenplein op 1 oktober 1949, tijdens de plechtigheid waarbij de nieuwe republiek werd uitgeroepen."},
            {"date": "Ontwerp", "text": "Het winnende ontwerp kwam van Zeng Liansong, een econoom en amateurkunstenaar uit Zhejiang, ingediend tijdens een landelijke openbare wedstrijd met bijna 3.000 inzendingen. Zijn oorspronkelijke schets bevatte een hamer en sikkel binnen de grote ster; het selectiecomité verwijderde dit om het ontwerp eenvoudig te houden en te onderscheiden van de emblemen van andere socialistische staten."},
            {"date": "2004", "text": "Formele technische normen voor de verhoudingen, stergeometrie en kleuren van de vlag werden vastgelegd in nationale standaarden (GB 12982 voor de constructie, GB 15092 voor de kleur)."},
        ],
    },
    "data": {
        "title": "Technische Gegevens",
        "ratio": {"title": "Verhoudingen", "text": "Verhouding tussen lengte en breedte van de vlag."},
        "grid": {"title": "Constructieraster", "text": "Een raster van 30 × 20 eenheden. Middelpunt van de grote ster op (5,5), buitenstraal 3. Kleine sterren, buitenstraal 1, met middelpunten op (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Kleuren",
            "red": "Rood — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Geel — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "De officiële norm definieert kleuren aan de hand van fysieke referentiestalen, niet digitale codes — hexwaarden op het scherm zijn slechts benaderingen.",
        },
        "orientation": {"title": "Oriëntatieregel van de Sterren", "text": "Elke kleine ster is zo gedraaid dat één van de punten precies uitlijnt met het middelpunt van de grote ster."},
    },
    "gallery": {
        "title": "Galerij en Dagelijks Gebruik",
        "intro": "Het vijfsterrenmotief is niet alleen voor vlaggenmasten — hier wordt het opnieuw vormgegeven als alledaagse voorwerpen, geliefde dieren en beroemde bezienswaardigheden, allemaal in het rood en goud van de vlag zelf.",
        "groups": {"objects": "Alledaagse Voorwerpen", "animals": "Populaire Dieren in China", "landmarks": "Bezienswaardigheden & de Kaart van China"},
        "disclaimer": "Illustratieve weergaven gemaakt voor deze site — geen officiële of gelicentieerde producten, en geen officiële kaart.",
        "items": {
            "box": {"text": "Chinese Vlag in de Vorm van een Pakket", "slug": "chinese-vlag-pakket"},
            "car": {"text": "Chinese Vlag in de Vorm van een Auto", "slug": "chinese-vlag-auto"},
            "phone": {"text": "Chinese Vlag in de Vorm van een Smartphone", "slug": "chinese-vlag-smartphone"},
            "chest": {"text": "Chinese Vlag in de Vorm van een Schatkist", "slug": "chinese-vlag-schatkist"},
            "teapot": {"text": "Chinese Vlag in de Vorm van een Theepot", "slug": "chinese-vlag-theepot"},
            "teacup": {"text": "Chinese Vlag in de Vorm van een Theekopje", "slug": "chinese-vlag-theekopje"},
            "umbrella": {"text": "Chinese Vlag in de Vorm van een Paraplu", "slug": "chinese-vlag-paraplu"},
            "fan": {"text": "Chinese Vlag in de Vorm van een Waaier", "slug": "chinese-vlag-waaier"},
            "lantern": {"text": "Chinese Vlag in de Vorm van een Lantaarn", "slug": "chinese-vlag-lantaarn"},
            "bicycle": {"text": "Chinese Vlag in de Vorm van een Fiets", "slug": "chinese-vlag-fiets"},
            "backpack": {"text": "Chinese Vlag in de Vorm van een Rugzak", "slug": "chinese-vlag-rugzak"},
            "sneaker": {"text": "Chinese Vlag in de Vorm van een Sneaker", "slug": "chinese-vlag-sneaker"},
            "bird": {"text": "Chinese Vlag in de Vorm van een Vogel", "slug": "chinese-vlag-vogel"},
            "dragon": {"text": "Chinese Vlag in de Vorm van een Draak", "slug": "chinese-vlag-draak"},
            "dog": {"text": "Chinese Vlag in de Vorm van een Hond", "slug": "chinese-vlag-hond"},
            "snake": {"text": "Chinese Vlag in de Vorm van een Slang", "slug": "chinese-vlag-slang"},
            "panda": {"text": "Chinese Vlag in de Vorm van een Panda", "slug": "chinese-vlag-panda"},
            "tiger": {"text": "Chinese Vlag in de Vorm van een Tijger", "slug": "chinese-vlag-tijger"},
            "rabbit": {"text": "Chinese Vlag in de Vorm van een Konijn", "slug": "chinese-vlag-konijn"},
            "ox": {"text": "Chinese Vlag in de Vorm van een Os", "slug": "chinese-vlag-os"},
            "horse": {"text": "Chinese Vlag in de Vorm van een Paard", "slug": "chinese-vlag-paard"},
            "monkey": {"text": "Chinese Vlag in de Vorm van een Aap", "slug": "chinese-vlag-aap"},
            "rooster": {"text": "Chinese Vlag in de Vorm van een Haan", "slug": "chinese-vlag-haan"},
            "koi": {"text": "Chinese Vlag in de Vorm van een Koikarper", "slug": "chinese-vlag-koikarper"},
            "map": {"text": "Chinese Vlag in de Vorm van de Omtrek van China", "slug": "chinese-vlag-omtrek-van-china"},
            "greatwall": {"text": "Chinese Vlag in de Vorm van de Chinese Muur", "slug": "chinese-vlag-chinese-muur"},
            "forbiddencity": {"text": "Chinese Vlag in de Vorm van de Verboden Stad", "slug": "chinese-vlag-verboden-stad"},
            "templeofheaven": {"text": "Chinese Vlag in de Vorm van de Hemeltempel", "slug": "chinese-vlag-hemeltempel"},
            "terracotta": {"text": "Chinese Vlag in de Vorm van een Terracotta Krijger", "slug": "chinese-vlag-terracotta-krijger"},
            "pearltower": {"text": "Chinese Vlag in de Vorm van de Oriental Pearl Tower", "slug": "chinese-vlag-oriental-pearl-tower"},
            "potala": {"text": "Chinese Vlag in de Vorm van het Potala-paleis", "slug": "chinese-vlag-potala-paleis"},
            "guilin": {"text": "Chinese Vlag in de Vorm van de Karstbergen van Guilin", "slug": "chinese-vlag-guilin-karstbergen"},
            "pagoda": {"text": "Chinese Vlag in de Vorm van de Wilde Ganzenpagode", "slug": "chinese-vlag-wilde-ganzenpagode"},
        },
    },
    "download": {
        "svg": "{name} downloaden als SVG",
        "png": "{name} downloaden als PNG",
    },
    "etiquette": {
        "title": "Vlaggen en Etiquette",
        "text": "De vlag wordt gehesen op nationale feestdagen, met name op de Nationale Feestdag (1 oktober) en de daaropvolgende Gouden Week, en het hele jaar door bij overheidsgebouwen, scholen en grensovergangen. Ze mag nooit de grond raken, ondersteboven worden gehesen of in beschadigde of verbleekte staat worden getoond. Op nationale rouwdagen wordt ze halfstok gehesen.",
    },
    "footer": {
        "disclaimer": "Dit is een onafhankelijke, niet-officiële informatieve website over de vlag van de Volksrepubliek China. Ze is niet verbonden met, goedgekeurd door of geëxploiteerd namens enige overheid.",
    },
}
