# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Flaga Chin — Znaczenie, Historia i Kolory",
        "description": "Flaga Chin wyjaśniona: znaczenie pięciu gwiazd, historia czerwonej flagi z pięcioma gwiazdami, oficjalne kolory i proporcje, etykieta flagowania oraz ilustracje tematyczne.",
    },
    "brand": "Flaga Chin",
    "nav": {"meaning": "Znaczenie", "history": "Historia", "data": "Dane Techniczne", "gallery": "Galeria", "etiquette": "Etykieta", "faq": "FAQ"},
    "hero": {
        "flag_alt": "Flaga Chińskiej Republiki Ludowej — czerwona flaga z pięcioma gwiazdami",
        "title": "Czerwona Flaga z Pięcioma Gwiazdami",
        "subtitle": "Flaga narodowa Chińskiej Republiki Ludowej",
        "meta": "Przyjęta 27 września 1949 · Proporcje 3:2 · Projektant: Zeng Liansong",
    },
    "meaning": {
        "title": "Znaczenie i Symbolika",
        "intro": "Przyjęty w 1949 roku projekt łączy kolor, geometrię i historię polityczną w jeden, natychmiast rozpoznawalny symbol.",
        "cards": [
            {"title": "Czerwone Tło", "text": "Czerwień symbolizuje rewolucję, a także jest tradycyjnym kolorem szczęścia i świętowania w kulturze chińskiej."},
            {"title": "Duża Gwiazda", "text": "Duża złota gwiazda symbolizuje przywództwo Komunistycznej Partii Chin."},
            {"title": "Cztery Małe Gwiazdy", "text": "Symbolizują wielką jedność narodu chińskiego pod tym przywództwem — tradycyjnie opisywaną jako klasa robotnicza, chłopstwo, miejskie drobnomieszczaństwo i burżuazja narodowa."},
            {"title": "Orientacja Gwiazd", "text": "Każda mała gwiazda ma jeden wierzchołek skierowany dokładnie na środek dużej gwiazdy, symbolizując jedność skupioną wokół wspólnego centrum."},
            {"title": "Złoty Żółty", "text": "Wybrany, by wyraźnie odcinać się od czerwonego tła, symbolizując światło rewolucji oświetlające kraj."},
        ],
    },
    "history": {
        "title": "Historia i Pochodzenie",
        "items": [
            {"date": "1949", "text": "27 września 1949 roku, na kilka dni przed powstaniem Chińskiej Republiki Ludowej, Chińska Ludowa Konferencja Konsultatywna Polityczna formalnie przyjęła czerwoną flagę z pięcioma gwiazdami jako flagę narodową. Po raz pierwszy została wciągnięta na maszt nad placem Tiananmen 1 października 1949 roku, podczas ceremonii proklamującej nową republikę."},
            {"date": "Projekt", "text": "Zwycięski projekt stworzył Zeng Liansong, ekonomista i amatorski artysta z Zhejiangu, zgłoszony podczas ogólnokrajowego konkursu publicznego, na który wpłynęło prawie 3000 zgłoszeń. Jego pierwotny szkic zawierał młot i sierp wewnątrz dużej gwiazdy; komisja selekcyjna usunęła je, aby zachować prostotę projektu i odróżnić go od godeł innych państw socjalistycznych."},
            {"date": "2004", "text": "Formalne normy techniczne dotyczące proporcji flagi, geometrii gwiazd i kolorów zostały skodyfikowane w normach krajowych (GB 12982 dla konstrukcji, GB 15092 dla koloru)."},
        ],
    },
    "data": {
        "title": "Dane Techniczne",
        "ratio": {"title": "Proporcje", "text": "Stosunek długości do szerokości flagi."},
        "grid": {"title": "Siatka Konstrukcyjna", "text": "Siatka o wymiarach 30 × 20 jednostek. Środek dużej gwiazdy w punkcie (5,5), promień zewnętrzny 3. Małe gwiazdy o promieniu zewnętrznym 1, ze środkami w punktach (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Kolory",
            "red": "Czerwony — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Żółty — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "Oficjalna norma definiuje kolory za pomocą fizycznych próbek wzorcowych, a nie kodów cyfrowych — wartości szesnastkowe na ekranie są jedynie przybliżeniem.",
        },
        "orientation": {"title": "Zasada Orientacji Gwiazd", "text": "Każda mała gwiazda jest obrócona tak, że jeden z jej wierzchołków dokładnie pokrywa się ze środkiem dużej gwiazdy."},
    },
    "gallery": {
        "title": "Galeria i Zastosowanie na Co Dzień",
        "intro": "Motyw pięciu gwiazd nie jest zarezerwowany tylko dla masztów — tutaj zostaje na nowo odkryty jako przedmioty codzienne, popularne zwierzęta i słynne zabytki, wszystkie przedstawione w czerwieni i złocie samej flagi.",
        "groups": {"objects": "Przedmioty Codzienne", "animals": "Popularne Zwierzęta w Chinach", "landmarks": "Zabytki i Mapa Chin"},
        "disclaimer": "Ilustracje stworzone na potrzeby tej strony — nie są to oficjalne ani licencjonowane produkty, ani oficjalna mapa.",
        "items": {
            "box": {"text": "Flaga Chin jako Paczka", "slug": "flaga-chin-paczka"},
            "car": {"text": "Flaga Chin jako Samochód", "slug": "flaga-chin-samochod"},
            "phone": {"text": "Flaga Chin jako Smartfon", "slug": "flaga-chin-smartfon"},
            "chest": {"text": "Flaga Chin jako Skrzynia Skarbów", "slug": "flaga-chin-skrzynia-skarbow"},
            "teapot": {"text": "Flaga Chin jako Czajniczek", "slug": "flaga-chin-czajniczek"},
            "teacup": {"text": "Flaga Chin jako Filiżanka", "slug": "flaga-chin-filizanka"},
            "umbrella": {"text": "Flaga Chin jako Parasol", "slug": "flaga-chin-parasol"},
            "fan": {"text": "Flaga Chin jako Wachlarz", "slug": "flaga-chin-wachlarz"},
            "lantern": {"text": "Flaga Chin jako Lampion", "slug": "flaga-chin-lampion"},
            "bicycle": {"text": "Flaga Chin jako Rower", "slug": "flaga-chin-rower"},
            "backpack": {"text": "Flaga Chin jako Plecak", "slug": "flaga-chin-plecak"},
            "sneaker": {"text": "Flaga Chin jako Sneakersy", "slug": "flaga-chin-sneakers"},
            "bird": {"text": "Flaga Chin jako Ptak", "slug": "flaga-chin-ptak"},
            "dragon": {"text": "Flaga Chin jako Smok", "slug": "flaga-chin-smok"},
            "dog": {"text": "Flaga Chin jako Pies", "slug": "flaga-chin-pies"},
            "snake": {"text": "Flaga Chin jako Wąż", "slug": "flaga-chin-waz"},
            "panda": {"text": "Flaga Chin jako Panda", "slug": "flaga-chin-panda"},
            "tiger": {"text": "Flaga Chin jako Tygrys", "slug": "flaga-chin-tygrys"},
            "rabbit": {"text": "Flaga Chin jako Królik", "slug": "flaga-chin-krolik"},
            "ox": {"text": "Flaga Chin jako Wół", "slug": "flaga-chin-wol"},
            "horse": {"text": "Flaga Chin jako Koń", "slug": "flaga-chin-kon"},
            "monkey": {"text": "Flaga Chin jako Małpa", "slug": "flaga-chin-malpa"},
            "rooster": {"text": "Flaga Chin jako Kogut", "slug": "flaga-chin-kogut"},
            "koi": {"text": "Flaga Chin jako Karp Koi", "slug": "flaga-chin-karp-koi"},
            "map": {"text": "Flaga Chin jako Kontur Chin", "slug": "flaga-chin-kontur-chin"},
            "greatwall": {"text": "Flaga Chin jako Wielki Mur", "slug": "flaga-chin-wielki-mur"},
            "forbiddencity": {"text": "Flaga Chin jako Zakazane Miasto", "slug": "flaga-chin-zakazane-miasto"},
            "templeofheaven": {"text": "Flaga Chin jako Świątynia Nieba", "slug": "flaga-chin-swiatynia-nieba"},
            "terracotta": {"text": "Flaga Chin jako Wojownik Terakotowy", "slug": "flaga-chin-wojownik-terakotowy"},
            "pearltower": {"text": "Flaga Chin jako Wieża Perły Orientu", "slug": "flaga-chin-wieza-perly-orientu"},
            "potala": {"text": "Flaga Chin jako Pałac Potala", "slug": "flaga-chin-palac-potala"},
            "guilin": {"text": "Flaga Chin jako Góry Krasowe Guilin", "slug": "flaga-chin-gory-krasowe-guilin"},
            "pagoda": {"text": "Flaga Chin jako Pagoda Dzikiej Gęsi", "slug": "flaga-chin-pagoda-dzikiej-gesi"},
        },
    },
    "download": {
        "svg": "Pobierz {name} jako SVG",
        "png": "Pobierz {name} jako PNG",
    },
    "faq": {
        "title": "Najczęstsze Pytania",
        "items": [
            {"q": "Co oznaczają gwiazdy na fladze Chin?",
             "a": "Duża złota gwiazda symbolizuje przywództwo Komunistycznej Partii Chin, a cztery mniejsze gwiazdy wielką jedność narodu chińskiego. Każda mała gwiazda ma jeden wierzchołek skierowany dokładnie na środek dużej gwiazdy."},
            {"q": "Jakie kolory ma flaga Chin?",
             "a": "Czerwony i złocistożółty. Czerwone tło odpowiada kolorowi Pantone 186 C (na ekranie ok. #DE2910), a gwiazdy Pantone 012 C (ok. #FFDE00). Czerwień symbolizuje rewolucję, żółć światło oświetlające kraj."},
            {"q": "Kiedy przyjęto flagę Chin?",
             "a": "27 września 1949 roku. Po raz pierwszy wciągnięto ją na maszt na placu Tiananmen w Pekinie 1 października 1949 roku, w dniu proklamowania Chińskiej Republiki Ludowej."},
            {"q": "Kto zaprojektował flagę Chin?",
             "a": "Zeng Liansong, ekonomista i artysta amator z prowincji Zhejiang. Jego projekt zwyciężył w ogólnokrajowym konkursie, na który wpłynęło prawie 3000 zgłoszeń."},
            {"q": "Jakie proporcje ma flaga Chin?",
             "a": "3:2 — flaga jest półtora raza dłuższa niż wyższa."},
            {"q": "Czy mogę bezpłatnie pobrać grafiki flagi z tej strony?",
             "a": "Tak. Każdą ilustrację z galerii można bezpłatnie pobrać jako plik wektorowy SVG lub obraz PNG."},
        ],
    },
    "etiquette": {
        "title": "Flagowanie i Etykieta",
        "text": "Flagę wciąga się na maszt w święta narodowe, szczególnie w Święto Narodowe (1 października) i podczas następującego po nim Złotego Tygodnia, a także przez cały rok na budynkach rządowych, w szkołach i na przejściach granicznych. Nigdy nie może dotykać ziemi, być wciągana do góry nogami ani eksponowana w uszkodzonym lub wyblakłym stanie. W dni żałoby narodowej opuszcza się ją do połowy masztu.",
    },
    "footer": {
        "disclaimer": "Jest to niezależna, nieoficjalna strona informacyjna o fladze Chińskiej Republiki Ludowej. Nie jest powiązana z żadnym rządem, popierana przez niego ani przez niego prowadzona.",
    },
}
