# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Kinas Flagga — Betydelse, Historia och Fakta om den Röda Femstjärniga Flaggan",
        "description": "Kinas flagga förklarad: betydelsen av de fem stjärnorna, historien om den röda femstjärniga flaggan, officiella färger och proportioner, flaggetikett och flaggtema-illustrationer.",
    },
    "brand": "Kinas Flagga",
    "nav": {"meaning": "Betydelse", "history": "Historia", "data": "Teknisk Data", "gallery": "Galleri", "etiquette": "Etikett"},
    "hero": {
        "flag_alt": "Folkrepubliken Kinas flagga — den röda femstjärniga flaggan",
        "title": "Den Röda Femstjärniga Flaggan",
        "subtitle": "Folkrepubliken Kinas nationalflagga",
        "meta": "Antagen 27 september 1949 · Proportion 3:2 · Designer: Zeng Liansong",
    },
    "meaning": {
        "title": "Betydelse och Symbolik",
        "intro": "Designen, antagen 1949, förenar färg, geometri och politisk historia i ett omedelbart igenkännbart emblem.",
        "cards": [
            {"title": "Det Röda Fältet", "text": "Rött står för revolutionen och är också den traditionella färgen för lycka och firande i kinesisk kultur."},
            {"title": "Den Stora Stjärnan", "text": "Den stora gyllene stjärnan representerar Kinas kommunistiska partis ledarskap."},
            {"title": "De Fyra Små Stjärnorna", "text": "De representerar det kinesiska folkets stora enighet under detta ledarskap — traditionellt beskrivna som arbetarklassen, bönderna, den urbana småborgerskapen och den nationella bourgeoisin."},
            {"title": "Stjärnornas Riktning", "text": "Varje liten stjärna har en spets riktad exakt mot den stora stjärnans centrum, vilket symboliserar enighet samlad kring en gemensam medelpunkt."},
            {"title": "Guldgult", "text": "Valt för att lysa strålande mot det röda fältet, en symbol för revolutionens ljus som upplyser landet."},
        ],
    },
    "history": {
        "title": "Historia och Ursprung",
        "items": [
            {"date": "1949", "text": "Den 27 september 1949, några dagar före grundandet av Folkrepubliken Kina, antog Kinesiska folkets politiskt rådgivande konferens formellt den röda femstjärniga flaggan som nationalflagga. Den hissades för första gången över Himmelska fridens torg den 1 oktober 1949, vid ceremonin som proklamerade den nya republiken."},
            {"date": "Design", "text": "Den vinnande designen kom från Zeng Liansong, en ekonom och amatörkonstnär från Zhejiang, som lämnades in under en nationell allmän tävling som samlade nästan 3 000 bidrag. Hans ursprungliga skiss innehöll en hammare och skära inuti den stora stjärnan; urvalskommittén tog bort detta för att hålla designen enkel och skild från andra socialistiska staters emblem."},
            {"date": "2004", "text": "Formella tekniska standarder för flaggans proportioner, stjärngeometri och färger kodifierades i nationella standarder (GB 12982 för konstruktion, GB 15092 för färg)."},
        ],
    },
    "data": {
        "title": "Teknisk Data",
        "ratio": {"title": "Proportioner", "text": "Flaggans längd-till-bredd-förhållande."},
        "grid": {"title": "Konstruktionsraster", "text": "Ett rutnät på 30 × 20 enheter. Den stora stjärnans centrum vid (5,5), ytterradie 3. Små stjärnor, ytterradie 1, centrerade vid (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Färger",
            "red": "Rött — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Gult — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "Den officiella standarden definierar färger med hjälp av fysiska referensprover, inte digitala koder — hexvärden på skärmen är endast ungefärliga.",
        },
        "orientation": {"title": "Stjärnornas Riktningsregel", "text": "Varje liten stjärna är roterad så att en av dess spetsar exakt riktas mot den stora stjärnans centrum."},
    },
    "gallery": {
        "title": "Galleri och Vardagsbruk",
        "intro": "Femstjärnemotivet är inte bara till för flaggstänger — här återges det som vardagsföremål, populära djur och kända sevärdheter, alla i flaggans egna färger rött och guld.",
        "groups": {"objects": "Vardagsföremål", "animals": "Populära Djur i Kina", "landmarks": "Sevärdheter och Kinas Karta"},
        "disclaimer": "Illustrativa bilder skapade för denna sida — inga officiella eller licensierade produkter, och ingen officiell karta.",
        "items": {
            "box": {"text": "Ett Paket i Flaggans Färger", "slug": "kinesisk-flagga-paket"},
            "car": {"text": "En Bil i Flaggans Färger", "slug": "kinesisk-flagga-bil"},
            "phone": {"text": "En Mobil i Flaggans Färger", "slug": "kinesisk-flagga-mobil"},
            "chest": {"text": "En Skattkista i Flaggans Färger", "slug": "kinesisk-flagga-skattkista"},
            "teapot": {"text": "En Tekanna i Flaggans Färger", "slug": "kinesisk-flagga-tekanna"},
            "teacup": {"text": "En Tekopp i Flaggans Färger", "slug": "kinesisk-flagga-tekopp"},
            "umbrella": {"text": "Ett Paraply i Flaggans Färger", "slug": "kinesisk-flagga-paraply"},
            "fan": {"text": "En Solfjäder i Flaggans Färger", "slug": "kinesisk-flagga-solfjader"},
            "lantern": {"text": "En Lykta i Flaggans Färger", "slug": "kinesisk-flagga-lykta"},
            "bicycle": {"text": "En Cykel i Flaggans Färger", "slug": "kinesisk-flagga-cykel"},
            "backpack": {"text": "En Ryggsäck i Flaggans Färger", "slug": "kinesisk-flagga-ryggsack"},
            "sneaker": {"text": "En Sneaker i Flaggans Färger", "slug": "kinesisk-flagga-sneaker"},
            "bird": {"text": "En Fågel i Flaggans Form", "slug": "kinesisk-flagga-fagel"},
            "dragon": {"text": "En Drake i Flaggans Form", "slug": "kinesisk-flagga-drake"},
            "dog": {"text": "En Hund i Flaggans Form", "slug": "kinesisk-flagga-hund"},
            "snake": {"text": "En Orm i Flaggans Form", "slug": "kinesisk-flagga-orm"},
            "panda": {"text": "En Panda i Flaggans Form", "slug": "kinesisk-flagga-panda"},
            "tiger": {"text": "En Tiger i Flaggans Form", "slug": "kinesisk-flagga-tiger"},
            "rabbit": {"text": "En Kanin i Flaggans Form", "slug": "kinesisk-flagga-kanin"},
            "ox": {"text": "En Oxe i Flaggans Form", "slug": "kinesisk-flagga-oxe"},
            "horse": {"text": "En Häst i Flaggans Form", "slug": "kinesisk-flagga-hast"},
            "monkey": {"text": "En Apa i Flaggans Form", "slug": "kinesisk-flagga-apa"},
            "rooster": {"text": "En Tupp i Flaggans Form", "slug": "kinesisk-flagga-tupp"},
            "koi": {"text": "En Koikarp i Flaggans Form", "slug": "kinesisk-flagga-koikarp"},
            "map": {"text": "Kinas Konturer i Flaggans Färger", "slug": "kinesisk-flagga-kinas-konturer"},
            "greatwall": {"text": "Kinesiska Muren i Flaggans Färger", "slug": "kinesisk-flagga-kinesiska-muren"},
            "forbiddencity": {"text": "Förbjudna Staden i Flaggans Färger", "slug": "kinesisk-flagga-forbjudna-staden"},
            "templeofheaven": {"text": "Himmelstemplet i Flaggans Färger", "slug": "kinesisk-flagga-himmelstemplet"},
            "terracotta": {"text": "En Terrakottakrigare i Flaggans Färger", "slug": "kinesisk-flagga-terrakottakrigare"},
            "pearltower": {"text": "Pearl Tower i Flaggans Färger", "slug": "kinesisk-flagga-pearltower"},
            "potala": {"text": "Potalapalatset i Flaggans Färger", "slug": "kinesisk-flagga-potalapalatset"},
            "guilin": {"text": "Guilins Karstberg i Flaggans Färger", "slug": "kinesisk-flagga-guilins-karstberg"},
            "pagoda": {"text": "Vildgåspagoden i Flaggans Färger", "slug": "kinesisk-flagga-vildgaspagoden"},
        },
    },
    "download": {
        "svg": "Ladda ner {name} som SVG",
        "png": "Ladda ner {name} som PNG",
    },
    "etiquette": {
        "title": "Flaggning och Etikett",
        "text": "Flaggan hissas på nationella helgdagar, särskilt nationaldagen (1 oktober) och den efterföljande Gyllene veckan, samt året runt vid myndighetsbyggnader, skolor och gränsövergångar. Den får aldrig vidröra marken, hissas upp och ner eller visas skadad eller blekt. På nationella sorgedagar hissas den på halv stång.",
    },
    "footer": {
        "disclaimer": "Detta är en oberoende, inofficiell informationswebbplats om Folkrepubliken Kinas flagga. Den är inte kopplad till, godkänd av eller driven på uppdrag av någon regering.",
    },
}
