# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Drapeau Chinois — Signification, Histoire et Couleurs",
        "description": "Le drapeau chinois expliqué : signification des cinq étoiles, histoire, couleurs et proportions officielles — plus 33 illustrations à télécharger gratuitement.",
    },
    "brand": "Drapeau Chinois",
    "nav": {"meaning": "Signification", "history": "Histoire", "data": "Données Techniques", "gallery": "Galerie", "etiquette": "Étiquette", "faq": "FAQ"},
    "hero": {
        "flag_alt": "Drapeau de la République populaire de Chine — le drapeau rouge aux cinq étoiles",
        "title": "Le Drapeau Rouge aux Cinq Étoiles",
        "subtitle": "Drapeau national de la République populaire de Chine",
        "meta": "Adopté le 27 septembre 1949 · Proportions 3:2 · Concepteur : Zeng Liansong",
    },
    "meaning": {
        "title": "Signification & Symbolisme",
        "intro": "Adopté en 1949, ce design allie couleur, géométrie et histoire politique en un emblème immédiatement reconnaissable.",
        "cards": [
            {"title": "Le Champ Rouge", "text": "Le rouge symbolise la révolution et représente aussi, dans la culture chinoise traditionnelle, la couleur de la bonne fortune et de la fête."},
            {"title": "La Grande Étoile", "text": "La grande étoile dorée représente la direction du Parti communiste chinois."},
            {"title": "Les Quatre Petites Étoiles", "text": "Elles représentent la grande unité du peuple chinois sous cette direction — traditionnellement décrites comme la classe ouvrière, la paysannerie, la petite bourgeoisie urbaine et la bourgeoisie nationale."},
            {"title": "Orientation des Étoiles", "text": "Chaque petite étoile a une pointe dirigée précisément vers le centre de la grande étoile, symbolisant l'unité rassemblée autour d'un centre commun."},
            {"title": "Le Jaune Doré", "text": "Choisi pour ressortir avec éclat sur le champ rouge, symbolisant la lumière de la révolution illuminant le pays."},
        ],
    },
    "history": {
        "title": "Histoire & Origine",
        "items": [
            {"date": "1949", "text": "Le 27 septembre 1949, quelques jours avant la fondation de la République populaire de Chine, la Conférence consultative politique du peuple chinois a officiellement adopté le drapeau rouge aux cinq étoiles comme drapeau national. Il fut hissé pour la première fois sur la place Tian'anmen le 1er octobre 1949, lors de la cérémonie proclamant la nouvelle république."},
            {"date": "Conception", "text": "Le design gagnant est l'œuvre de Zeng Liansong, un économiste et artiste amateur originaire du Zhejiang, soumis lors d'un concours public national qui a réuni près de 3 000 candidatures. Son esquisse originale comportait un marteau et une faucille à l'intérieur de la grande étoile ; le comité de sélection les a retirés pour garder un design simple et distinct des emblèmes d'autres États socialistes."},
            {"date": "2004", "text": "Des normes techniques officielles concernant les proportions du drapeau, la géométrie des étoiles et les couleurs ont été codifiées dans des normes nationales (GB 12982 pour la construction, GB 15092 pour la couleur)."},
        ],
    },
    "data": {
        "title": "Données Techniques",
        "ratio": {"title": "Proportions", "text": "Rapport longueur/largeur du drapeau."},
        "grid": {"title": "Grille de Construction", "text": "Une grille de 30 × 20 unités. Centre de la grande étoile en (5,5), rayon extérieur 3. Petites étoiles, rayon extérieur 1, centrées en (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Couleurs",
            "red": "Rouge — Pantone 186 C · RVB 222,41,16 · #DE2910",
            "yellow": "Jaune — Pantone 012 C · RVB 255,222,0 · #FFDE00",
            "note": "La norme officielle définit les couleurs à l'aide d'échantillons physiques de référence, et non de codes numériques — les valeurs hexadécimales à l'écran ne sont que des approximations.",
        },
        "orientation": {"title": "Règle d'Orientation des Étoiles", "text": "Chaque petite étoile est tournée de sorte qu'une de ses pointes s'aligne exactement sur le centre de la grande étoile."},
    },
    "gallery": {
        "title": "Galerie & Usage Quotidien",
        "intro": "Le motif des cinq étoiles n'est pas réservé aux mâts — ici, il est réinventé sous forme d'objets du quotidien, d'animaux appréciés et de sites célèbres, tous représentés dans le rouge et l'or du drapeau.",
        "groups": {"objects": "Objets du Quotidien", "animals": "Animaux Populaires en Chine", "landmarks": "Monuments & la Carte de la Chine"},
        "disclaimer": "Illustrations créées pour ce site — il ne s'agit pas de produits officiels ou sous licence, ni d'une carte officielle.",
        "license": "Licence des images : toutes les illustrations de drapeaux de cette page peuvent être téléchargées et utilisées gratuitement, y compris à des fins commerciales. Une attribution (lien vers china-flag.cn) est appréciée mais pas obligatoire.",
        "items": {
            "box": {"text": "Drapeau Chinois en Forme de Paquet", "slug": "drapeau-chinois-paquet"},
            "car": {"text": "Drapeau Chinois en Forme de Voiture", "slug": "drapeau-chinois-voiture"},
            "phone": {"text": "Drapeau Chinois en Forme de Smartphone", "slug": "drapeau-chinois-smartphone"},
            "chest": {"text": "Drapeau Chinois en Forme de Coffre au Trésor", "slug": "drapeau-chinois-coffre-au-tresor"},
            "teapot": {"text": "Drapeau Chinois en Forme de Théière", "slug": "drapeau-chinois-theiere"},
            "teacup": {"text": "Drapeau Chinois en Forme de Tasse à Thé", "slug": "drapeau-chinois-tasse-a-the"},
            "umbrella": {"text": "Drapeau Chinois en Forme de Parapluie", "slug": "drapeau-chinois-parapluie"},
            "fan": {"text": "Drapeau Chinois en Forme d'Éventail", "slug": "drapeau-chinois-eventail"},
            "lantern": {"text": "Drapeau Chinois en Forme de Lanterne", "slug": "drapeau-chinois-lanterne"},
            "bicycle": {"text": "Drapeau Chinois en Forme de Vélo", "slug": "drapeau-chinois-velo"},
            "backpack": {"text": "Drapeau Chinois en Forme de Sac à Dos", "slug": "drapeau-chinois-sac-a-dos"},
            "sneaker": {"text": "Drapeau Chinois en Forme de Basket", "slug": "drapeau-chinois-basket"},
            "bird": {"text": "Drapeau Chinois en Forme d'Oiseau", "slug": "drapeau-chinois-oiseau"},
            "dragon": {"text": "Drapeau Chinois en Forme de Dragon", "slug": "drapeau-chinois-dragon"},
            "dog": {"text": "Drapeau Chinois en Forme de Chien", "slug": "drapeau-chinois-chien"},
            "snake": {"text": "Drapeau Chinois en Forme de Serpent", "slug": "drapeau-chinois-serpent"},
            "panda": {"text": "Drapeau Chinois en Forme de Panda", "slug": "drapeau-chinois-panda"},
            "tiger": {"text": "Drapeau Chinois en Forme de Tigre", "slug": "drapeau-chinois-tigre"},
            "rabbit": {"text": "Drapeau Chinois en Forme de Lapin", "slug": "drapeau-chinois-lapin"},
            "ox": {"text": "Drapeau Chinois en Forme de Bœuf", "slug": "drapeau-chinois-boeuf"},
            "horse": {"text": "Drapeau Chinois en Forme de Cheval", "slug": "drapeau-chinois-cheval"},
            "monkey": {"text": "Drapeau Chinois en Forme de Singe", "slug": "drapeau-chinois-singe"},
            "rooster": {"text": "Drapeau Chinois en Forme de Coq", "slug": "drapeau-chinois-coq"},
            "koi": {"text": "Drapeau Chinois en Forme de Carpe Koï", "slug": "drapeau-chinois-carpe-koi"},
            "map": {"text": "Drapeau Chinois en Forme de Contour de la Chine", "slug": "drapeau-chinois-contour-de-la-chine"},
            "greatwall": {"text": "Drapeau Chinois en Forme de Grande Muraille", "slug": "drapeau-chinois-grande-muraille"},
            "forbiddencity": {"text": "Drapeau Chinois en Forme de Cité Interdite", "slug": "drapeau-chinois-cite-interdite"},
            "templeofheaven": {"text": "Drapeau Chinois en Forme de Temple du Ciel", "slug": "drapeau-chinois-temple-du-ciel"},
            "terracotta": {"text": "Drapeau Chinois en Forme de Guerrier en Terre Cuite", "slug": "drapeau-chinois-guerrier-en-terre-cuite"},
            "pearltower": {"text": "Drapeau Chinois en Forme de Tour de la Perle Orientale", "slug": "drapeau-chinois-tour-de-la-perle-orientale"},
            "potala": {"text": "Drapeau Chinois en Forme de Palais du Potala", "slug": "drapeau-chinois-palais-du-potala"},
            "guilin": {"text": "Drapeau Chinois en Forme de Monts Karstiques de Guilin", "slug": "drapeau-chinois-monts-karstiques-de-guilin"},
            "pagoda": {"text": "Drapeau Chinois en Forme de Pagode de la Grande Oie Sauvage", "slug": "drapeau-chinois-pagode-de-la-grande-oie-sauvage"},
        },
    },
    "download": {
        "svg": "Télécharger « {name} » en SVG",
        "png": "Télécharger « {name} » en PNG",
    },
    "consent": {
        "text": "Nous souhaitons mesurer l'utilisation de ce site avec Google Analytics. Les cookies statistiques ne sont déposés qu'avec votre accord.",
        "accept": "Accepter",
        "decline": "Refuser",
        "settings": "Paramètres des cookies",
    },
    "faq": {
        "title": "Questions Fréquentes",
        "items": [
            {"q": "Que signifient les cinq étoiles du drapeau chinois ?",
             "a": "La grande étoile dorée représente la direction du Parti communiste chinois, et les quatre petites étoiles la grande unité du peuple chinois. Chaque petite étoile a une pointe dirigée précisément vers le centre de la grande étoile."},
            {"q": "Quelles sont les couleurs du drapeau chinois ?",
             "a": "Rouge et jaune doré. Le champ rouge correspond au Pantone 186 C (environ #DE2910 à l'écran), les étoiles au Pantone 012 C (environ #FFDE00). Le rouge symbolise la révolution, le jaune la lumière qui illumine le pays."},
            {"q": "Quand le drapeau chinois a-t-il été adopté ?",
             "a": "Le 27 septembre 1949. Il a été hissé pour la première fois sur la place Tian'anmen à Pékin le 1er octobre 1949, jour de la proclamation de la République populaire de Chine."},
            {"q": "Qui a conçu le drapeau chinois ?",
             "a": "Zeng Liansong, un économiste et artiste amateur de la province du Zhejiang. Son projet a remporté un concours national réunissant près de 3 000 propositions."},
            {"q": "Quel est le rapport de proportions du drapeau chinois ?",
             "a": "3:2 — le drapeau est une fois et demie plus long que haut."},
            {"q": "Puis-je télécharger gratuitement les images du drapeau sur ce site ?",
             "a": "Oui. Chaque illustration de la galerie peut être téléchargée gratuitement au format vectoriel SVG ou en image PNG."},
        ],
    },
    "etiquette": {
        "title": "Usage & Étiquette",
        "text": "Le drapeau est hissé lors des fêtes nationales, en particulier la Fête nationale (1er octobre) et la Golden Week qui suit, ainsi que toute l'année sur les bâtiments gouvernementaux, les écoles et les postes frontières. Il ne doit jamais toucher le sol, être hissé à l'envers, ni être affiché endommagé ou décoloré. Les jours de deuil national, il est mis en berne.",
    },
    "footer": {
        "disclaimer": "Ce site est un site d'information indépendant et non officiel sur le drapeau de la République populaire de Chine. Il n'est affilié à aucun gouvernement, ni approuvé ou exploité en son nom.",
    },
}
