# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "中国国旗——含义、历史与五星红旗知识 | China Flag",
        "description": "深入了解中华人民共和国国旗:五颗星的含义、五星红旗的历史、官方颜色与比例、悬挂礼仪,以及国旗主题插画。",
    },
    "brand": "中国国旗",
    "nav": {"meaning": "含义", "history": "历史", "data": "技术数据", "gallery": "图库", "etiquette": "礼仪", "faq": "常见问题"},
    "hero": {
        "flag_alt": "中华人民共和国国旗——五星红旗",
        "title": "五星红旗",
        "subtitle": "中华人民共和国国旗",
        "meta": "1949年9月27日通过 · 长宽比 3:2 · 设计者:曾联松",
    },
    "meaning": {
        "title": "含义与象征",
        "intro": "五星红旗诞生于1949年,其设计融合了色彩、几何与历史,凝练成一面辨识度极高的国旗。",
        "cards": [
            {"title": "红色底色", "text": "红色象征革命,同时也是中国传统文化中喜庆与吉祥的颜色。"},
            {"title": "大五角星", "text": "大五角星象征中国共产党的领导。"},
            {"title": "四颗小星", "text": "象征在中国共产党领导下全国人民的大团结——传统上分别代表工人阶级、农民阶级、城市小资产阶级和民族资产阶级。"},
            {"title": "星的朝向", "text": "每颗小星均有一角正对大星中心,象征紧密团结、众星拱月。"},
            {"title": "金黄色", "text": "在红色底色上熠熠生辉,象征革命光芒普照大地。"},
        ],
    },
    "history": {
        "title": "历史与起源",
        "items": [
            {"date": "1949", "text": "1949年9月27日,在中华人民共和国成立前夕,中国人民政治协商会议第一届全体会议正式通过五星红旗为国旗。同年10月1日,在开国大典上,五星红旗首次在天安门广场升起。"},
            {"date": "设计", "text": "获选设计出自浙江籍经济学家、业余美术爱好者曾联松之手。当时面向全国征集国旗图案,共收到近3000件应征稿。他最初的设计在大星内绘有镰刀锤子图案,评选委员会为使图案更简洁、并与其他社会主义国家的徽记有所区别,将其移除。"},
            {"date": "2004", "text": "国家标准(GB 12982 关于制法,GB 15092 关于色彩)对国旗的比例、五星的几何构造及颜色作出了正式规定。"},
        ],
    },
    "data": {
        "title": "技术数据",
        "ratio": {"title": "比例", "text": "旗面长与高之比。"},
        "grid": {"title": "制图网格", "text": "旗面划分为30×20单位网格。大星圆心(5,5),外接圆半径3;四颗小星外接圆半径1,圆心分别为(10,2)、(12,4)、(12,7)、(10,9)。"},
        "colors": {
            "title": "颜色",
            "red": "红色——潘通186C · RGB 222,41,16 · #DE2910",
            "yellow": "黄色——潘通012C · RGB 255,222,0 · #FFDE00",
            "note": "国家标准以实物色样而非数字色值定义颜色,因此屏幕显示的十六进制值仅为近似值。",
        },
        "orientation": {"title": "星的朝向规则", "text": "每颗小星的其中一角均精确指向大星中心。"},
    },
    "gallery": {
        "title": "图库与日常应用",
        "intro": "五星红旗的元素不仅限于旗杆之上——在这里,我们用国旗本身的红与金,重新演绎出日常物品、人气动物与著名景点的造型。",
        "groups": {"objects": "日常物品", "animals": "中国人气动物", "landmarks": "地标名胜与中国地图"},
        "disclaimer": "以上为本站制作的示意图,并非官方或授权产品,亦非官方地图。",
        "license": "图片许可:本页所有国旗插画均可免费下载和使用,包括商业用途。欢迎注明出处(链接至 china-flag.cn),但并非必须。",
        "items": {
            "box": {"text": "包裹造型的中国国旗", "slug": "qizhi-peise-de-baoguo"},
            "car": {"text": "汽车造型的中国国旗", "slug": "qizhi-peise-de-qiche"},
            "phone": {"text": "手机造型的中国国旗", "slug": "qizhi-peise-de-shouji"},
            "chest": {"text": "宝箱造型的中国国旗", "slug": "qizhi-peise-de-baoxiang"},
            "teapot": {"text": "茶壶造型的中国国旗", "slug": "qizhi-peise-de-chahu"},
            "teacup": {"text": "茶杯造型的中国国旗", "slug": "qizhi-peise-de-chabei"},
            "umbrella": {"text": "雨伞造型的中国国旗", "slug": "qizhi-peise-de-yusan"},
            "fan": {"text": "扇子造型的中国国旗", "slug": "qizhi-peise-de-shanzi"},
            "lantern": {"text": "灯笼造型的中国国旗", "slug": "qizhi-peise-de-denglong"},
            "bicycle": {"text": "自行车造型的中国国旗", "slug": "qizhi-peise-de-zixingche"},
            "backpack": {"text": "背包造型的中国国旗", "slug": "qizhi-peise-de-beibao"},
            "sneaker": {"text": "运动鞋造型的中国国旗", "slug": "qizhi-peise-de-yundongxie"},
            "bird": {"text": "小鸟造型的中国国旗", "slug": "qizhi-zaoxing-de-xiaoniao"},
            "dragon": {"text": "龙造型的中国国旗", "slug": "qizhi-zaoxing-de-long"},
            "dog": {"text": "小狗造型的中国国旗", "slug": "qizhi-zaoxing-de-xiaogou"},
            "snake": {"text": "蛇造型的中国国旗", "slug": "qizhi-zaoxing-de-she"},
            "panda": {"text": "熊猫造型的中国国旗", "slug": "qizhi-zaoxing-de-xiongmao"},
            "tiger": {"text": "老虎造型的中国国旗", "slug": "qizhi-zaoxing-de-laohu"},
            "rabbit": {"text": "兔子造型的中国国旗", "slug": "qizhi-zaoxing-de-tuzi"},
            "ox": {"text": "牛造型的中国国旗", "slug": "qizhi-zaoxing-de-niu"},
            "horse": {"text": "马造型的中国国旗", "slug": "qizhi-zaoxing-de-ma"},
            "monkey": {"text": "猴子造型的中国国旗", "slug": "qizhi-zaoxing-de-houzi"},
            "rooster": {"text": "公鸡造型的中国国旗", "slug": "qizhi-zaoxing-de-gongji"},
            "koi": {"text": "锦鲤造型的中国国旗", "slug": "qizhi-zaoxing-de-jinli"},
            "map": {"text": "中国轮廓造型的中国国旗", "slug": "qizhi-peise-de-zhongguo-lunkuo"},
            "greatwall": {"text": "长城造型的中国国旗", "slug": "qizhi-peise-de-changcheng"},
            "forbiddencity": {"text": "故宫造型的中国国旗", "slug": "qizhi-peise-de-gugong"},
            "templeofheaven": {"text": "天坛造型的中国国旗", "slug": "qizhi-peise-de-tiantan"},
            "terracotta": {"text": "兵马俑造型的中国国旗", "slug": "qizhi-peise-de-bingmayong"},
            "pearltower": {"text": "东方明珠塔造型的中国国旗", "slug": "qizhi-peise-de-dongfang-mingzhu-ta"},
            "potala": {"text": "布达拉宫造型的中国国旗", "slug": "qizhi-peise-de-budala-gong"},
            "guilin": {"text": "桂林山水造型的中国国旗", "slug": "qizhi-peise-de-guilin-shanshui"},
            "pagoda": {"text": "大雁塔造型的中国国旗", "slug": "qizhi-peise-de-dayan-ta"},
        },
    },
    "download": {
        "svg": "下载「{name}」SVG图片",
        "png": "下载「{name}」PNG图片",
    },
    "consent": {
        "text": "我们希望使用 Google Analytics 统计本站的访问情况。只有在您同意后,才会设置统计 Cookie。",
        "accept": "同意",
        "decline": "拒绝",
        "settings": "Cookie 设置",
    },
    "faq": {
        "title": "常见问题",
        "items": [
            {"q": "中国国旗上的五颗星代表什么?",
             "a": "大五角星象征中国共产党的领导,四颗小星象征全国人民的大团结。每颗小星均有一角正对大星的中心。"},
            {"q": "中国国旗有哪些颜色?",
             "a": "红色和金黄色。旗面红色约为潘通186C(屏幕近似值 #DE2910),五角星为潘通012C(约 #FFDE00)。红色象征革命,黄色象征普照大地的光明。"},
            {"q": "中国国旗是什么时候确定的?",
             "a": "1949年9月27日正式通过,并于1949年10月1日开国大典当天首次在北京天安门广场升起。"},
            {"q": "中国国旗是谁设计的?",
             "a": "浙江人曾联松,一位经济工作者和业余美术爱好者。他的设计在全国征集的近3000件应征作品中脱颖而出。"},
            {"q": "中国国旗的长宽比是多少?",
             "a": "3:2,即旗面长度为高度的1.5倍。"},
            {"q": "本站的国旗图片可以免费下载吗?",
             "a": "可以。图库中的每幅插画都可免费下载为SVG矢量文件或PNG图片。"},
        ],
    },
    "etiquette": {
        "title": "悬挂与礼仪",
        "text": "国旗在国庆节(10月1日)及随后的黄金周等重要节日悬挂,并常年悬挂于政府机关、学校及口岸等场所。国旗不得触地、不得倒挂,亦不得使用破损、褪色的旗帜。在全国哀悼日,应下半旗志哀。",
    },
    "footer": {
        "disclaimer": "本网站为关于中华人民共和国国旗的独立、非官方资讯网站,与任何政府机构均无关联,亦未获其认可或代表其运营。",
    },
}
