# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Bendera Tiongkok — Arti, Sejarah, dan Warna",
        "description": "Bendera Tiongkok dijelaskan: arti lima bintang, sejarah, warna dan proporsi resmi — plus 33 ilustrasi yang dapat diunduh gratis.",
    },
    "brand": "Bendera Tiongkok",
    "nav": {"meaning": "Arti", "history": "Sejarah", "data": "Data Teknis", "gallery": "Galeri", "etiquette": "Etiket", "faq": "FAQ", "historic": "Bendera Bersejarah", "coloring": "Mewarnai"},
    "hero": {
        "flag_alt": "Bendera Republik Rakyat Tiongkok — Bendera Merah Lima Bintang",
        "title": "Bendera Merah Lima Bintang",
        "subtitle": "Bendera nasional Republik Rakyat Tiongkok",
        "meta": "Ditetapkan 27 September 1949 · Rasio 3:2 · Perancang: Zeng Liansong",
    },
    "meaning": {
        "title": "Arti dan Simbolisme",
        "intro": "Desain yang ditetapkan pada 1949 ini memadukan warna, geometri, dan sejarah politik menjadi satu lambang yang langsung dikenali.",
        "cards": [
            {"title": "Latar Merah", "text": "Merah melambangkan revolusi, sekaligus warna tradisional keberuntungan dan perayaan dalam budaya Tionghoa."},
            {"title": "Bintang Besar", "text": "Bintang emas besar melambangkan kepemimpinan Partai Komunis Tiongkok."},
            {"title": "Empat Bintang Kecil", "text": "Melambangkan persatuan besar rakyat Tiongkok di bawah kepemimpinan itu — secara tradisional digambarkan sebagai kelas pekerja, kaum tani, borjuis kecil perkotaan, dan borjuis nasional."},
            {"title": "Arah Bintang", "text": "Setiap bintang kecil memiliki satu ujung yang mengarah tepat ke pusat bintang besar, melambangkan persatuan yang berhimpun pada satu pusat bersama."},
            {"title": "Kuning Emas", "text": "Dipilih agar tampil cemerlang di atas latar merah, melambangkan cahaya revolusi yang menerangi negeri."},
        ],
    },
    "history": {
        "title": "Sejarah dan Asal-Usul",
        "items": [
            {"date": "1949", "text": "Pada 27 September 1949, beberapa hari sebelum berdirinya Republik Rakyat Tiongkok, Konferensi Permusyawaratan Politik Rakyat Tiongkok secara resmi menetapkan Bendera Merah Lima Bintang sebagai bendera nasional. Bendera ini pertama kali dikibarkan di Lapangan Tiananmen pada 1 Oktober 1949, saat upacara proklamasi republik baru."},
            {"date": "Desain", "text": "Desain pemenang berasal dari Zeng Liansong, seorang ekonom dan seniman amatir dari Zhejiang, yang diajukan dalam sayembara nasional dengan hampir 3.000 karya. Sketsa awalnya memuat palu arit di dalam bintang besar; panitia seleksi menghapusnya agar desain tetap sederhana dan berbeda dari lambang negara sosialis lainnya."},
            {"date": "2004", "text": "Standar teknis resmi untuk proporsi bendera, geometri bintang, dan warna dituangkan dalam standar nasional (GB 12982 untuk konstruksi, GB 15092 untuk warna)."},
        ],
    },
    "data": {
        "title": "Data Teknis",
        "ratio": {"title": "Proporsi", "text": "Perbandingan panjang terhadap lebar bendera."},
        "grid": {"title": "Kisi Konstruksi", "text": "Kisi 30 × 20 satuan. Pusat bintang besar di (5,5), jari-jari luar 3. Bintang kecil berjari-jari luar 1, berpusat di (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Warna",
            "red": "Merah — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Kuning — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "Standar resmi mendefinisikan warna dengan contoh fisik, bukan kode digital — nilai heksadesimal di layar hanyalah pendekatan.",
        },
        "orientation": {"title": "Aturan Arah Bintang", "text": "Setiap bintang kecil diputar sehingga salah satu ujungnya tepat segaris dengan pusat bintang besar."},
    },
    "gallery": {
        "title": "Galeri dan Penggunaan Sehari-hari",
        "intro": "Motif lima bintang bukan hanya untuk tiang bendera — di sini ia digubah ulang menjadi benda sehari-hari, hewan kesayangan, dan tempat terkenal, semuanya dalam warna merah dan emas khas bendera.",
        "groups": {"objects": "Benda Sehari-hari", "animals": "Hewan Populer di Tiongkok", "landmarks": "Tempat Terkenal dan Peta Tiongkok"},
        "disclaimer": "Ilustrasi dibuat khusus untuk situs ini — bukan produk resmi atau berlisensi, dan bukan peta resmi.",
        "license": "Lisensi gambar: Semua ilustrasi bendera di halaman ini dapat diunduh dan digunakan secara gratis, termasuk untuk tujuan komersial. Pencantuman sumber (tautan ke china-flag.cn) dihargai tetapi tidak wajib.",
        "items": {
            "box": {"text": "Bendera Tiongkok Berbentuk Paket", "slug": "bendera-tiongkok-paket"},
            "car": {"text": "Bendera Tiongkok Berbentuk Mobil", "slug": "bendera-tiongkok-mobil"},
            "phone": {"text": "Bendera Tiongkok Berbentuk Ponsel", "slug": "bendera-tiongkok-ponsel"},
            "chest": {"text": "Bendera Tiongkok Berbentuk Peti Harta", "slug": "bendera-tiongkok-peti-harta"},
            "teapot": {"text": "Bendera Tiongkok Berbentuk Teko", "slug": "bendera-tiongkok-teko"},
            "teacup": {"text": "Bendera Tiongkok Berbentuk Cangkir Teh", "slug": "bendera-tiongkok-cangkir-teh"},
            "umbrella": {"text": "Bendera Tiongkok Berbentuk Payung", "slug": "bendera-tiongkok-payung"},
            "fan": {"text": "Bendera Tiongkok Berbentuk Kipas Lipat", "slug": "bendera-tiongkok-kipas-lipat"},
            "lantern": {"text": "Bendera Tiongkok Berbentuk Lampion", "slug": "bendera-tiongkok-lampion"},
            "bicycle": {"text": "Bendera Tiongkok Berbentuk Sepeda", "slug": "bendera-tiongkok-sepeda"},
            "backpack": {"text": "Bendera Tiongkok Berbentuk Ransel", "slug": "bendera-tiongkok-ransel"},
            "sneaker": {"text": "Bendera Tiongkok Berbentuk Sepatu Kets", "slug": "bendera-tiongkok-sepatu-kets"},
            "bird": {"text": "Bendera Tiongkok Berbentuk Burung", "slug": "bendera-tiongkok-burung"},
            "dragon": {"text": "Bendera Tiongkok Berbentuk Naga", "slug": "bendera-tiongkok-naga"},
            "dog": {"text": "Bendera Tiongkok Berbentuk Anjing", "slug": "bendera-tiongkok-anjing"},
            "snake": {"text": "Bendera Tiongkok Berbentuk Ular", "slug": "bendera-tiongkok-ular"},
            "panda": {"text": "Bendera Tiongkok Berbentuk Panda", "slug": "bendera-tiongkok-panda"},
            "tiger": {"text": "Bendera Tiongkok Berbentuk Harimau", "slug": "bendera-tiongkok-harimau"},
            "rabbit": {"text": "Bendera Tiongkok Berbentuk Kelinci", "slug": "bendera-tiongkok-kelinci"},
            "ox": {"text": "Bendera Tiongkok Berbentuk Kerbau", "slug": "bendera-tiongkok-kerbau"},
            "horse": {"text": "Bendera Tiongkok Berbentuk Kuda", "slug": "bendera-tiongkok-kuda"},
            "monkey": {"text": "Bendera Tiongkok Berbentuk Monyet", "slug": "bendera-tiongkok-monyet"},
            "rooster": {"text": "Bendera Tiongkok Berbentuk Ayam Jantan", "slug": "bendera-tiongkok-ayam-jantan"},
            "koi": {"text": "Bendera Tiongkok Berbentuk Ikan Koi", "slug": "bendera-tiongkok-ikan-koi"},
            "map": {"text": "Bendera Tiongkok Berbentuk Peta Tiongkok", "slug": "bendera-tiongkok-peta-tiongkok"},
            "greatwall": {"text": "Bendera Tiongkok Berbentuk Tembok Besar", "slug": "bendera-tiongkok-tembok-besar"},
            "forbiddencity": {"text": "Bendera Tiongkok Berbentuk Kota Terlarang", "slug": "bendera-tiongkok-kota-terlarang"},
            "templeofheaven": {"text": "Bendera Tiongkok Berbentuk Kuil Surga", "slug": "bendera-tiongkok-kuil-surga"},
            "terracotta": {"text": "Bendera Tiongkok Berbentuk Prajurit Terakota", "slug": "bendera-tiongkok-prajurit-terakota"},
            "pearltower": {"text": "Bendera Tiongkok Berbentuk Menara Mutiara Timur", "slug": "bendera-tiongkok-menara-mutiara"},
            "potala": {"text": "Bendera Tiongkok Berbentuk Istana Potala", "slug": "bendera-tiongkok-istana-potala"},
            "guilin": {"text": "Bendera Tiongkok Berbentuk Pegunungan Karst Guilin", "slug": "bendera-tiongkok-pegunungan-guilin"},
            "pagoda": {"text": "Bendera Tiongkok Berbentuk Pagoda Angsa Liar", "slug": "bendera-tiongkok-pagoda-angsa-liar"},
        },
    },
    "download": {
        "svg": "Unduh {name} sebagai SVG",
        "png": "Unduh {name} sebagai PNG",
    },
    "historical": {
        "title": "Bendera Bersejarah Tiongkok",
        "intro": "Sebelum Bendera Merah Lima Bintang, Tiongkok mengibarkan panji-panji yang sangat berbeda. Ilustrasi bergaya ini menampilkan tiga pendahulu yang paling terkenal.",
        "items": {
            "qing": {
                "name": "Bendera Naga Qing",
                "period": "1889–1912",
                "text": "Dinasti kekaisaran terakhir mengibarkan bendera kuning keemasan dengan naga biru yang mengejar mutiara merah — kuning adalah warna kaisar.",
                "alt": "Bendera naga dinasti Qing (1889–1912) — ilustrasi bergaya",
                "slug": "bendera-bersejarah-tiongkok-naga-qing",
            },
            "fivecolor": {
                "name": "Bendera Lima Warna",
                "period": "1912–1928",
                "text": "Bendera pertama Republik Tiongkok: lima garis untuk lima bangsa besar Tiongkok — Han, Manchu, Mongol, Hui, dan Tibet.",
                "alt": "Bendera lima warna Republik Tiongkok (1912–1928)",
                "slug": "bendera-bersejarah-tiongkok-lima-warna",
            },
            "bluesky": {
                "name": "Langit Biru, Matahari Putih, Bumi Merah",
                "period": "1928–1949",
                "text": "Bendera nasional era republik di daratan hingga 1949, dengan matahari putih bersinar dua belas pada kanton biru.",
                "alt": "Bendera era Republik Tiongkok (1928–1949) dengan kanton biru dan matahari putih",
                "slug": "bendera-bersejarah-tiongkok-langit-biru-matahari-putih",
            },
        },
    },
    "coloring": {
        "title": "Halaman Mewarnai",
        "text": "Garis bentuk bendera Tiongkok yang dapat dicetak untuk diwarnai — cocok untuk sekolah atau sore yang hujan. Tips: bintang besar dan empat bintang kecil diwarnai kuning emas di atas latar merah.",
        "caption": "Bendera Tiongkok untuk Diwarnai",
        "alt": "Halaman mewarnai bendera Tiongkok — garis bentuk Bendera Merah Lima Bintang yang dapat dicetak",
        "slug": "bendera-tiongkok-halaman-mewarnai",
    },
    "emoji": {
        "title": "Emoji Bendera Tiongkok",
        "text": "Emoji bendera Tiongkok 🇨🇳 terdiri dari dua simbol indikator regional: C (U+1F1E8) dan N (U+1F1F3). Salin di sini dengan sekali klik.",
        "copy": "Salin emoji",
        "copied": "Tersalin!",
        "note": "Di beberapa sistem Windows, emoji ini tampil sebagai huruf “CN” — di ponsel dan sebagian besar perangkat lain, bendera akan muncul.",
    },
    "consent": {
        "text": "Kami ingin mengukur penggunaan situs ini dengan Google Analytics. Cookie statistik hanya dipasang jika Anda setuju.",
        "accept": "Setuju",
        "decline": "Tolak",
        "settings": "Pengaturan cookie",
    },
    "faq": {
        "title": "Pertanyaan yang Sering Diajukan",
        "items": [
            {"q": "Apa arti lima bintang pada bendera Tiongkok?",
             "a": "Bintang emas besar melambangkan kepemimpinan Partai Komunis Tiongkok, dan empat bintang kecil melambangkan persatuan besar rakyat Tiongkok. Setiap bintang kecil memiliki satu ujung yang mengarah tepat ke pusat bintang besar."},
            {"q": "Apa saja warna bendera Tiongkok?",
             "a": "Merah dan kuning emas. Latar merah sesuai Pantone 186 C (di layar sekitar #DE2910), bintang-bintangnya Pantone 012 C (sekitar #FFDE00). Merah melambangkan revolusi, kuning cahaya yang menerangi negeri."},
            {"q": "Kapan bendera Tiongkok ditetapkan?",
             "a": "Pada 27 September 1949. Bendera ini pertama kali dikibarkan di Lapangan Tiananmen, Beijing, pada 1 Oktober 1949, hari proklamasi Republik Rakyat Tiongkok."},
            {"q": "Siapa perancang bendera Tiongkok?",
             "a": "Zeng Liansong, seorang ekonom dan seniman amatir dari Provinsi Zhejiang. Desainnya memenangkan sayembara nasional dengan hampir 3.000 karya."},
            {"q": "Berapa rasio bendera Tiongkok?",
             "a": "3:2 — panjang bendera satu setengah kali tingginya."},
            {"q": "Bolehkah saya mengunduh gambar bendera di situs ini secara gratis?",
             "a": "Ya. Setiap ilustrasi di galeri dapat diunduh gratis sebagai berkas vektor SVG atau gambar PNG."},
        ],
    },
    "etiquette": {
        "title": "Pengibaran dan Etiket",
        "text": "Bendera dikibarkan pada hari libur nasional, terutama Hari Nasional (1 Oktober) dan Pekan Emas sesudahnya, serta sepanjang tahun di gedung pemerintah, sekolah, dan pos perbatasan. Bendera tidak boleh menyentuh tanah, dikibarkan terbalik, atau dipajang dalam keadaan rusak maupun pudar. Pada hari berkabung nasional, bendera dikibarkan setengah tiang.",
    },
    "footer": {
        "disclaimer": "Ini adalah situs informasi independen dan tidak resmi tentang bendera Republik Rakyat Tiongkok. Situs ini tidak berafiliasi dengan, didukung oleh, atau dioperasikan atas nama pemerintah mana pun.",
    },
}
