# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Chinese Flag — Meaning, History & Five-Star Red Flag Facts",
        "description": "The Chinese flag explained: meaning of the five stars, history of the Five-Star Red Flag, official colors & proportions, display etiquette, and flag-themed illustrations.",
    },
    "brand": "China Flag",
    "nav": {"meaning": "Meaning", "history": "History", "data": "Technical Data", "gallery": "Gallery", "etiquette": "Etiquette"},
    "hero": {
        "flag_alt": "Flag of the People's Republic of China — the Five-Star Red Flag",
        "title": "The Five-Star Red Flag",
        "subtitle": "National Flag of the People's Republic of China",
        "meta": "Adopted 27 September 1949 · Ratio 3:2 · Designer: Zeng Liansong",
    },
    "meaning": {
        "title": "Meaning & Symbolism",
        "intro": "Adopted in 1949, the design blends color, geometry and political history into a single, instantly recognizable emblem.",
        "cards": [
            {"title": "The Red Field", "text": "Red stands for revolution, and is also the traditional color of good fortune and celebration in Chinese culture."},
            {"title": "The Large Star", "text": "The large golden star represents the leadership of the Communist Party of China."},
            {"title": "The Four Small Stars", "text": "They represent the great unity of the Chinese people under that leadership — traditionally described as the working class, the peasantry, the urban petty bourgeoisie, and the national bourgeoisie."},
            {"title": "Star Orientation", "text": "Each small star has one point aimed precisely at the center of the large star, symbolizing unity gathered around a common center."},
            {"title": "Golden Yellow", "text": "Chosen to stand out brilliantly against the red field, symbolizing the light of revolution illuminating the country."},
        ],
    },
    "history": {
        "title": "History & Origin",
        "items": [
            {"date": "1949", "text": "On 27 September 1949, days before the founding of the People's Republic of China, the Chinese People's Political Consultative Conference formally adopted the Five-Star Red Flag as the national flag. It was first raised over Tiananmen Square on 1 October 1949, at the ceremony proclaiming the new republic."},
            {"date": "Design", "text": "The winning design came from Zeng Liansong, an economist and amateur artist from Zhejiang, submitted during a nationwide public competition that drew nearly 3,000 entries. His original sketch included a hammer and sickle inside the large star; the selection committee removed it to keep the design simple and distinct from the emblems of other socialist states."},
            {"date": "2004", "text": "Formal technical standards for the flag's proportions, star geometry and colors were codified in national standards (GB 12982 for construction, GB 15092 for color)."},
        ],
    },
    "data": {
        "title": "Technical Data",
        "ratio": {"title": "Proportions", "text": "Length-to-width ratio of the flag."},
        "grid": {"title": "Construction Grid", "text": "A 30 × 20 unit grid. Large star center (5,5), outer radius 3. Small stars, outer radius 1, centered at (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Colors",
            "red": "Red — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Yellow — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "The official standard defines colors using physical reference samples, not digital codes — on-screen hex values are close approximations.",
        },
        "orientation": {"title": "Star Orientation Rule", "text": "Each small star is rotated so that one of its points aligns exactly with the center of the large star."},
    },
    "gallery": {
        "title": "Gallery & Everyday Use",
        "intro": "The five-star motif isn't just for flagpoles — here it's reimagined as everyday shapes, favorite animals and famous sights, all rendered in the flag's own red and gold.",
        "groups": {"objects": "Everyday Objects", "animals": "Animals Popular in China", "landmarks": "Landmarks & the Map of China"},
        "disclaimer": "Illustrative renderings created for this site — not official or licensed products, and not an official map.",
        "items": {
            "box": {"text": "A Package in Flag Colors", "slug": "chinese-flag-shaped-shipping-box"},
            "car": {"text": "A Car in Flag Colors", "slug": "chinese-flag-shaped-car"},
            "phone": {"text": "A Smartphone in Flag Colors", "slug": "chinese-flag-shaped-smartphone"},
            "chest": {"text": "A Treasure Chest in Flag Colors", "slug": "chinese-flag-shaped-treasure-chest"},
            "teapot": {"text": "A Teapot in Flag Colors", "slug": "chinese-flag-shaped-teapot"},
            "teacup": {"text": "A Tea Cup in Flag Colors", "slug": "chinese-flag-shaped-tea-cup"},
            "umbrella": {"text": "An Umbrella in Flag Colors", "slug": "chinese-flag-shaped-umbrella"},
            "fan": {"text": "A Folding Fan in Flag Colors", "slug": "chinese-flag-shaped-folding-fan"},
            "lantern": {"text": "A Lantern in Flag Colors", "slug": "chinese-flag-shaped-red-lantern"},
            "bicycle": {"text": "A Bicycle in Flag Colors", "slug": "chinese-flag-shaped-bicycle"},
            "backpack": {"text": "A Backpack in Flag Colors", "slug": "chinese-flag-shaped-backpack"},
            "sneaker": {"text": "A Sneaker in Flag Colors", "slug": "chinese-flag-shaped-sneaker"},
            "bird": {"text": "A Bird Shaped Like the Flag", "slug": "chinese-flag-shaped-bird"},
            "dragon": {"text": "A Dragon Shaped Like the Flag", "slug": "chinese-flag-shaped-dragon"},
            "dog": {"text": "A Dog Shaped Like the Flag", "slug": "chinese-flag-shaped-dog"},
            "snake": {"text": "A Snake Shaped Like the Flag", "slug": "chinese-flag-shaped-snake"},
            "panda": {"text": "A Panda Shaped Like the Flag", "slug": "chinese-flag-shaped-panda"},
            "tiger": {"text": "A Tiger Shaped Like the Flag", "slug": "chinese-flag-shaped-tiger"},
            "rabbit": {"text": "A Rabbit Shaped Like the Flag", "slug": "chinese-flag-shaped-rabbit"},
            "ox": {"text": "An Ox Shaped Like the Flag", "slug": "chinese-flag-shaped-ox"},
            "horse": {"text": "A Horse Shaped Like the Flag", "slug": "chinese-flag-shaped-horse"},
            "monkey": {"text": "A Monkey Shaped Like the Flag", "slug": "chinese-flag-shaped-monkey"},
            "rooster": {"text": "A Rooster Shaped Like the Flag", "slug": "chinese-flag-shaped-rooster"},
            "koi": {"text": "A Koi Fish Shaped Like the Flag", "slug": "chinese-flag-shaped-koi-fish"},
            "map": {"text": "China's Outline in Flag Colors", "slug": "chinese-flag-shaped-china-map"},
            "greatwall": {"text": "The Great Wall in Flag Colors", "slug": "chinese-flag-shaped-great-wall"},
            "forbiddencity": {"text": "The Forbidden City in Flag Colors", "slug": "chinese-flag-shaped-forbidden-city"},
            "templeofheaven": {"text": "The Temple of Heaven in Flag Colors", "slug": "chinese-flag-shaped-temple-of-heaven"},
            "terracotta": {"text": "A Terracotta Warrior in Flag Colors", "slug": "chinese-flag-shaped-terracotta-warrior"},
            "pearltower": {"text": "The Oriental Pearl Tower in Flag Colors", "slug": "chinese-flag-shaped-oriental-pearl-tower"},
            "potala": {"text": "The Potala Palace in Flag Colors", "slug": "chinese-flag-shaped-potala-palace"},
            "guilin": {"text": "The Guilin Karst Mountains in Flag Colors", "slug": "chinese-flag-shaped-guilin-mountains"},
            "pagoda": {"text": "The Big Wild Goose Pagoda in Flag Colors", "slug": "chinese-flag-shaped-big-wild-goose-pagoda"},
        },
    },
    "etiquette": {
        "title": "Display & Etiquette",
        "text": "The flag is flown on national holidays, especially National Day (1 October) and the ensuing Golden Week, as well as at government buildings, schools and border crossings year-round. It must never touch the ground, be flown upside down, or be displayed in a damaged or faded state. On days of national mourning, it is flown at half-mast.",
    },
    "footer": {
        "disclaimer": "This is an independent, unofficial informational website about the flag of the People's Republic of China. It is not affiliated with, endorsed by, or operated on behalf of any government.",
    },
}
