# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "중국 국기 — 의미, 역사, 색상",
        "description": "중국 국기 해설: 다섯 별의 의미, 역사, 공식 색상과 비율 — 무료로 다운로드할 수 있는 33개의 일러스트 포함.",
    },
    "brand": "중국 국기",
    "nav": {"meaning": "의미", "history": "역사", "data": "기술 정보", "gallery": "갤러리", "etiquette": "게양 예절", "faq": "자주 묻는 질문", "historic": "역대 국기", "coloring": "색칠 도안"},
    "hero": {
        "flag_alt": "중화인민공화국 국기 — 오성홍기",
        "title": "오성홍기",
        "subtitle": "중화인민공화국의 국기",
        "meta": "1949년 9월 27일 제정 · 비율 3:2 · 디자이너: 쩡롄쑹",
    },
    "meaning": {
        "title": "의미와 상징",
        "intro": "1949년에 제정된 이 디자인은 색채, 기하학, 정치사를 하나로 결합해 즉시 알아볼 수 있는 상징이 되었습니다.",
        "cards": [
            {"title": "붉은 바탕", "text": "붉은색은 혁명을 상징하며, 중국 문화에서 행운과 축제를 뜻하는 전통 색이기도 합니다."},
            {"title": "큰 별", "text": "큰 황금별은 중국공산당의 영도를 상징합니다."},
            {"title": "네 개의 작은 별", "text": "그 영도 아래 중국 인민의 대단결을 상징합니다 — 전통적으로 노동자 계급, 농민, 도시 소자산계급, 민족자산계급으로 설명됩니다."},
            {"title": "별의 방향", "text": "작은 별 하나하나의 꼭짓점이 정확히 큰 별의 중심을 향해 있어, 하나의 중심을 둘러싼 단결을 상징합니다."},
            {"title": "황금빛 노랑", "text": "붉은 바탕 위에서 찬란히 빛나도록 선택된 색으로, 나라를 비추는 혁명의 빛을 상징합니다."},
        ],
    },
    "history": {
        "title": "역사와 유래",
        "items": [
            {"date": "1949", "text": "중화인민공화국 수립을 며칠 앞둔 1949년 9월 27일, 중국인민정치협상회의는 오성홍기를 공식 국기로 채택했습니다. 국기는 1949년 10월 1일, 새 공화국 수립을 선포하는 식전에서 톈안먼 광장에 처음 게양되었습니다."},
            {"date": "디자인", "text": "당선작은 저장성 출신의 경제인이자 아마추어 화가인 쩡롄쑹의 작품으로, 약 3,000점이 응모된 전국 공모전에서 선정되었습니다. 초안에는 큰 별 안에 낫과 망치가 그려져 있었으나, 심사위원회는 디자인을 단순하게 하고 다른 사회주의 국가의 상징과 구별하기 위해 이를 삭제했습니다."},
            {"date": "2004", "text": "국기의 비율, 별의 기하학적 구조, 색상에 관한 공식 기술 표준은 국가 표준(제작은 GB 12982, 색상은 GB 15092)으로 명문화되었습니다."},
        ],
    },
    "data": {
        "title": "기술 정보",
        "ratio": {"title": "비율", "text": "국기의 가로세로 비율."},
        "grid": {"title": "제도 격자", "text": "30 × 20 단위의 격자. 큰 별의 중심은 (5,5), 외접원 반지름 3. 작은 별은 외접원 반지름 1이며 중심은 각각 (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "색상",
            "red": "빨강 — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "노랑 — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "공식 표준은 색을 디지털 코드가 아니라 실물 표준 견본으로 정의합니다 — 화면의 16진수 값은 근사치일 뿐입니다.",
        },
        "orientation": {"title": "별 방향 규칙", "text": "작은 별은 각각 꼭짓점 하나가 큰 별의 중심과 정확히 일직선이 되도록 회전되어 있습니다."},
    },
    "gallery": {
        "title": "갤러리와 일상 속 활용",
        "intro": "오성 문양은 깃대 위에만 있는 것이 아닙니다 — 여기서는 일상용품, 사랑받는 동물, 유명 명소의 모습으로 재해석되어 국기 고유의 빨강과 금색으로 표현됩니다.",
        "groups": {"objects": "일상용품", "animals": "중국에서 사랑받는 동물", "landmarks": "명소와 중국 지도"},
        "disclaimer": "이 사이트를 위해 제작된 일러스트입니다 — 공식 제품이나 라이선스 제품이 아니며 공식 지도도 아닙니다.",
        "license": "이미지 라이선스: 이 페이지의 모든 국기 일러스트는 상업적 용도를 포함해 무료로 다운로드하여 사용할 수 있습니다. 출처 표기(china-flag.cn 링크)는 환영하지만 필수는 아닙니다.",
        "items": {
            "box": {"text": "소포 모양의 중국 국기", "slug": "junggug-guggi-sopo"},
            "car": {"text": "자동차 모양의 중국 국기", "slug": "junggug-guggi-jadongcha"},
            "phone": {"text": "스마트폰 모양의 중국 국기", "slug": "junggug-guggi-smartphone"},
            "chest": {"text": "보물상자 모양의 중국 국기", "slug": "junggug-guggi-bomulsangja"},
            "teapot": {"text": "찻주전자 모양의 중국 국기", "slug": "junggug-guggi-chatjujeonja"},
            "teacup": {"text": "찻잔 모양의 중국 국기", "slug": "junggug-guggi-chatjan"},
            "umbrella": {"text": "우산 모양의 중국 국기", "slug": "junggug-guggi-usan"},
            "fan": {"text": "접부채 모양의 중국 국기", "slug": "junggug-guggi-buchae"},
            "lantern": {"text": "홍등 모양의 중국 국기", "slug": "junggug-guggi-hongdeung"},
            "bicycle": {"text": "자전거 모양의 중국 국기", "slug": "junggug-guggi-jajeongeo"},
            "backpack": {"text": "배낭 모양의 중국 국기", "slug": "junggug-guggi-baenang"},
            "sneaker": {"text": "운동화 모양의 중국 국기", "slug": "junggug-guggi-undonghwa"},
            "bird": {"text": "새 모양의 중국 국기", "slug": "junggug-guggi-sae"},
            "dragon": {"text": "용 모양의 중국 국기", "slug": "junggug-guggi-yong"},
            "dog": {"text": "강아지 모양의 중국 국기", "slug": "junggug-guggi-gangaji"},
            "snake": {"text": "뱀 모양의 중국 국기", "slug": "junggug-guggi-baem"},
            "panda": {"text": "판다 모양의 중국 국기", "slug": "junggug-guggi-panda"},
            "tiger": {"text": "호랑이 모양의 중국 국기", "slug": "junggug-guggi-horangi"},
            "rabbit": {"text": "토끼 모양의 중국 국기", "slug": "junggug-guggi-tokki"},
            "ox": {"text": "소 모양의 중국 국기", "slug": "junggug-guggi-so"},
            "horse": {"text": "말 모양의 중국 국기", "slug": "junggug-guggi-mal"},
            "monkey": {"text": "원숭이 모양의 중국 국기", "slug": "junggug-guggi-wonsungi"},
            "rooster": {"text": "수탉 모양의 중국 국기", "slug": "junggug-guggi-sutak"},
            "koi": {"text": "비단잉어 모양의 중국 국기", "slug": "junggug-guggi-bidaningeo"},
            "map": {"text": "중국 지도 모양의 중국 국기", "slug": "junggug-guggi-jido"},
            "greatwall": {"text": "만리장성 모양의 중국 국기", "slug": "junggug-guggi-mallijangseong"},
            "forbiddencity": {"text": "자금성 모양의 중국 국기", "slug": "junggug-guggi-jageumseong"},
            "templeofheaven": {"text": "천단 모양의 중국 국기", "slug": "junggug-guggi-cheondan"},
            "terracotta": {"text": "병마용 모양의 중국 국기", "slug": "junggug-guggi-byeongmayong"},
            "pearltower": {"text": "동방명주 타워 모양의 중국 국기", "slug": "junggug-guggi-dongbangmyeongju"},
            "potala": {"text": "포탈라궁 모양의 중국 국기", "slug": "junggug-guggi-potallagung"},
            "guilin": {"text": "구이린 카르스트 산 모양의 중국 국기", "slug": "junggug-guggi-guilin-san"},
            "pagoda": {"text": "대안탑 모양의 중국 국기", "slug": "junggug-guggi-daeantap"},
        },
    },
    "download": {
        "svg": "{name} SVG로 다운로드",
        "png": "{name} PNG로 다운로드",
    },
    "historical": {
        "title": "중국의 역대 국기",
        "intro": "오성홍기 이전의 중국에는 전혀 다른 깃발이 휘날렸습니다. 이 양식화된 일러스트는 가장 잘 알려진 세 개의 이전 국기를 보여줍니다.",
        "items": {
            "qing": {
                "name": "청나라 황룡기",
                "period": "1889–1912",
                "text": "마지막 황조는 붉은 여의주를 쫓는 푸른 용이 그려진 황금빛 노란 깃발을 사용했습니다 — 노랑은 황제의 색이었습니다.",
                "alt": "청나라 황룡기(1889–1912) — 양식화된 일러스트",
                "slug": "junggug-yeokdae-guggi-hwangnyonggi",
            },
            "fivecolor": {
                "name": "오색기",
                "period": "1912–1928",
                "text": "중화민국 최초의 국기: 다섯 줄은 중국의 5대 민족인 한족·만주족·몽골족·후이족·티베트족을 상징했습니다.",
                "alt": "중화민국의 오색기(1912–1928)",
                "slug": "junggug-yeokdae-guggi-osaekgi",
            },
            "bluesky": {
                "name": "청천백일만지홍기",
                "period": "1928–1949",
                "text": "1949년까지 본토에서 쓰인 중화민국 시기의 국기로, 파란 캔턴에 열두 갈래 빛의 흰 태양이 그려져 있습니다.",
                "alt": "중화민국 시기 국기(1928–1949), 파란 캔턴과 흰 태양",
                "slug": "junggug-yeokdae-guggi-cheongcheonbaekil",
            },
        },
    },
    "coloring": {
        "title": "색칠 도안",
        "text": "인쇄해서 색칠할 수 있는 중국 국기 윤곽선 도안입니다 — 학교 수업이나 비 오는 오후에 안성맞춤. 팁: 큰 별과 네 개의 작은 별은 붉은 바탕 위에 황금빛 노랑으로 칠합니다.",
        "caption": "중국 국기 색칠 도안",
        "alt": "중국 국기 색칠 도안 — 오성홍기의 인쇄용 윤곽선",
        "slug": "junggug-guggi-saekchil-doan",
    },
    "emoji": {
        "title": "중국 국기 이모지",
        "text": "중국 국기 이모지 🇨🇳는 두 개의 지역 지시 기호 C(U+1F1E8)와 N(U+1F1F3)으로 이루어져 있습니다. 여기서 클릭 한 번으로 복사하세요.",
        "copy": "이모지 복사",
        "copied": "복사됨!",
        "note": "일부 Windows 시스템에서는 이모지가 “CN”이라는 글자로 표시됩니다 — 휴대폰과 대부분의 다른 기기에서는 국기가 나타납니다.",
    },
    "consent": {
        "text": "Google Analytics로 이 사이트의 이용 현황을 측정하고자 합니다. 통계 쿠키는 동의하신 경우에만 설정됩니다.",
        "accept": "동의",
        "decline": "거부",
        "settings": "쿠키 설정",
    },
    "faq": {
        "title": "자주 묻는 질문",
        "items": [
            {"q": "중국 국기의 다섯 별은 무엇을 의미하나요?",
             "a": "큰 황금별은 중국공산당의 영도를, 네 개의 작은 별은 중국 인민의 대단결을 상징합니다. 작은 별 하나하나의 꼭짓점이 정확히 큰 별의 중심을 향해 있습니다."},
            {"q": "중국 국기에는 어떤 색이 쓰이나요?",
             "a": "빨강과 황금빛 노랑입니다. 붉은 바탕은 Pantone 186 C(화면상 약 #DE2910), 별은 Pantone 012 C(약 #FFDE00)에 해당합니다. 빨강은 혁명을, 노랑은 나라를 비추는 빛을 상징합니다."},
            {"q": "중국 국기는 언제 제정되었나요?",
             "a": "1949년 9월 27일입니다. 중화인민공화국 수립이 선포된 1949년 10월 1일, 베이징 톈안먼 광장에 처음 게양되었습니다."},
            {"q": "중국 국기는 누가 디자인했나요?",
             "a": "저장성 출신의 경제인이자 아마추어 화가인 쩡롄쑹입니다. 그의 작품은 약 3,000점이 응모된 전국 공모전에서 당선되었습니다."},
            {"q": "중국 국기의 비율은 어떻게 되나요?",
             "a": "3:2 — 국기의 가로가 세로의 1.5배입니다."},
            {"q": "이 사이트의 국기 이미지를 무료로 다운로드할 수 있나요?",
             "a": "네. 갤러리의 모든 일러스트는 SVG 벡터 파일 또는 PNG 이미지로 무료 다운로드할 수 있습니다."},
        ],
    },
    "etiquette": {
        "title": "게양과 예절",
        "text": "국기는 국경절(10월 1일)과 이어지는 황금연휴 등 국가 기념일에 게양되며, 정부 청사·학교·국경 검문소에서는 연중 게양됩니다. 국기는 땅에 닿아서는 안 되고, 거꾸로 게양하거나 훼손·변색된 상태로 사용해서는 안 됩니다. 국가 애도일에는 조기를 게양합니다.",
    },
    "footer": {
        "disclaimer": "이 사이트는 중화인민공화국 국기에 관한 독립적인 비공식 정보 사이트입니다. 어떠한 정부와도 관련이 없으며, 정부의 승인을 받거나 정부를 대신해 운영되지 않습니다.",
    },
}
