# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Bandila ng Tsina — Kahulugan, Kasaysayan at mga Kulay",
        "description": "Ipinaliwanag ang bandila ng Tsina: kahulugan ng limang bituin, kasaysayan, opisyal na mga kulay at proporsyon — kasama ang 33 ilustrasyong libreng mada-download.",
    },
    "brand": "Bandila ng Tsina",
    "nav": {"meaning": "Kahulugan", "history": "Kasaysayan", "data": "Teknikal na Datos", "gallery": "Galerya", "etiquette": "Etiketa", "faq": "Mga Tanong", "historic": "Makasaysayang Bandila", "coloring": "Pangkulay"},
    "hero": {
        "flag_alt": "Bandila ng People's Republic of China — ang Pulang Bandilang May Limang Bituin",
        "title": "Pulang Bandilang May Limang Bituin",
        "subtitle": "Pambansang bandila ng People's Republic of China",
        "meta": "Pinagtibay noong 27 Setyembre 1949 · Proporsyon 3:2 · Taga-disenyo: Zeng Liansong",
    },
    "meaning": {
        "title": "Kahulugan at Simbolismo",
        "intro": "Pinagtibay noong 1949, pinagsasama ng disenyo ang kulay, heometriya at kasaysayang pampulitika sa isang simbolong agad nakikilala.",
        "cards": [
            {"title": "Ang Pulang Larangan", "text": "Ang pula ay sumisimbolo sa rebolusyon, at ito rin ang tradisyonal na kulay ng suwerte at pagdiriwang sa kulturang Tsino."},
            {"title": "Ang Malaking Bituin", "text": "Ang malaking gintong bituin ay kumakatawan sa pamumuno ng Partido Komunista ng Tsina."},
            {"title": "Ang Apat na Maliliit na Bituin", "text": "Kumakatawan sila sa dakilang pagkakaisa ng mamamayang Tsino sa ilalim ng pamumunong iyon — ayon sa tradisyon: ang uring manggagawa, magsasaka, petiburgesyang panlungsod at pambansang burgesya."},
            {"title": "Direksyon ng mga Bituin", "text": "Bawat maliit na bituin ay may isang dulong nakatutok nang eksakto sa gitna ng malaking bituin — simbolo ng pagkakaisang nakapalibot sa iisang sentro."},
            {"title": "Gintong Dilaw", "text": "Pinili upang kuminang sa pulang larangan — simbolo ng liwanag ng rebolusyong tumatanglaw sa bansa."},
        ],
    },
    "history": {
        "title": "Kasaysayan at Pinagmulan",
        "items": [
            {"date": "1949", "text": "Noong 27 Setyembre 1949, ilang araw bago itatag ang People's Republic of China, pormal na pinagtibay ng Chinese People's Political Consultative Conference ang Pulang Bandilang May Limang Bituin bilang pambansang bandila. Unang iwinagayway ito sa Tiananmen Square noong 1 Oktubre 1949, sa seremonya ng proklamasyon ng bagong republika."},
            {"date": "Disenyo", "text": "Ang nanalong disenyo ay gawa ni Zeng Liansong, isang ekonomista at baguhang artista mula sa Zhejiang, na isinali sa pambansang patimpalak na tinanggap ang halos 3,000 lahok. May karit at maso sa loob ng malaking bituin ang orihinal niyang burador; inalis ito ng komite upang manatiling simple ang disenyo at maiba sa mga sagisag ng ibang bansang sosyalista."},
            {"date": "2004", "text": "Ang mga pormal na teknikal na pamantayan para sa proporsyon ng bandila, heometriya ng mga bituin at mga kulay ay itinakda sa mga pambansang pamantayan (GB 12982 para sa pagbuo, GB 15092 para sa kulay)."},
        ],
    },
    "data": {
        "title": "Teknikal na Datos",
        "ratio": {"title": "Proporsyon", "text": "Ang ratio ng haba sa lapad ng bandila."},
        "grid": {"title": "Grid ng Pagbuo", "text": "Isang grid na 30 × 20 yunit. Gitna ng malaking bituin sa (5,5), panlabas na radius 3. Ang maliliit na bituin ay may panlabas na radius 1, nakasentro sa (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Mga Kulay",
            "red": "Pula — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Dilaw — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "Tinutukoy ng opisyal na pamantayan ang mga kulay gamit ang pisikal na sanggunian, hindi digital na code — ang mga hex value sa screen ay pawang tantiya lamang.",
        },
        "orientation": {"title": "Panuntunan sa Direksyon ng Bituin", "text": "Bawat maliit na bituin ay iniikot upang ang isa sa mga dulo nito ay eksaktong nakahanay sa gitna ng malaking bituin."},
    },
    "gallery": {
        "title": "Galerya at Pang-araw-araw na Gamit",
        "intro": "Ang motif ng limang bituin ay hindi lamang para sa mga poste ng bandila — dito, muling inilarawan ito bilang mga pang-araw-araw na bagay, paboritong hayop at tanyag na tanawin, lahat sa pula at ginto ng mismong bandila.",
        "groups": {"objects": "Pang-araw-araw na Bagay", "animals": "Mga Hayop na Sikat sa Tsina", "landmarks": "Mga Tanawin at ang Mapa ng Tsina"},
        "disclaimer": "Mga ilustrasyong ginawa para sa site na ito — hindi opisyal o lisensyadong produkto, at hindi opisyal na mapa.",
        "license": "Lisensya ng imahe: Lahat ng ilustrasyon ng bandila sa pahinang ito ay maaaring i-download at gamitin nang libre, kabilang ang paggamit na pangkomersyo. Ang pagbanggit ng pinagmulan (link sa china-flag.cn) ay ikinagagalak ngunit hindi kailangan.",
        "items": {
            "box": {"text": "Bandila ng Tsina na Hugis Pakete", "slug": "bandila-ng-tsina-pakete"},
            "car": {"text": "Bandila ng Tsina na Hugis Kotse", "slug": "bandila-ng-tsina-kotse"},
            "phone": {"text": "Bandila ng Tsina na Hugis Smartphone", "slug": "bandila-ng-tsina-smartphone"},
            "chest": {"text": "Bandila ng Tsina na Hugis Baul ng Kayamanan", "slug": "bandila-ng-tsina-baul"},
            "teapot": {"text": "Bandila ng Tsina na Hugis Tsarera", "slug": "bandila-ng-tsina-tsarera"},
            "teacup": {"text": "Bandila ng Tsina na Hugis Tasa ng Tsaa", "slug": "bandila-ng-tsina-tasa"},
            "umbrella": {"text": "Bandila ng Tsina na Hugis Payong", "slug": "bandila-ng-tsina-payong"},
            "fan": {"text": "Bandila ng Tsina na Hugis Pamaypay", "slug": "bandila-ng-tsina-pamaypay"},
            "lantern": {"text": "Bandila ng Tsina na Hugis Parol", "slug": "bandila-ng-tsina-parol"},
            "bicycle": {"text": "Bandila ng Tsina na Hugis Bisikleta", "slug": "bandila-ng-tsina-bisikleta"},
            "backpack": {"text": "Bandila ng Tsina na Hugis Backpack", "slug": "bandila-ng-tsina-backpack"},
            "sneaker": {"text": "Bandila ng Tsina na Hugis Sneaker", "slug": "bandila-ng-tsina-sneaker"},
            "bird": {"text": "Bandila ng Tsina na Hugis Ibon", "slug": "bandila-ng-tsina-ibon"},
            "dragon": {"text": "Bandila ng Tsina na Hugis Dragon", "slug": "bandila-ng-tsina-dragon"},
            "dog": {"text": "Bandila ng Tsina na Hugis Aso", "slug": "bandila-ng-tsina-aso"},
            "snake": {"text": "Bandila ng Tsina na Hugis Ahas", "slug": "bandila-ng-tsina-ahas"},
            "panda": {"text": "Bandila ng Tsina na Hugis Panda", "slug": "bandila-ng-tsina-panda"},
            "tiger": {"text": "Bandila ng Tsina na Hugis Tigre", "slug": "bandila-ng-tsina-tigre"},
            "rabbit": {"text": "Bandila ng Tsina na Hugis Kuneho", "slug": "bandila-ng-tsina-kuneho"},
            "ox": {"text": "Bandila ng Tsina na Hugis Baka", "slug": "bandila-ng-tsina-baka"},
            "horse": {"text": "Bandila ng Tsina na Hugis Kabayo", "slug": "bandila-ng-tsina-kabayo"},
            "monkey": {"text": "Bandila ng Tsina na Hugis Unggoy", "slug": "bandila-ng-tsina-unggoy"},
            "rooster": {"text": "Bandila ng Tsina na Hugis Tandang", "slug": "bandila-ng-tsina-tandang"},
            "koi": {"text": "Bandila ng Tsina na Hugis Isdang Koi", "slug": "bandila-ng-tsina-isdang-koi"},
            "map": {"text": "Bandila ng Tsina na Hugis Mapa ng Tsina", "slug": "bandila-ng-tsina-mapa"},
            "greatwall": {"text": "Bandila ng Tsina na Hugis Great Wall", "slug": "bandila-ng-tsina-great-wall"},
            "forbiddencity": {"text": "Bandila ng Tsina na Hugis Forbidden City", "slug": "bandila-ng-tsina-forbidden-city"},
            "templeofheaven": {"text": "Bandila ng Tsina na Hugis Temple of Heaven", "slug": "bandila-ng-tsina-temple-of-heaven"},
            "terracotta": {"text": "Bandila ng Tsina na Hugis Terracotta Warrior", "slug": "bandila-ng-tsina-terracotta"},
            "pearltower": {"text": "Bandila ng Tsina na Hugis Oriental Pearl Tower", "slug": "bandila-ng-tsina-pearl-tower"},
            "potala": {"text": "Bandila ng Tsina na Hugis Potala Palace", "slug": "bandila-ng-tsina-potala"},
            "guilin": {"text": "Bandila ng Tsina na Hugis Kabundukan ng Guilin", "slug": "bandila-ng-tsina-guilin"},
            "pagoda": {"text": "Bandila ng Tsina na Hugis Wild Goose Pagoda", "slug": "bandila-ng-tsina-pagoda"},
        },
    },
    "download": {
        "svg": "I-download ang {name} bilang SVG",
        "png": "I-download ang {name} bilang PNG",
    },
    "historical": {
        "title": "Mga Makasaysayang Bandila ng Tsina",
        "intro": "Bago ang Pulang Bandilang May Limang Bituin, ibang-iba ang mga watawat na iwinagayway sa Tsina. Ipinapakita ng mga istilisadong ilustrasyong ito ang tatlong pinakakilalang nauna.",
        "items": {
            "qing": {
                "name": "Bandilang Dragon ng Qing",
                "period": "1889–1912",
                "text": "Gumamit ang huling dinastiyang imperyal ng gintong-dilaw na bandila na may asul na dragong humahabol sa pulang perlas — dilaw ang kulay ng emperador.",
                "alt": "Bandilang dragon ng dinastiyang Qing (1889–1912) — istilisadong ilustrasyon",
                "slug": "makasaysayang-bandila-tsina-dragon-qing",
            },
            "fivecolor": {
                "name": "Bandilang May Limang Kulay",
                "period": "1912–1928",
                "text": "Ang unang bandila ng Republika ng Tsina: limang guhit para sa limang dakilang lahi ng Tsina — Han, Manchu, Mongol, Hui at Tibetano.",
                "alt": "Bandilang may limang kulay ng Republika ng Tsina (1912–1928)",
                "slug": "makasaysayang-bandila-tsina-limang-kulay",
            },
            "bluesky": {
                "name": "Asul na Langit, Puting Araw, Pulang Lupa",
                "period": "1928–1949",
                "text": "Ang pambansang bandila ng panahon ng republika sa mainland hanggang 1949, na may puting araw na may labindalawang sinag sa asul na kanton.",
                "alt": "Bandila ng panahon ng Republika ng Tsina (1928–1949) na may asul na kanton at puting araw",
                "slug": "makasaysayang-bandila-tsina-asul-na-langit-puting-araw",
            },
        },
    },
    "coloring": {
        "title": "Pahinang Pangkulay",
        "text": "Isang naipi-print na balangkas ng bandila ng Tsina para kulayan — sakto para sa paaralan o sa maulang hapon. Tip: ang malaking bituin at apat na maliliit na bituin ay kinukulayan ng gintong dilaw sa pulang larangan.",
        "caption": "Bandila ng Tsina na Pangkulay",
        "alt": "Pahinang pangkulay ng bandila ng Tsina — naipi-print na balangkas ng Pulang Bandilang May Limang Bituin",
        "slug": "bandila-ng-tsina-pangkulay",
    },
    "emoji": {
        "title": "Emoji ng Bandila ng Tsina",
        "text": "Ang emoji ng bandila ng Tsina 🇨🇳 ay binubuo ng dalawang regional indicator symbol: C (U+1F1E8) at N (U+1F1F3). Kopyahin ito rito sa isang click.",
        "copy": "Kopyahin ang emoji",
        "copied": "Nakopya!",
        "note": "Sa ilang Windows system, lumalabas ang emoji bilang mga titik na “CN” — sa mga telepono at karamihan ng ibang device, lumilitaw ang bandila.",
    },
    "consent": {
        "text": "Nais naming sukatin ang paggamit ng site na ito gamit ang Google Analytics. Ang statistics cookies ay itatakda lamang kung papayag ka.",
        "accept": "Tanggapin",
        "decline": "Tanggihan",
        "settings": "Mga setting ng cookie",
    },
    "faq": {
        "title": "Mga Madalas Itanong",
        "items": [
            {"q": "Ano ang ibig sabihin ng limang bituin sa bandila ng Tsina?",
             "a": "Ang malaking gintong bituin ay kumakatawan sa pamumuno ng Partido Komunista ng Tsina, at ang apat na maliliit na bituin sa dakilang pagkakaisa ng mamamayang Tsino. Bawat maliit na bituin ay may isang dulong nakatutok nang eksakto sa gitna ng malaking bituin."},
            {"q": "Anong mga kulay mayroon ang bandila ng Tsina?",
             "a": "Pula at gintong dilaw. Ang pulang larangan ay tumutugma sa Pantone 186 C (humigit-kumulang #DE2910 sa screen), ang mga bituin sa Pantone 012 C (humigit-kumulang #FFDE00). Ang pula ay simbolo ng rebolusyon, ang dilaw ng liwanag na tumatanglaw sa bansa."},
            {"q": "Kailan pinagtibay ang bandila ng Tsina?",
             "a": "Noong 27 Setyembre 1949. Unang iwinagayway ito sa Tiananmen Square sa Beijing noong 1 Oktubre 1949, ang araw ng proklamasyon ng People's Republic of China."},
            {"q": "Sino ang nagdisenyo ng bandila ng Tsina?",
             "a": "Si Zeng Liansong, isang ekonomista at baguhang artista mula sa lalawigan ng Zhejiang. Nanalo ang kanyang disenyo sa pambansang patimpalak na may halos 3,000 lahok."},
            {"q": "Ano ang proporsyon ng bandila ng Tsina?",
             "a": "3:2 — ang haba ng bandila ay isa't kalahating beses ng taas nito."},
            {"q": "Maaari ko bang i-download nang libre ang mga larawan ng bandila sa site na ito?",
             "a": "Oo. Bawat ilustrasyon sa galerya ay maaaring i-download nang libre bilang SVG vector file o PNG na larawan."},
        ],
    },
    "etiquette": {
        "title": "Pagwawagayway at Etiketa",
        "text": "Iwinagayway ang bandila tuwing pambansang pista opisyal, lalo na sa Pambansang Araw (1 Oktubre) at sa sumusunod na Golden Week, gayundin nang buong taon sa mga gusali ng pamahalaan, paaralan at hangganan. Hindi ito dapat sumayad sa lupa, iwagayway nang baligtad, o ipakita nang sira o kupas. Sa mga araw ng pambansang pagluluksa, inilaladlad ito nang nakababa (half-mast).",
    },
    "footer": {
        "disclaimer": "Ito ay isang malaya at di-opisyal na website ng impormasyon tungkol sa bandila ng People's Republic of China. Hindi ito kaanib, inendorso o pinapatakbo sa ngalan ng anumang pamahalaan.",
    },
}
