# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "中国国旗 — 意味・歴史・五星紅旗の基礎知識",
        "description": "中国国旗を徹底解説:五つの星の意味、五星紅旗の歴史、公式の色と比率、掲揚のマナー、国旗モチーフのイラスト。",
    },
    "brand": "中国国旗",
    "nav": {"meaning": "意味", "history": "歴史", "data": "技術データ", "gallery": "ギャラリー", "etiquette": "マナー", "faq": "よくある質問"},
    "hero": {
        "flag_alt": "中華人民共和国の国旗——五星紅旗",
        "title": "五星紅旗",
        "subtitle": "中華人民共和国の国旗",
        "meta": "1949年9月27日制定 · 縦横比 3:2 · デザイナー:曾聯松",
    },
    "meaning": {
        "title": "意味と象徴",
        "intro": "1949年に制定されたこのデザインは、色彩、幾何学、そして政治史を一つに融合させた、ひと目でそれとわかる国旗です。",
        "cards": [
            {"title": "赤い旗地", "text": "赤は革命を象徴すると同時に、中国の伝統文化において慶事や幸運を表す色でもあります。"},
            {"title": "大きな星", "text": "大きな金色の星は中国共産党の指導を象徴しています。"},
            {"title": "四つの小さな星", "text": "その指導のもとでの中国人民の大団結を象徴し、伝統的には労働者階級、農民階級、都市小資産階級、民族資産階級を表すとされています。"},
            {"title": "星の向き", "text": "それぞれの小さな星は、その一つの頂点が大きな星の中心を正確に指すように配置されており、共通の中心に結集する団結を象徴しています。"},
            {"title": "金色", "text": "赤い旗地の上で輝くように選ばれた色で、革命の光が国全体を照らすことを象徴しています。"},
        ],
    },
    "history": {
        "title": "歴史と由来",
        "items": [
            {"date": "1949年", "text": "中華人民共和国建国のわずか数日前、1949年9月27日に、中国人民政治協商会議は五星紅旗を正式に国旗として採択しました。同年10月1日、新中国成立を宣言する式典で、五星紅旗は天安門広場に初めて掲げられました。"},
            {"date": "デザイン", "text": "採用されたデザインは、浙江省出身の経済学者でアマチュア画家の曾聯松によるものです。全国規模で行われたデザイン公募には約3000点の応募がありました。彼の当初の草案では大きな星の中に鎌と槌が描かれていましたが、デザインをより簡潔にし、他の社会主義国家の紋章との違いを明確にするため、選考委員会によって取り除かれました。"},
            {"date": "2004年", "text": "国旗の比率、星の幾何学的構造、色彩に関する正式な技術基準は、後に国家標準(制図についてはGB 12982、色彩についてはGB 15092)として明文化されました。"},
        ],
    },
    "data": {
        "title": "技術データ",
        "ratio": {"title": "縦横比", "text": "国旗の縦と横の比率。"},
        "grid": {"title": "制図グリッド", "text": "旗面は30×20単位のグリッドに分割されます。大きな星の中心は(5,5)、外接円半径は3。小さな星は外接円半径1で、中心はそれぞれ(10,2)、(12,4)、(12,7)、(10,9)にあります。"},
        "colors": {
            "title": "色",
            "red": "赤 — パントン186C · RGB 222,41,16 · #DE2910",
            "yellow": "黄 — パントン012C · RGB 255,222,0 · #FFDE00",
            "note": "公式基準では色は数値コードではなく実物の色見本によって定義されているため、画面上の16進数値はあくまで近似値です。",
        },
        "orientation": {"title": "星の向きの規則", "text": "それぞれの小さな星は、その一つの頂点が大きな星の中心と正確に一致するように回転しています。"},
    },
    "gallery": {
        "title": "ギャラリーと日常での活用",
        "intro": "五星紅旗のモチーフは旗竿の上だけのものではありません。ここでは日常の品々、人気の動物、有名な名所を、国旗そのものの赤と金で表現しています。",
        "groups": {"objects": "日常の品々", "animals": "中国で人気の動物", "landmarks": "名所と中国の地図"},
        "disclaimer": "以上はこのサイトのために作成したイメージイラストであり、公式または許諾を受けた製品ではなく、また公式の地図でもありません。",
        "items": {
            "box": {"text": "小包の形をした中国国旗", "slug": "chugoku-kokki-kozutsumi"},
            "car": {"text": "車の形をした中国国旗", "slug": "chugoku-kokki-kuruma"},
            "phone": {"text": "スマートフォンの形をした中国国旗", "slug": "chugoku-kokki-sumaho"},
            "chest": {"text": "宝箱の形をした中国国旗", "slug": "chugoku-kokki-takarabako"},
            "teapot": {"text": "急須の形をした中国国旗", "slug": "chugoku-kokki-kyusu"},
            "teacup": {"text": "湯呑みの形をした中国国旗", "slug": "chugoku-kokki-yunomi"},
            "umbrella": {"text": "傘の形をした中国国旗", "slug": "chugoku-kokki-kasa"},
            "fan": {"text": "扇子の形をした中国国旗", "slug": "chugoku-kokki-sensu"},
            "lantern": {"text": "提灯の形をした中国国旗", "slug": "chugoku-kokki-chochin"},
            "bicycle": {"text": "自転車の形をした中国国旗", "slug": "chugoku-kokki-jitensha"},
            "backpack": {"text": "リュックの形をした中国国旗", "slug": "chugoku-kokki-ryukku"},
            "sneaker": {"text": "スニーカーの形をした中国国旗", "slug": "chugoku-kokki-sunika"},
            "bird": {"text": "鳥の形をした中国国旗", "slug": "chugoku-kokki-tori"},
            "dragon": {"text": "龍の形をした中国国旗", "slug": "chugoku-kokki-ryu"},
            "dog": {"text": "犬の形をした中国国旗", "slug": "chugoku-kokki-inu"},
            "snake": {"text": "蛇の形をした中国国旗", "slug": "chugoku-kokki-hebi"},
            "panda": {"text": "パンダの形をした中国国旗", "slug": "chugoku-kokki-panda"},
            "tiger": {"text": "虎の形をした中国国旗", "slug": "chugoku-kokki-tora"},
            "rabbit": {"text": "ウサギの形をした中国国旗", "slug": "chugoku-kokki-usagi"},
            "ox": {"text": "牛の形をした中国国旗", "slug": "chugoku-kokki-ushi"},
            "horse": {"text": "馬の形をした中国国旗", "slug": "chugoku-kokki-uma"},
            "monkey": {"text": "猿の形をした中国国旗", "slug": "chugoku-kokki-saru"},
            "rooster": {"text": "雄鶏の形をした中国国旗", "slug": "chugoku-kokki-niwatori"},
            "koi": {"text": "鯉の形をした中国国旗", "slug": "chugoku-kokki-koi"},
            "map": {"text": "中国の輪郭をした中国国旗", "slug": "chugoku-kokki-chugoku-rinkaku"},
            "greatwall": {"text": "万里の長城の形をした中国国旗", "slug": "chugoku-kokki-banrinochoujou"},
            "forbiddencity": {"text": "紫禁城の形をした中国国旗", "slug": "chugoku-kokki-shikinjou"},
            "templeofheaven": {"text": "天壇の形をした中国国旗", "slug": "chugoku-kokki-tendan"},
            "terracotta": {"text": "兵馬俑の形をした中国国旗", "slug": "chugoku-kokki-heibayou"},
            "pearltower": {"text": "東方明珠タワーの形をした中国国旗", "slug": "chugoku-kokki-toho-meishu-to"},
            "potala": {"text": "ポタラ宮の形をした中国国旗", "slug": "chugoku-kokki-potala-kyuden"},
            "guilin": {"text": "桂林山水の形をした中国国旗", "slug": "chugoku-kokki-keirin-sansui"},
            "pagoda": {"text": "大雁塔の形をした中国国旗", "slug": "chugoku-kokki-daigan-tou"},
        },
    },
    "download": {
        "svg": "「{name}」をSVGでダウンロード",
        "png": "「{name}」をPNGでダウンロード",
    },
    "consent": {
        "text": "当サイトでは、Google Analyticsを使って利用状況を測定したいと考えています。統計Cookieは、同意いただいた場合にのみ設定されます。",
        "accept": "同意する",
        "decline": "拒否する",
        "settings": "Cookie設定",
    },
    "faq": {
        "title": "よくある質問",
        "items": [
            {"q": "中国国旗の5つの星は何を意味していますか?",
             "a": "大きな金色の星は中国共産党の指導を、4つの小さな星は中国人民の大団結を象徴しています。それぞれの小さな星は、頂点の一つが大きな星の中心を正確に指しています。"},
            {"q": "中国国旗には何色が使われていますか?",
             "a": "赤と金色(黄色)です。旗地の赤はパントン186C(画面上ではおよそ#DE2910)、星はパントン012C(およそ#FFDE00)に相当します。赤は革命を、黄色は国を照らす光を象徴します。"},
            {"q": "中国国旗はいつ制定されましたか?",
             "a": "1949年9月27日です。中華人民共和国の建国が宣言された1949年10月1日に、北京の天安門広場で初めて掲揚されました。"},
            {"q": "中国国旗は誰がデザインしましたか?",
             "a": "浙江省出身の経済学者でアマチュア画家の曾聯松です。約3000点の応募が寄せられた全国公募で彼のデザインが選ばれました。"},
            {"q": "中国国旗の縦横比はいくつですか?",
             "a": "3:2で、旗の長さは高さの1.5倍です。"},
            {"q": "このサイトの国旗画像は無料でダウンロードできますか?",
             "a": "はい。ギャラリーのすべてのイラストは、SVGベクターファイルまたはPNG画像として無料でダウンロードできます。"},
        ],
    },
    "etiquette": {
        "title": "掲揚とマナー",
        "text": "国旗は国慶節(10月1日)とそれに続く黄金週間などの祝日に掲げられるほか、政府機関、学校、国境の出入国拠点などでは一年を通じて掲げられます。地面に触れさせたり、逆さまに掲げたり、破損・色あせした状態で掲げたりしてはいけません。全国哀悼日には半旗が掲げられます。",
    },
    "footer": {
        "disclaimer": "本サイトは中華人民共和国の国旗に関する独立した非公式の情報サイトであり、いかなる政府とも関係がなく、その承認や運営を受けたものでもありません。",
    },
}
