# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Drapeau Chinois — Signification, Histoire et Faits sur le Drapeau Rouge aux Cinq Étoiles",
        "description": "Le drapeau chinois expliqué : signification des cinq étoiles, histoire du drapeau rouge aux cinq étoiles, couleurs et proportions officielles, étiquette et illustrations à thème.",
    },
    "brand": "Drapeau Chinois",
    "nav": {"meaning": "Signification", "history": "Histoire", "data": "Données Techniques", "gallery": "Galerie", "etiquette": "Étiquette"},
    "hero": {
        "flag_alt": "Drapeau de la République populaire de Chine — le drapeau rouge aux cinq étoiles",
        "title": "Le Drapeau Rouge aux Cinq Étoiles",
        "subtitle": "Drapeau national de la République populaire de Chine",
        "meta": "Adopté le 27 septembre 1949 · Proportions 3:2 · Concepteur : Zeng Liansong",
    },
    "meaning": {
        "title": "Signification & Symbolisme",
        "intro": "Adopté en 1949, ce design allie couleur, géométrie et histoire politique en un emblème immédiatement reconnaissable.",
        "cards": [
            {"title": "Le Champ Rouge", "text": "Le rouge symbolise la révolution et représente aussi, dans la culture chinoise traditionnelle, la couleur de la bonne fortune et de la fête."},
            {"title": "La Grande Étoile", "text": "La grande étoile dorée représente la direction du Parti communiste chinois."},
            {"title": "Les Quatre Petites Étoiles", "text": "Elles représentent la grande unité du peuple chinois sous cette direction — traditionnellement décrites comme la classe ouvrière, la paysannerie, la petite bourgeoisie urbaine et la bourgeoisie nationale."},
            {"title": "Orientation des Étoiles", "text": "Chaque petite étoile a une pointe dirigée précisément vers le centre de la grande étoile, symbolisant l'unité rassemblée autour d'un centre commun."},
            {"title": "Le Jaune Doré", "text": "Choisi pour ressortir avec éclat sur le champ rouge, symbolisant la lumière de la révolution illuminant le pays."},
        ],
    },
    "history": {
        "title": "Histoire & Origine",
        "items": [
            {"date": "1949", "text": "Le 27 septembre 1949, quelques jours avant la fondation de la République populaire de Chine, la Conférence consultative politique du peuple chinois a officiellement adopté le drapeau rouge aux cinq étoiles comme drapeau national. Il fut hissé pour la première fois sur la place Tian'anmen le 1er octobre 1949, lors de la cérémonie proclamant la nouvelle république."},
            {"date": "Conception", "text": "Le design gagnant est l'œuvre de Zeng Liansong, un économiste et artiste amateur originaire du Zhejiang, soumis lors d'un concours public national qui a réuni près de 3 000 candidatures. Son esquisse originale comportait un marteau et une faucille à l'intérieur de la grande étoile ; le comité de sélection les a retirés pour garder un design simple et distinct des emblèmes d'autres États socialistes."},
            {"date": "2004", "text": "Des normes techniques officielles concernant les proportions du drapeau, la géométrie des étoiles et les couleurs ont été codifiées dans des normes nationales (GB 12982 pour la construction, GB 15092 pour la couleur)."},
        ],
    },
    "data": {
        "title": "Données Techniques",
        "ratio": {"title": "Proportions", "text": "Rapport longueur/largeur du drapeau."},
        "grid": {"title": "Grille de Construction", "text": "Une grille de 30 × 20 unités. Centre de la grande étoile en (5,5), rayon extérieur 3. Petites étoiles, rayon extérieur 1, centrées en (10,2), (12,4), (12,7), (10,9)."},
        "colors": {
            "title": "Couleurs",
            "red": "Rouge — Pantone 186 C · RVB 222,41,16 · #DE2910",
            "yellow": "Jaune — Pantone 012 C · RVB 255,222,0 · #FFDE00",
            "note": "La norme officielle définit les couleurs à l'aide d'échantillons physiques de référence, et non de codes numériques — les valeurs hexadécimales à l'écran ne sont que des approximations.",
        },
        "orientation": {"title": "Règle d'Orientation des Étoiles", "text": "Chaque petite étoile est tournée de sorte qu'une de ses pointes s'aligne exactement sur le centre de la grande étoile."},
    },
    "gallery": {
        "title": "Galerie & Usage Quotidien",
        "intro": "Le motif des cinq étoiles n'est pas réservé aux mâts — ici, il est réinventé sous forme d'objets du quotidien, d'animaux appréciés et de sites célèbres, tous représentés dans le rouge et l'or du drapeau.",
        "groups": {"objects": "Objets du Quotidien", "animals": "Animaux Populaires en Chine", "landmarks": "Monuments & la Carte de la Chine"},
        "disclaimer": "Illustrations créées pour ce site — il ne s'agit pas de produits officiels ou sous licence, ni d'une carte officielle.",
        "items": {
            "box": {"text": "Un Paquet aux Couleurs du Drapeau", "slug": "drapeau-chinois-paquet"},
            "car": {"text": "Une Voiture aux Couleurs du Drapeau", "slug": "drapeau-chinois-voiture"},
            "phone": {"text": "Un Smartphone aux Couleurs du Drapeau", "slug": "drapeau-chinois-smartphone"},
            "chest": {"text": "Un Coffre au Trésor aux Couleurs du Drapeau", "slug": "drapeau-chinois-coffre-au-tresor"},
            "teapot": {"text": "Une Théière aux Couleurs du Drapeau", "slug": "drapeau-chinois-theiere"},
            "teacup": {"text": "Une Tasse à Thé aux Couleurs du Drapeau", "slug": "drapeau-chinois-tasse-a-the"},
            "umbrella": {"text": "Un Parapluie aux Couleurs du Drapeau", "slug": "drapeau-chinois-parapluie"},
            "fan": {"text": "Un Éventail aux Couleurs du Drapeau", "slug": "drapeau-chinois-eventail"},
            "lantern": {"text": "Une Lanterne aux Couleurs du Drapeau", "slug": "drapeau-chinois-lanterne"},
            "bicycle": {"text": "Un Vélo aux Couleurs du Drapeau", "slug": "drapeau-chinois-velo"},
            "backpack": {"text": "Un Sac à Dos aux Couleurs du Drapeau", "slug": "drapeau-chinois-sac-a-dos"},
            "sneaker": {"text": "Une Basket aux Couleurs du Drapeau", "slug": "drapeau-chinois-basket"},
            "bird": {"text": "Un Oiseau en Forme de Drapeau", "slug": "drapeau-chinois-oiseau"},
            "dragon": {"text": "Un Dragon en Forme de Drapeau", "slug": "drapeau-chinois-dragon"},
            "dog": {"text": "Un Chien en Forme de Drapeau", "slug": "drapeau-chinois-chien"},
            "snake": {"text": "Un Serpent en Forme de Drapeau", "slug": "drapeau-chinois-serpent"},
            "panda": {"text": "Un Panda en Forme de Drapeau", "slug": "drapeau-chinois-panda"},
            "tiger": {"text": "Un Tigre en Forme de Drapeau", "slug": "drapeau-chinois-tigre"},
            "rabbit": {"text": "Un Lapin en Forme de Drapeau", "slug": "drapeau-chinois-lapin"},
            "ox": {"text": "Un Bœuf en Forme de Drapeau", "slug": "drapeau-chinois-boeuf"},
            "horse": {"text": "Un Cheval en Forme de Drapeau", "slug": "drapeau-chinois-cheval"},
            "monkey": {"text": "Un Singe en Forme de Drapeau", "slug": "drapeau-chinois-singe"},
            "rooster": {"text": "Un Coq en Forme de Drapeau", "slug": "drapeau-chinois-coq"},
            "koi": {"text": "Une Carpe Koï en Forme de Drapeau", "slug": "drapeau-chinois-carpe-koi"},
            "map": {"text": "Le Contour de la Chine aux Couleurs du Drapeau", "slug": "drapeau-chinois-contour-de-la-chine"},
            "greatwall": {"text": "La Grande Muraille aux Couleurs du Drapeau", "slug": "drapeau-chinois-grande-muraille"},
            "forbiddencity": {"text": "La Cité Interdite aux Couleurs du Drapeau", "slug": "drapeau-chinois-cite-interdite"},
            "templeofheaven": {"text": "Le Temple du Ciel aux Couleurs du Drapeau", "slug": "drapeau-chinois-temple-du-ciel"},
            "terracotta": {"text": "Un Guerrier en Terre Cuite aux Couleurs du Drapeau", "slug": "drapeau-chinois-guerrier-en-terre-cuite"},
            "pearltower": {"text": "La Tour de la Perle Orientale aux Couleurs du Drapeau", "slug": "drapeau-chinois-tour-de-la-perle-orientale"},
            "potala": {"text": "Le Palais du Potala aux Couleurs du Drapeau", "slug": "drapeau-chinois-palais-du-potala"},
            "guilin": {"text": "Les Monts Karstiques de Guilin aux Couleurs du Drapeau", "slug": "drapeau-chinois-monts-karstiques-de-guilin"},
            "pagoda": {"text": "La Pagode de la Grande Oie Sauvage aux Couleurs du Drapeau", "slug": "drapeau-chinois-pagode-de-la-grande-oie-sauvage"},
        },
    },
    "download": {
        "svg": "Télécharger « {name} » en SVG",
        "png": "Télécharger « {name} » en PNG",
    },
    "etiquette": {
        "title": "Usage & Étiquette",
        "text": "Le drapeau est hissé lors des fêtes nationales, en particulier la Fête nationale (1er octobre) et la Golden Week qui suit, ainsi que toute l'année sur les bâtiments gouvernementaux, les écoles et les postes frontières. Il ne doit jamais toucher le sol, être hissé à l'envers, ni être affiché endommagé ou décoloré. Les jours de deuil national, il est mis en berne.",
    },
    "footer": {
        "disclaimer": "Ce site est un site d'information indépendant et non officiel sur le drapeau de la République populaire de Chine. Il n'est affilié à aucun gouvernement, ni approuvé ou exploité en son nom.",
    },
}
