# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "Çin Bayrağı — Anlamı, Tarihi ve Renkleri",
        "description": "Çin bayrağı: beş yıldızın anlamı, tarihi, resmi renkler ve oranlar — ayrıca ücretsiz indirilebilen 33 illüstrasyon.",
    },
    "brand": "Çin Bayrağı",
    "nav": {"meaning": "Anlamı", "history": "Tarih", "data": "Teknik Bilgiler", "gallery": "Galeri", "etiquette": "Görgü Kuralları", "faq": "SSS", "historic": "Tarihî Bayraklar", "coloring": "Boyama Sayfası"},
    "hero": {
        "flag_alt": "Çin Halk Cumhuriyeti bayrağı — Beş Yıldızlı Kızıl Bayrak",
        "title": "Beş Yıldızlı Kızıl Bayrak",
        "subtitle": "Çin Halk Cumhuriyeti'nin ulusal bayrağı",
        "meta": "27 Eylül 1949'da kabul edildi · Oran 3:2 · Tasarımcı: Zeng Liansong",
    },
    "meaning": {
        "title": "Anlamı ve Sembolizmi",
        "intro": "1949'da kabul edilen tasarım; rengi, geometriyi ve siyasi tarihi anında tanınabilen tek bir amblemde birleştirir.",
        "cards": [
            {"title": "Kızıl Zemin", "text": "Kızıl renk devrimi simgeler; aynı zamanda Çin kültüründe şans ve kutlamanın geleneksel rengidir."},
            {"title": "Büyük Yıldız", "text": "Büyük altın yıldız, Çin Komünist Partisi'nin önderliğini temsil eder."},
            {"title": "Dört Küçük Yıldız", "text": "Bu önderlik altındaki Çin halkının büyük birliğini temsil ederler — geleneksel olarak işçi sınıfı, köylüler, kentli küçük burjuvazi ve ulusal burjuvazi olarak tanımlanır."},
            {"title": "Yıldızların Yönü", "text": "Her küçük yıldızın bir ucu tam olarak büyük yıldızın merkezine bakar; bu, ortak bir merkez etrafında toplanan birliği simgeler."},
            {"title": "Altın Sarısı", "text": "Kızıl zeminde parlak biçimde öne çıkması için seçilmiştir; ülkeyi aydınlatan devrim ışığını simgeler."},
        ],
    },
    "history": {
        "title": "Tarihçe ve Köken",
        "items": [
            {"date": "1949", "text": "Çin Halk Cumhuriyeti'nin kuruluşundan günler önce, 27 Eylül 1949'da Çin Halk Siyasi Danışma Konferansı, Beş Yıldızlı Kızıl Bayrağı resmen ulusal bayrak olarak kabul etti. Bayrak ilk kez 1 Ekim 1949'da, yeni cumhuriyetin ilan edildiği törende Tiananmen Meydanı'nda göndere çekildi."},
            {"date": "Tasarım", "text": "Kazanan tasarım, Zhejiang'lı bir ekonomist ve amatör sanatçı olan Zeng Liansong'a aittir. Tasarımı, yaklaşık 3.000 başvurunun yapıldığı ülke çapındaki bir yarışmada seçildi. İlk taslağında büyük yıldızın içinde orak ve çekiç vardı; seçici kurul, tasarımı sade tutmak ve diğer sosyalist devletlerin amblemlerinden ayırmak için bunları çıkardı."},
            {"date": "2004", "text": "Bayrağın oranları, yıldız geometrisi ve renklerine ilişkin resmî teknik standartlar ulusal standartlarda (yapım için GB 12982, renk için GB 15092) belirlendi."},
        ],
    },
    "data": {
        "title": "Teknik Bilgiler",
        "ratio": {"title": "Oranlar", "text": "Bayrağın en-boy oranı."},
        "grid": {"title": "Yapım Izgarası", "text": "30 × 20 birimlik bir ızgara. Büyük yıldızın merkezi (5,5), dış yarıçapı 3. Küçük yıldızların dış yarıçapı 1; merkezleri (10,2), (12,4), (12,7), (10,9) noktalarındadır."},
        "colors": {
            "title": "Renkler",
            "red": "Kızıl — Pantone 186 C · RGB 222,41,16 · #DE2910",
            "yellow": "Sarı — Pantone 012 C · RGB 255,222,0 · #FFDE00",
            "note": "Resmî standart, renkleri dijital kodlarla değil fiziksel referans örnekleriyle tanımlar — ekrandaki onaltılık değerler yalnızca yaklaşık değerlerdir.",
        },
        "orientation": {"title": "Yıldız Yönü Kuralı", "text": "Her küçük yıldız, uçlarından biri büyük yıldızın merkeziyle tam hizalanacak şekilde döndürülmüştür."},
    },
    "gallery": {
        "title": "Galeri ve Günlük Kullanım",
        "intro": "Beş yıldız motifi yalnızca bayrak direkleri için değil — burada günlük eşyalar, sevilen hayvanlar ve ünlü yapılar olarak, bayrağın kendi kızıl ve altın renklerinde yeniden yorumlanıyor.",
        "groups": {"objects": "Günlük Eşyalar", "animals": "Çin'de Sevilen Hayvanlar", "landmarks": "Yapılar ve Çin Haritası"},
        "disclaimer": "Bu site için hazırlanmış örnek illüstrasyonlardır — resmî veya lisanslı ürünler değildir; resmî bir harita da değildir.",
        "license": "Görsel lisansı: Bu sayfadaki tüm bayrak illüstrasyonları ticari amaçlar dahil ücretsiz indirilebilir ve kullanılabilir. Kaynak gösterilmesi (china-flag.cn bağlantısı) memnuniyetle karşılanır ancak zorunlu değildir.",
        "items": {
            "box": {"text": "Paket Şeklinde Çin Bayrağı", "slug": "cin-bayragi-paket"},
            "car": {"text": "Araba Şeklinde Çin Bayrağı", "slug": "cin-bayragi-araba"},
            "phone": {"text": "Akıllı Telefon Şeklinde Çin Bayrağı", "slug": "cin-bayragi-akilli-telefon"},
            "chest": {"text": "Hazine Sandığı Şeklinde Çin Bayrağı", "slug": "cin-bayragi-hazine-sandigi"},
            "teapot": {"text": "Çaydanlık Şeklinde Çin Bayrağı", "slug": "cin-bayragi-caydanlik"},
            "teacup": {"text": "Çay Fincanı Şeklinde Çin Bayrağı", "slug": "cin-bayragi-cay-fincani"},
            "umbrella": {"text": "Şemsiye Şeklinde Çin Bayrağı", "slug": "cin-bayragi-semsiye"},
            "fan": {"text": "Yelpaze Şeklinde Çin Bayrağı", "slug": "cin-bayragi-yelpaze"},
            "lantern": {"text": "Fener Şeklinde Çin Bayrağı", "slug": "cin-bayragi-fener"},
            "bicycle": {"text": "Bisiklet Şeklinde Çin Bayrağı", "slug": "cin-bayragi-bisiklet"},
            "backpack": {"text": "Sırt Çantası Şeklinde Çin Bayrağı", "slug": "cin-bayragi-sirt-cantasi"},
            "sneaker": {"text": "Spor Ayakkabı Şeklinde Çin Bayrağı", "slug": "cin-bayragi-spor-ayakkabi"},
            "bird": {"text": "Kuş Şeklinde Çin Bayrağı", "slug": "cin-bayragi-kus"},
            "dragon": {"text": "Ejderha Şeklinde Çin Bayrağı", "slug": "cin-bayragi-ejderha"},
            "dog": {"text": "Köpek Şeklinde Çin Bayrağı", "slug": "cin-bayragi-kopek"},
            "snake": {"text": "Yılan Şeklinde Çin Bayrağı", "slug": "cin-bayragi-yilan"},
            "panda": {"text": "Panda Şeklinde Çin Bayrağı", "slug": "cin-bayragi-panda"},
            "tiger": {"text": "Kaplan Şeklinde Çin Bayrağı", "slug": "cin-bayragi-kaplan"},
            "rabbit": {"text": "Tavşan Şeklinde Çin Bayrağı", "slug": "cin-bayragi-tavsan"},
            "ox": {"text": "Öküz Şeklinde Çin Bayrağı", "slug": "cin-bayragi-okuz"},
            "horse": {"text": "At Şeklinde Çin Bayrağı", "slug": "cin-bayragi-at"},
            "monkey": {"text": "Maymun Şeklinde Çin Bayrağı", "slug": "cin-bayragi-maymun"},
            "rooster": {"text": "Horoz Şeklinde Çin Bayrağı", "slug": "cin-bayragi-horoz"},
            "koi": {"text": "Koi Balığı Şeklinde Çin Bayrağı", "slug": "cin-bayragi-koi-baligi"},
            "map": {"text": "Çin Haritası Şeklinde Çin Bayrağı", "slug": "cin-bayragi-cin-haritasi"},
            "greatwall": {"text": "Çin Seddi Şeklinde Çin Bayrağı", "slug": "cin-bayragi-cin-seddi"},
            "forbiddencity": {"text": "Yasak Şehir Şeklinde Çin Bayrağı", "slug": "cin-bayragi-yasak-sehir"},
            "templeofheaven": {"text": "Cennet Tapınağı Şeklinde Çin Bayrağı", "slug": "cin-bayragi-cennet-tapinagi"},
            "terracotta": {"text": "Terrakota Askeri Şeklinde Çin Bayrağı", "slug": "cin-bayragi-terrakota-askeri"},
            "pearltower": {"text": "Doğu İncisi Kulesi Şeklinde Çin Bayrağı", "slug": "cin-bayragi-dogu-incisi-kulesi"},
            "potala": {"text": "Potala Sarayı Şeklinde Çin Bayrağı", "slug": "cin-bayragi-potala-sarayi"},
            "guilin": {"text": "Guilin Karst Dağları Şeklinde Çin Bayrağı", "slug": "cin-bayragi-guilin-daglari"},
            "pagoda": {"text": "Büyük Yaban Kazı Pagodası Şeklinde Çin Bayrağı", "slug": "cin-bayragi-yaban-kazi-pagodasi"},
        },
    },
    "download": {
        "svg": "{name} görselini SVG olarak indir",
        "png": "{name} görselini PNG olarak indir",
    },
    "historical": {
        "title": "Çin'in Tarihî Bayrakları",
        "intro": "Beş Yıldızlı Kızıl Bayrak'tan önce Çin'de çok farklı sancaklar dalgalanıyordu. Bu stilize illüstrasyonlar en bilinen üç öncülü gösteriyor.",
        "items": {
            "qing": {
                "name": "Qing Ejderha Bayrağı",
                "period": "1889–1912",
                "text": "Son imparatorluk hanedanı, kızıl bir inciyi kovalayan gök mavisi bir ejderhanın işlendiği altın sarısı bir bayrak kullanıyordu — sarı, imparatorun rengiydi.",
                "alt": "Qing hanedanının ejderha bayrağı (1889–1912) — stilize illüstrasyon",
                "slug": "tarihi-cin-bayragi-qing-ejderha",
            },
            "fivecolor": {
                "name": "Beş Renkli Bayrak",
                "period": "1912–1928",
                "text": "Çin Cumhuriyeti'nin ilk bayrağı: beş şerit, Çin'in beş büyük halkını — Han, Mançu, Moğol, Hui ve Tibetlileri — temsil ediyordu.",
                "alt": "Çin Cumhuriyeti'nin beş renkli bayrağı (1912–1928)",
                "slug": "tarihi-cin-bayragi-bes-renkli",
            },
            "bluesky": {
                "name": "Mavi Gök, Beyaz Güneş, Kızıl Toprak",
                "period": "1928–1949",
                "text": "1949'a kadar anakaradaki cumhuriyet döneminin ulusal bayrağı; mavi köşelikte on iki ışınlı beyaz bir güneş yer alır.",
                "alt": "Çin Cumhuriyeti dönemi bayrağı (1928–1949), mavi köşelik ve beyaz güneşli",
                "slug": "tarihi-cin-bayragi-mavi-gok-beyaz-gunes",
            },
        },
    },
    "coloring": {
        "title": "Boyama Sayfası",
        "text": "Boyamak için Çin bayrağının yazdırılabilir dış çizgisi — okul veya yağmurlu bir öğleden sonrası için ideal. İpucu: büyük yıldız ve dört küçük yıldız, kızıl zemin üzerine altın sarısıyla boyanır.",
        "caption": "Boyama Sayfası Olarak Çin Bayrağı",
        "alt": "Çin bayrağı boyama sayfası — Beş Yıldızlı Kızıl Bayrak'ın yazdırılabilir dış çizgisi",
        "slug": "cin-bayragi-boyama-sayfasi",
    },
    "emoji": {
        "title": "Çin Bayrağı Emojisi",
        "text": "Çin bayrağı emojisi 🇨🇳, iki bölgesel gösterge sembolünden oluşur: C (U+1F1E8) ve N (U+1F1F3). Tek tıkla buradan kopyalayın.",
        "copy": "Emojiyi kopyala",
        "copied": "Kopyalandı!",
        "note": "Bazı Windows sistemlerinde emoji “CN” harfleri olarak görünür — telefonlarda ve çoğu diğer cihazda bayrak görüntülenir.",
    },
    "consent": {
        "text": "Bu sitenin kullanımını Google Analytics ile ölçmek istiyoruz. İstatistik çerezleri yalnızca onay vermeniz hâlinde yerleştirilir.",
        "accept": "Kabul et",
        "decline": "Reddet",
        "settings": "Çerez ayarları",
    },
    "faq": {
        "title": "Sıkça Sorulan Sorular",
        "items": [
            {"q": "Çin bayrağındaki beş yıldız ne anlama gelir?",
             "a": "Büyük altın yıldız Çin Komünist Partisi'nin önderliğini, dört küçük yıldız ise Çin halkının büyük birliğini temsil eder. Her küçük yıldızın bir ucu tam olarak büyük yıldızın merkezine bakar."},
            {"q": "Çin bayrağında hangi renkler vardır?",
             "a": "Kızıl ve altın sarısı. Kızıl zemin Pantone 186 C'ye (ekranda yaklaşık #DE2910), yıldızlar Pantone 012 C'ye (yaklaşık #FFDE00) karşılık gelir. Kızıl devrimi, sarı ülkeyi aydınlatan ışığı simgeler."},
            {"q": "Çin bayrağı ne zaman kabul edildi?",
             "a": "27 Eylül 1949'da. İlk kez 1 Ekim 1949'da, Çin Halk Cumhuriyeti'nin ilan edildiği gün Pekin'deki Tiananmen Meydanı'nda göndere çekildi."},
            {"q": "Çin bayrağını kim tasarladı?",
             "a": "Zhejiang eyaletinden ekonomist ve amatör sanatçı Zeng Liansong. Tasarımı, yaklaşık 3.000 başvurunun yapıldığı ülke çapındaki yarışmayı kazandı."},
            {"q": "Çin bayrağının en-boy oranı nedir?",
             "a": "3:2 — bayrağın uzunluğu yüksekliğinin bir buçuk katıdır."},
            {"q": "Bu sitedeki bayrak görsellerini ücretsiz indirebilir miyim?",
             "a": "Evet. Galerideki her illüstrasyon, SVG vektör dosyası veya PNG görseli olarak ücretsiz indirilebilir."},
        ],
    },
    "etiquette": {
        "title": "Göndere Çekme ve Görgü Kuralları",
        "text": "Bayrak, başta Ulusal Gün (1 Ekim) ve onu izleyen Altın Hafta olmak üzere ulusal bayramlarda; devlet binalarında, okullarda ve sınır kapılarında ise yıl boyunca göndere çekilir. Bayrak asla yere değmemeli, ters asılmamalı, yıpranmış veya solmuş hâlde kullanılmamalıdır. Ulusal yas günlerinde yarıya indirilir.",
    },
    "footer": {
        "disclaimer": "Bu, Çin Halk Cumhuriyeti bayrağı hakkında bağımsız ve gayriresmî bir bilgi sitesidir. Hiçbir hükûmetle bağlantılı değildir; hiçbir hükûmet tarafından onaylanmamıştır veya onun adına işletilmemektedir.",
    },
}
