# -*- coding: utf-8 -*-
DATA = {
    "meta": {
        "title": "中国国旗——含义、历史与五星红旗知识 | China Flag",
        "description": "深入了解中华人民共和国国旗:五颗星的含义、五星红旗的历史、官方颜色与比例、悬挂礼仪,以及国旗主题插画。",
    },
    "brand": "中国国旗",
    "nav": {"meaning": "含义", "history": "历史", "data": "技术数据", "gallery": "图库", "etiquette": "礼仪"},
    "hero": {
        "flag_alt": "中华人民共和国国旗——五星红旗",
        "title": "五星红旗",
        "subtitle": "中华人民共和国国旗",
        "meta": "1949年9月27日通过 · 长宽比 3:2 · 设计者:曾联松",
    },
    "meaning": {
        "title": "含义与象征",
        "intro": "五星红旗诞生于1949年,其设计融合了色彩、几何与历史,凝练成一面辨识度极高的国旗。",
        "cards": [
            {"title": "红色底色", "text": "红色象征革命,同时也是中国传统文化中喜庆与吉祥的颜色。"},
            {"title": "大五角星", "text": "大五角星象征中国共产党的领导。"},
            {"title": "四颗小星", "text": "象征在中国共产党领导下全国人民的大团结——传统上分别代表工人阶级、农民阶级、城市小资产阶级和民族资产阶级。"},
            {"title": "星的朝向", "text": "每颗小星均有一角正对大星中心,象征紧密团结、众星拱月。"},
            {"title": "金黄色", "text": "在红色底色上熠熠生辉,象征革命光芒普照大地。"},
        ],
    },
    "history": {
        "title": "历史与起源",
        "items": [
            {"date": "1949", "text": "1949年9月27日,在中华人民共和国成立前夕,中国人民政治协商会议第一届全体会议正式通过五星红旗为国旗。同年10月1日,在开国大典上,五星红旗首次在天安门广场升起。"},
            {"date": "设计", "text": "获选设计出自浙江籍经济学家、业余美术爱好者曾联松之手。当时面向全国征集国旗图案,共收到近3000件应征稿。他最初的设计在大星内绘有镰刀锤子图案,评选委员会为使图案更简洁、并与其他社会主义国家的徽记有所区别,将其移除。"},
            {"date": "2004", "text": "国家标准(GB 12982 关于制法,GB 15092 关于色彩)对国旗的比例、五星的几何构造及颜色作出了正式规定。"},
        ],
    },
    "data": {
        "title": "技术数据",
        "ratio": {"title": "比例", "text": "旗面长与高之比。"},
        "grid": {"title": "制图网格", "text": "旗面划分为30×20单位网格。大星圆心(5,5),外接圆半径3;四颗小星外接圆半径1,圆心分别为(10,2)、(12,4)、(12,7)、(10,9)。"},
        "colors": {
            "title": "颜色",
            "red": "红色——潘通186C · RGB 222,41,16 · #DE2910",
            "yellow": "黄色——潘通012C · RGB 255,222,0 · #FFDE00",
            "note": "国家标准以实物色样而非数字色值定义颜色,因此屏幕显示的十六进制值仅为近似值。",
        },
        "orientation": {"title": "星的朝向规则", "text": "每颗小星的其中一角均精确指向大星中心。"},
    },
    "gallery": {
        "title": "图库与日常应用",
        "intro": "五星红旗的元素不仅限于旗杆之上——在这里,我们用国旗本身的红与金,重新演绎出日常物品、人气动物与著名景点的造型。",
        "groups": {"objects": "日常物品", "animals": "中国人气动物", "landmarks": "地标名胜与中国地图"},
        "disclaimer": "以上为本站制作的示意图,并非官方或授权产品,亦非官方地图。",
        "items": {
            "box": {"text": "旗帜配色的包裹", "slug": "qizhi-peise-de-baoguo"},
            "car": {"text": "旗帜配色的汽车", "slug": "qizhi-peise-de-qiche"},
            "phone": {"text": "旗帜配色的手机", "slug": "qizhi-peise-de-shouji"},
            "chest": {"text": "旗帜配色的宝箱", "slug": "qizhi-peise-de-baoxiang"},
            "teapot": {"text": "旗帜配色的茶壶", "slug": "qizhi-peise-de-chahu"},
            "teacup": {"text": "旗帜配色的茶杯", "slug": "qizhi-peise-de-chabei"},
            "umbrella": {"text": "旗帜配色的雨伞", "slug": "qizhi-peise-de-yusan"},
            "fan": {"text": "旗帜配色的扇子", "slug": "qizhi-peise-de-shanzi"},
            "lantern": {"text": "旗帜配色的灯笼", "slug": "qizhi-peise-de-denglong"},
            "bicycle": {"text": "旗帜配色的自行车", "slug": "qizhi-peise-de-zixingche"},
            "backpack": {"text": "旗帜配色的背包", "slug": "qizhi-peise-de-beibao"},
            "sneaker": {"text": "旗帜配色的运动鞋", "slug": "qizhi-peise-de-yundongxie"},
            "bird": {"text": "旗帜造型的小鸟", "slug": "qizhi-zaoxing-de-xiaoniao"},
            "dragon": {"text": "旗帜造型的龙", "slug": "qizhi-zaoxing-de-long"},
            "dog": {"text": "旗帜造型的小狗", "slug": "qizhi-zaoxing-de-xiaogou"},
            "snake": {"text": "旗帜造型的蛇", "slug": "qizhi-zaoxing-de-she"},
            "panda": {"text": "旗帜造型的熊猫", "slug": "qizhi-zaoxing-de-xiongmao"},
            "tiger": {"text": "旗帜造型的老虎", "slug": "qizhi-zaoxing-de-laohu"},
            "rabbit": {"text": "旗帜造型的兔子", "slug": "qizhi-zaoxing-de-tuzi"},
            "ox": {"text": "旗帜造型的牛", "slug": "qizhi-zaoxing-de-niu"},
            "horse": {"text": "旗帜造型的马", "slug": "qizhi-zaoxing-de-ma"},
            "monkey": {"text": "旗帜造型的猴子", "slug": "qizhi-zaoxing-de-houzi"},
            "rooster": {"text": "旗帜造型的公鸡", "slug": "qizhi-zaoxing-de-gongji"},
            "koi": {"text": "旗帜造型的锦鲤", "slug": "qizhi-zaoxing-de-jinli"},
            "map": {"text": "旗帜配色的中国轮廓", "slug": "qizhi-peise-de-zhongguo-lunkuo"},
            "greatwall": {"text": "旗帜配色的长城", "slug": "qizhi-peise-de-changcheng"},
            "forbiddencity": {"text": "旗帜配色的故宫", "slug": "qizhi-peise-de-gugong"},
            "templeofheaven": {"text": "旗帜配色的天坛", "slug": "qizhi-peise-de-tiantan"},
            "terracotta": {"text": "旗帜配色的兵马俑", "slug": "qizhi-peise-de-bingmayong"},
            "pearltower": {"text": "旗帜配色的东方明珠塔", "slug": "qizhi-peise-de-dongfang-mingzhu-ta"},
            "potala": {"text": "旗帜配色的布达拉宫", "slug": "qizhi-peise-de-budala-gong"},
            "guilin": {"text": "旗帜配色的桂林山水", "slug": "qizhi-peise-de-guilin-shanshui"},
            "pagoda": {"text": "旗帜配色的大雁塔", "slug": "qizhi-peise-de-dayan-ta"},
        },
    },
    "download": {
        "svg": "下载「{name}」SVG图片",
        "png": "下载「{name}」PNG图片",
    },
    "etiquette": {
        "title": "悬挂与礼仪",
        "text": "国旗在国庆节(10月1日)及随后的黄金周等重要节日悬挂,并常年悬挂于政府机关、学校及口岸等场所。国旗不得触地、不得倒挂,亦不得使用破损、褪色的旗帜。在全国哀悼日,应下半旗志哀。",
    },
    "footer": {
        "disclaimer": "本网站为关于中华人民共和国国旗的独立、非官方资讯网站,与任何政府机构均无关联,亦未获其认可或代表其运营。",
    },
}
